### ISSUE TITLE
smpeg present but cannot be compiled

### ISSUE THREAD

**Issue by DrItanium** [Aleph-One-Marathon/alephone#102]
When running autogen.sh on master I encounter the following warning:

> checking smpeg/smpeg.h usability... no
checking smpeg/smpeg.h presence... yes
configure: WARNING: smpeg/smpeg.h: present but cannot be compiled
configure: WARNING: smpeg/smpeg.h:     check for missing prerequisite headers?
configure: WARNING: smpeg/smpeg.h: see the Autoconf documentation
configure: WARNING: smpeg/smpeg.h:     section "Present But Cannot Be Compiled"
configure: WARNING: smpeg/smpeg.h: proceeding with the compiler's result
configure: WARNING:     ## -------------------------------------------------------------------- ##
configure: WARNING:     ## Report this to https://github.com/Aleph-One-Marathon/alephone/issues ##
configure: WARNING:     ## -------------------------------------------------------------------- ##
checking for smpeg/smpeg.h... no

While configuration is successful, I was asked to report this so I have :). 

My system is:

Operating System: Linux
Architecture: AMD64
Distribution: Gentoo 
GCC Version: 7.3.0 (Gentoo 7.3.0 p1.0)

What's odd is that there are two smpeg libraries listed in emerge:

*  media-libs/smpeg
      Latest version available: 0.4.4-r10
      Latest version installed: 0.4.4-r10
      Size of files: 312 KiB
      Homepage:      https://icculus.org/smpeg/
      Description:   SDL MPEG Player Library
      License:       LGPL-2

*  media-libs/smpeg2
      Latest version available: 2.0.0-r3
      Latest version installed: [ Not Installed ]
      Size of files: 305 KiB
      Homepage:      https://icculus.org/smpeg/
      Description:   SDL MPEG Player Library
      License:       LGPL-2

Am I supposed to be using smpeg2? 

Let me know if there is any other information you need.

**Comment by Hopper262** [comment]
Thank you for the report! I've belatedly updated the [install instructions](https://github.com/Aleph-One-Marathon/alephone/wiki/Linux-Install-Instructions) with some relevant information. Regarding your situation:

* SMPEG is ignored if FFmpeg is enabled
* If FFmpeg is disabled, SMPEG is used in custom scenarios with movie cutscenes
* You do need smpeg2 instead of smpeg 0.x to build with master
