### ISSUE TITLE
Crash on No artificial colors.

### ISSUE THREAD

**Issue by ObsidianCarnageX12** [Aleph-One-Marathon/alephone#105]
Platform : Ubuntu 18.04

if you get past Pfhor Your Eyes Only in one sitting the game crashes.

GDB shows this :

Thread 1 "alephone" received signal SIGSEGV, Segmentation fault.
sweeplist (L=0x5555569f7d70, p=0x555558daa470, count=48, count@entry=85)
    at lgc.c:729
729	    int marked = gch(curr)->marked;

**Comment by Hopper262** [comment]
OK, thanks for the info!
