### ISSUE TITLE
Patch for compliation on Arch Linux - New FFMPEG

### ISSUE THREAD

**Issue by Koatman** [Aleph-One-Marathon/alephone#106]
Hi,

Attached is a patch to allow compiliation of alephone on newer Arch linux installations.

Thanks!
[Movie.cpp.patch.TXT](https://github.com/Aleph-One-Marathon/alephone/files/2300323/Movie.cpp.patch.TXT)

**Comment by Hopper262** [comment]
Thanks! The fix is in 902cd09 and part of the 1.3b1 release.
