### ISSUE TITLE
Trying to switch to OpenGL mode usually results in the game being opened again but invisible

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#113]
In 1.3b2 It doesnt switch to openGL when you switch to it, it opens the game again with a transparent fullscreen
the transparent fullscreen it opens cannot be interacted with the mouse
or the controller
but pressing escape does exit menus
at least you can hear it do that
you seem to be able to create multiple transparent fullscreens and they all close when you quit the one they spawned from thats still in software mode. On Windows 7 64 bit.

**Comment by orbea** [comment]
fwiw I can't reproduce this on linux using mesa (nouveau).

**Comment by kandriod** [comment]
It turns out my PC had an old OpenGL this whole time, never mind my openGL issues.

**Comment by kandriod** [comment]
So I have sorted out my position on my OpemGL version and whatnot and I do think this is an important issue after all and not a personal hardware problem.

**Comment by kandriod** [comment]
I have found a workaround for the rare chance it happens, click the lower area of the screen after switching to openGL and it will take you to the openGL instance of the game and then it will close the software mode instance, I have no idea how it works but it just does.

**Comment by treellama** [comment]
Can you retry this in 1.8? We are always updating the screen now,  so I think this should be fixed

**Comment by kandriod** [comment]
It was fixed.
