### ISSUE TITLE
Player attack animations in M1 are bugged.

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#130]
This is most easily seen in third person mode due to there not being online yet. 
![image](https://user-images.githubusercontent.com/25878306/49336403-6d376500-f5b6-11e8-8ea6-9f9ba648fefa.png) I have no idea if this applies to openGL mode too.

**Comment by TrajansRow** [comment]
I can reproduce this in the programmable renderer also. It's particularly noticeable in multiplayer games.

![rendering glitch](https://user-images.githubusercontent.com/25617921/50577140-ed83fc80-0de6-11e9-9727-285a26774d38.png)

**Comment by TrajansRow** [comment]
I was just looking at this in the frame debugger, and it seems the renderer is working fine (I don't see any corrupt texcoords, etc). It just looks like the wrong texture is being bound (or possibly not loaded correctly at game start) when drawing the firing half of the torso. Interestingly, this does not affect M2 or M8.

<img width="1970" alt="framedebug" src="https://user-images.githubusercontent.com/25617921/50579179-647dbd00-0e08-11e9-84c4-5352facf013e.png">
