### ISSUE TITLE
can't skip chapter screens

### ISSUE THREAD

**Issue by treellama** [Aleph-One-Marathon/alephone#134]
In git master, pressing the space bar or mouse button no longer skips the chapter screen.

**Comment by treellama** [comment]
This seems to be related to #150 in the _most bizarre_ way. Sometimes when I launch Marathon 2, and level select skip to What About Bob? the first left mouse press doesn't stop the chapter screen scrolling, but additionally it then absorbs the first key press as well! Whereas, if I tap the space bar first instead of the left mouse button, the chapter screen stops scrolling immediately.

Going to try to track down #150 first, then see if this still gives me trouble.

**Comment by Hopper262** [comment]
Testing on Fedora 29, I never managed to get a mouse or key press ignored entirely, but I did have delays of up to 1 second between clicking the mouse, and having the animation stop scrolling. I haven't seen any similar delays in gameplay or menus, just on the scrolling.
