### ISSUE TITLE
Mouse aiming preferences not preserved

### ISSUE THREAD

**Issue by wrkncacnter7** [Aleph-One-Marathon/alephone#144]
Using the latest code in master, if you go to the preferences -> controls and click the "Mouse Aiming" checkbox, it has no effect in game.  The checkbox will always show as checked when you go to the controls screen, whether mouse aiming is on or off.

**Comment by SpookyMarathon** [comment]
Make sure you aren't switching between the beta and the stable aleph. It will nuke your preferences if you load up previous aleph. Cheers.
