### ISSUE TITLE
Terminal PICTs with vector data display incorrectly

### ISSUE THREAD

**Issue by ravenshining** [Aleph-One-Marathon/alephone#155]
Every illustrated terminal page from the classic, award-winning "Missed Island" scenario is improperly scaled or cropped under Aleph One.

Marathon Infinity:
![missed1](https://user-images.githubusercontent.com/31712538/55084266-03e9cf00-5049-11e9-9032-ea0be177836c.png)

Screenshot from Aleph One git master compiled on Debian 8:
![Intro_0001](https://user-images.githubusercontent.com/31712538/55084286-0c420a00-5049-11e9-9c06-2b1cfccfc230.png)

MacBinary'd map file for use with A1:
[Missed Island map.sceA.tar.gz](https://github.com/Aleph-One-Marathon/alephone/files/3013668/Missed.Island.map.sceA.tar.gz)

The above terminal image extracted from the map with ResSploder in SheepShaver.  Attempting to open this file with GraphicConverter 3 gave a warning that vector data will be lost if the image is saved:
[140.pct.tar.gz](https://github.com/Aleph-One-Marathon/alephone/files/3013665/140.pct.tar.gz)

The above PICT converted to PNG format with ImageMagick:
![140](https://user-images.githubusercontent.com/31712538/55084926-dcdfcd00-5049-11e9-86ce-dc25c4157b7f.png)

It appears every terminal PICT from Missed Island is an oversized image with some scaling and cropping data, or even... I don't know what I'm seeing above, is that a 3D image?  Most of the images are definitely just 2D, I guess I chose a weird example.  Here's a definitely 2D example:

Marathon ∞:
![missedpedestal](https://user-images.githubusercontent.com/31712538/55088052-28e14080-504f-11e9-9a4a-1eff0a3fff9c.png)

Aleph One:
![Moretricks_0000](https://user-images.githubusercontent.com/31712538/55088064-2d0d5e00-504f-11e9-84b5-db15c5f35082.png)

PICT:
[155.PICT.pct.tar.gz](https://github.com/Aleph-One-Marathon/alephone/files/3013878/155.PICT.pct.tar.gz)

PNG:
![155 PICT](https://user-images.githubusercontent.com/31712538/55088195-6b0a8200-504f-11e9-9a13-c8af645b4713.png)

I don't know if other maps from the 90's are also like this, or if that's just how Jason Harper did things, but here it is.

**Comment by Iritscen** [comment]
That "MetaTools" watermark on the original image sure is nice.  Anyway, you might already realize this, but Apple's long-forgotten PICT format was object-oriented, or could be: https://en.wikipedia.org/wiki/PICT .  So apparently whatever the modder used to produce these pictures embedded the bitmap data in an object which A1 doesn't read correctly, at least as far as its dimensions/cropping.

**Comment by treellama** [comment]
https://github.com/jorio/pomme

**Comment by treellama** [comment]
We have been unable to find an open source PICT decode that can do these properly. We also haven't run across another scenario that has such messed-up PICTs. So I think the solution is to re-convert these with GraphicConverter in classic mac OS, and post a new version for Aleph One.
