### ISSUE TITLE
'Aleph One 1.3b3' marked as 'Latest Release' in GitHub

### ISSUE THREAD

**Issue by core-code** [Aleph-One-Marathon/alephone#157]
since 'Aleph One 1.3b3' is still a beta-quality release (as documented on the homepage) could you make sure to correctly mark it as 'Pre-release' in GitHub, instead of as 'Latest Release'?

thanks!

**Comment by Hopper262** [comment]
At this point in the development cycle, 1.3b3 should be more stable than the four-year-old 1.2.1 for the majority of users. Think of it as 1.3rc1 if that helps. I want to get a bit more outside testing before labeling it as final, and exposing it as the default release on GitHub is a way to widen the audience to reach that goal.

I will add release notes to clarify this once I get time to finish them.
