### ISSUE TITLE
M1 original HUD is missing ammo bar in software 1.3b3

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#158]
![image](https://user-images.githubusercontent.com/25878306/55406960-ed90b700-5511-11e9-9d97-3843716460f5.png)
The image of the weapon you're using also doesn't appear next to the name.

**Comment by kandriod** [comment]
I've also confirmed the ammo bar and weapon image were missing in software classic HUD in 1.3b2 as well.

**Comment by djkontraktor** [comment]
There was an updated version of the M1 HUD released on Simplici7y. I just downloaded that version and used it instead. That fixed the problem.

**Comment by treellama** [comment]
This was fixed in 6da2726
