### ISSUE TITLE
Controller cannot be changed to "Treat as analog stick" in 1.3b3

### ISSUE THREAD

**Issue by kandriod** [Aleph-One-Marathon/alephone#160]
Every time you change it to treat as analog stick and click accept it will go right back to "treat as D-pad"

**Comment by kandriod** [comment]
This only happens in M1, not in durandal or infinity.

**Comment by baconicsynergy** [comment]
Hello friends. I'm encountering the same bug on Alephone 1.5 when using a bluetooth PS4 controller. This bug occurs on all three games unlike the person above me.

Hopefully a developer with a controller can solve this!
