### ISSUE TITLE
Main menu is small

### ISSUE THREAD

**Issue by Jman7** [Aleph-One-Marathon/alephone#162]
M1 main menu is small. Not in M2 or Mi. 2015 & 2015 versions. I had installed 2019 version at one point. It didn't always used to be like this. But Nature's Peace does not work with 2019 version AFAIK. 

edit: just needed to set fill screen. I dont think Natures peace (or other plugins?) work.

**Comment by MOFTAD** [comment]
Changing high DPI settings fixed this issue for me.

Executable properties > Compatibility tab > Change high DPI settings > Check _Override high DPI scaling behavior_ > Set the option to _Application_.
