### ISSUE TITLE
Support for additional Mouse Buttons

### ISSUE THREAD

**Issue by yar0th3ungg0y** [Aleph-One-Marathon/alephone#164]
I'm currently unable to bind button 5 on my 5 button mouse in version 1.3b3 (2019-03-31)

It was previously usable in 1.2.1 (2015-06-20), though it appeared incorrectly as "mouse 7", mouse 4 appears as "mouse 6".
![Annotation 2019-06-11 122932](https://user-images.githubusercontent.com/51716553/59294409-0c64a580-8c47-11e9-858b-86418ba12d41.jpg)
Mouse 4 is usable in 1.3.1 appearing as Mouse X1. Mouse 5 is not bindable.
![Annotation 2019-06-11 123506](https://user-images.githubusercontent.com/51716553/59294394-04a50100-8c47-11e9-8116-24296bd20aed.jpg)
I suppose that the number of the button as seen by the A1 engine may depend upon mouse hardware specifications.

I request to restore this functionality not only for 5 button mouses but a wider variety of Gaming/Precision mouses featuring 7 or more buttons as well.

Resetting to defaults does not fix this behavior, I also tried to open the 1.2.1 Marathon 1 in the newer Aleph One with the previous settings and somehow Mouse 4 was set to Scrollwheel Up and Mouse 5 to Scrollwheel Down.

**Comment by treellama** [comment]
What operating system is this?

**Comment by yar0th3ungg0y** [comment]
Windows 10 version 1909

**Comment by treellama** [comment]
The mouse buttons are handled by SDL--but we are going to integrate the latest version into the next release, which may help. I know it has support for a ton more game controllers, but it doesn't say anything about mouse buttons.

**Comment by yar0th3ungg0y** [comment]
Would it help for me to send you the prefs of each...

**Comment by treellama** [comment]
SDL only supports 5 mouse buttons plus the scroll wheel, but I did enable binding button 5 in that commit

**Comment by yar0th3ungg0y** [comment]
Excellent, thank you... It is alright, most 7 button mouses have the buttons from 6 onwards as programmable to different keys or gamepad buttons which are handled by the mouse's driver and not Windows by default unlike the first 5 buttons supported by SDL. It was something I didn't know when I opened this issue.
