### ISSUE TITLE
Skybox texture corruption on Windows with Intel HD 3000 graphics in OpenGL mode.

### ISSUE THREAD

**Issue by mz1193** [Aleph-One-Marathon/alephone#165]
As stated in the title, attempting to run this on Windows (tested on 8.1 and 10) with an Intel HD 3000 in OpenGL mode results in corrupted skybox textures. Curiously, this only seems to affect replacements from the plugins, the vanilla skyboxes render just fine. This can be seen in every game of the trilogy if using the bundled HD plugins.

A few things to note: This bug has never occurred for me under various Linux distributions (driver differences, I'm sure) and the bug does not happen if using the legacy OpenGL (Classic) renderer from the last stable release. This bug is also exclusive to the new OpenGL mode when running under these conditions, and does not appear in Software mode (which doesn't seem to utilize texture replacements anyway.)

**Comment by pfhore-github** [comment]
recent AMD drivers has the same glich.

https://github.com/Aleph-One-Marathon/alephone/pull/374
