### ISSUE TITLE
1.3b3 can activate mission controll on mac

### ISSUE THREAD

**Issue by HerbertWest7** [Aleph-One-Marathon/alephone#167]
By default, holding control and pressing the up arrow causes mission control to activate on mac OS 10.12.6. This behavior should be disabled while playing Aleph One as this interrupts one's ability to control the game, and is disabled for 1.2.1 and every earlier version that I have used. However, it is not disabled for 1.3b3. I encountered this problem while playing through Marathon 2 using OpenGL rendering, but I doubt that it's specific to that scenario or graphics. 

One workaround is to change the hotkeys that activate mission control to something that won't be pressed while using Aleph One - which is fine, but the existence of this bug suggests that there's a deeper problem with 1.3b3 passing keyboard input along to the finder when it shouldn't.

**Comment by treellama** [comment]
This was a deliberate choice, for better or worse, to run as a borderless window in full screen now in SDL 2. Switching modes and taking over the whole screen has caused lots of issues in the past.

Among other things, the new approach allows you to swipe left/right to switch apps--but it does mean the operating system will respond to Expose requests.
