### ISSUE TITLE
Linux install instructions for Ubuntu inaccurate?

### ISSUE THREAD

**Issue by anuyts** [Aleph-One-Marathon/alephone#171]
I was following the [Linux Install Instructions](https://github.com/Aleph-One-Marathon/alephone/wiki/Linux-Install-Instructions) in order to install Aleph One on Ubuntu. However, `./configure` gave me several errors, which I have been able to resolve by additionally installing:
* `libsdl1.2-dev`
* `libsdl-ttf2.0-dev`
* `libsdl-net1.2-dev`

**Comment by anuyts** [comment]
Subsequently, `make` fails:
```
SDL_ffmpeg.c:2262:44: error: ‘PIX_FMT_RGB24’ undeclared (first use in this function); did you mean ‘PIX_FMT_RGB32’?
                                            PIX_FMT_RGB24 ),
                                            ^~~~~~~~~~~~~
                                            PIX_FMT_RGB32
SDL_ffmpeg.c:2266:32: warning: ‘codec’ is deprecated [-Wdeprecated-declarations]
                                file->videoStream->_ffmpeg->codec->height,
                                ^~~~
In file included from SDL_ffmpeg.c:44:0:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:893:21: note: declared here
     AVCodecContext *codec;
                     ^~~~~
Makefile:379: recipe for target 'SDL_ffmpeg.o' failed
make[3]: *** [SDL_ffmpeg.o] Error 1
make[3]: Leaving directory '/media/Common HD/Spellekes/Marathon/AlephOneUbuntu/AlephOne-20150620/Source_Files/FFmpeg'
Makefile:559: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/media/Common HD/Spellekes/Marathon/AlephOneUbuntu/AlephOne-20150620/Source_Files'
Makefile:524: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/media/Common HD/Spellekes/Marathon/AlephOneUbuntu/AlephOne-20150620'
Makefile:419: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ccallahan** [comment]
What version of Ubuntu is this? I'm part of the [Marathon Speedrun Developers](https://devel.marathonruns.net/), an unaffiliated project. We have unofficial nightly's we build on 18.04, and they have been succeeding for us. If this is a newer version of Ubuntu, I'd be very interested to investigate this.

**Comment by anuyts** [comment]
No, I'm also on 18.04 LTS.

**Comment by ccallahan** [comment]
Huh, and you're pulling the head of the repository, right?

**Comment by anuyts** [comment]
I used
```
curl -o AlephOne-stable.tar.bz2 -L https://alephone.lhowon.org/download/source.php
tar xjvf AlephOne-stable.tar.bz2
```

**Comment by jamos05** [comment]
I'm on Ubuntu 18.04 and I got the same error that you did. However, that link is for a very old build of the game from back in 2015. The ffmpeg libraries have changed a lot since then so I'm not surprised that such an old code base fails to build.

Instead, you should just clone the git repository, which has the latest and greatest code and works with current libraries:

```
git clone https://github.com/Aleph-One-Marathon/alephone.git
cd alephone
./autogen.sh
make
make install
```

Also note that the new code base has new dependencies like SDL2 that you'll have to install beforehand.

**Comment by mkrupczak3** [comment]
This documentation really should get updated. 

I'm on Ubuntu 18.04 LTS many moons later, simmiliar issue. 

Would it kill anybody to just release some binaries or Debian installs or whatever?

**Comment by mkrupczak3** [comment]
Better yet, it would be cool if this was available on the Ubuntu software store!

**Comment by mkrupczak3** [comment]
I might check out if this game would be worth porting over to Android

@emileb, interested in another opentouch game?

**Comment by mkrupczak3** [comment]
I was somehow able to build on Ubuntu 18.04 LTS, I don't remember what I did but I remember it being a HUGE pain and I had to fix some weird errors.

I would recommend keeping this open until documentation is updated @treellama @baconicsyncergy

**Comment by treellama** [comment]
The documentation is up to date for the latest release version
