### ISSUE TITLE
Button Audio loops in menus/netgame lobby after playing/hosting a match. 

### ISSUE THREAD

**Issue by AnonFriction** [Aleph-One-Marathon/alephone#173]
**__With 16 bit Audio__** 
After selecting "OK" on the Post Game Carnage Report the audio from selecting the button will loop in menus/netgame lobby.  
**With 8 bit Audio**
After selecting "OK" on the Post Game Carnage Report the user will have no audio in the menus/netgame lobby

Notes:
-Going into audio settings, changing a setting and selecting "Accept" appears to stop this

Version: 1.3b3
Game: Marathon Infinity (I have not checked others)
OS: Windows 10 Pro
OS Build: 18362.356

![sound_settings](https://user-images.githubusercontent.com/36592069/66145127-03655e80-e5bf-11e9-8a97-6cb355c21b61.png)

Let me know if there's any other info I can provide to help!

**Comment by treellama** [comment]
Hopefully these two changes are enough to fix it!
