### ISSUE TITLE
I could not start rubicon x

### ISSUE THREAD

**Issue by kotenok2000** [Aleph-One-Marathon/alephone#175]
When i try to start rubicon x i get Please be sure the files 'Map', 'Shapes', 'Images' and 'Sounds' are correctly installed and try again. .
Steps to reproduce:
1.Download rubicon from http://files5.bungie.org/marathon/marathonRubiconX.zip.
2Download Aleph One from https://github.com/Aleph-One-Marathon/alephone/releases/download/release-20190331/AlephOne-20190331-Win.zip.
3.Unzip to desktop Rubicon X ƒ folder from marathonRubiconX.zip.
4.unzip AlephOne-20190331 folder contents to Rubicon X ƒ.
double click alephone.exe

**Comment by richardpl** [comment]
You need to give argument to alephone.exe

**Comment by kotenok2000** [comment]
When i try to load rubicon with a shared aleph one executable i get an error, but when i rename folder from "Rubicon X ƒ" to "Rubicon X" the game starts. please fix it.
"C:\Users\frolo\Desktop\aleph one\AlephOne.exe" "C:\Users\frolo\Desktop\aleph one\Rubicon X ƒ"
![Снимок экрана (1)](https://user-images.githubusercontent.com/8822292/73526375-2810fc00-4422-11ea-9c2a-bad0d3a14780.png)

**Comment by LidMop** [comment]
Aleph One on Windows has broken Unicode path handling. Working on a fix.

**Comment by treellama** [comment]
@LidMop to get you up to speed: SDL 2 uses UTF-8 for paths, but the mingw POSIX layer does not. In previous releases we worked around this by patching SDL itself in our mxe cross-build environment to revert the "fix" to make SDL 1.2 use UTF-8. One solution would be to rewrite the patch for SDL 2.

Another solution is to write a separate implementation of FileHandler that uses the Windows API, and convert the UCS-2 to UTF-8 for SDL.

An even solution might be to use boost::filesystem, now that we depend on it. I think it standardizes on UTF-8 but you'd need to check into it. Good luck.

**Comment by LidMop** [comment]
I've uploaded a somewhat-tested patch branch [here](https://github.com/LidMop/alephone/tree/unicode). It should be a complete fix for all Unicode incompatibilities besides glyph-rendering and text-field input in Aleph One on Windows (even Lua script functions are covered).

Boost.Filesystem, sadly, does not standardize on UTF-8. `boost::path` is just a wrapper around `std::wstring` on Windows and `std::string` on all other platforms. Feeding it a `char` string involves an encoding-sensitive conversion on Windows, which (by default) assumes the `char` string is ANSI.

**Comment by treellama** [comment]
This is excellent, thanks. I can review it, but I won't catch weird corner case behavior, so the best bet is to issue a pull request, get it in the next beta, and let the beta testers try it.
