### ISSUE TITLE
No terminal pictures in ra'thor scenario on windows.

### ISSUE THREAD

**Issue by kotenok2000** [Aleph-One-Marathon/alephone#176]
Download link: http://simplici7y.com/items/marathon-ra-thor
I installed scenario into marathon evil folder.
![Снимок экрана (7)](https://user-images.githubusercontent.com/8822292/73630239-947c3d00-4666-11ea-92d5-9229776389a4.png)

**Comment by kotenok2000** [comment]
![Снимок экрана (8)](https://user-images.githubusercontent.com/8822292/73630524-63503c80-4667-11ea-810d-ab9e98fd9eef.png)

**Comment by treellama** [comment]
It looks like you've downloaded a file using the old style of Mac resource forks, which don't work in Windows. The easiest way to fix is to have the author re-merge it using Atque, which will use a more cross-platform format that survives being zipped.
