### ISSUE TITLE
THE GAME WONT OPEN 

### ISSUE THREAD

**Issue by h2ojonsoncs** [Aleph-One-Marathon/alephone#177]
whenever i try to play marathon 1 it wont start up so can you pls fix this pls

**Comment by ravenshining** [comment]
Without any information we can't help you, but I'm guessing you're looking for tech support rather than filing a bug, and for that, you'll have better luck on the Discord https://discord.gg/c7rEVgY or on the Pfhorums http://pfhorums.com .
