### ISSUE TITLE
Aleph One rendering stack is having a bit of rough time on Win10 2004.

### ISSUE THREAD

**Issue by ccallahan** [Aleph-One-Marathon/alephone#179]
I was playing master on Win10 build 2004, and during M1 when I got to No Artificial Colors the rendering stack kinda had a stroke. I have zero idea what caused it.

![image](https://user-images.githubusercontent.com/263269/77837912-bfea4800-713c-11ea-912d-03812b15b9e4.png)

**Comment by Kolfering** [comment]
Most certainly fixed by 86d47b2acce7dfc5774fce511070ab9e8ff0e2e5
