### ISSUE TITLE
Game lobby UI sometimes does not accept chat input

### ISSUE THREAD

**Issue by wrkncacnter7** [Aleph-One-Marathon/alephone#180]
I've experienced this with the latest windows beta, as well as latest master on linux.  After clicking "Find Internet Game", I'm unable to type messages.  The UI does not allow the chat box to focus or something.  If I leave and re-join, it starts working.  Not sure if this happens every time, but it happens very often.

**Comment by ravenshining** [comment]
I've had this happening for quite some time.  I have to hit tab a couple times before I can type, as if it's focused on a UI element that doesn't accept text.  Sometimes that doesn't work, but if I switch in and out of fullscreen it starts working.

**Comment by wrkncacnter7** [comment]
I would also add to this that scrolling the chat also doesn't work sometimes. I assume it's a similar issue with not correctly grabbing focus.
