### ISSUE TITLE
Media textures on walls now always employ liquid transparency even where they were previously solid

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#183]
This is probably easier to explain using pictures rather than text, so here is a screenshot of “Where Giants Have Fallen” from _Eternal_ using the shader renderer in 1.3:

<img src="https://user-images.githubusercontent.com/5233345/79731137-b15c0000-82a6-11ea-983f-89070bd488e9.png"/>

Here it is in 1.2.1 using the shader (the intended appearance):

<img width="986" alt="Screen Shot 2020-05-01 at 16 13 58" src="https://user-images.githubusercontent.com/8217916/80838334-cef26900-8bc6-11ea-9985-9a6ad411f52e.png"/>

I don’t know if the change is intentional, but I must say I don’t care for it, and it’s certainly a major change from the way media textures behaved in every previous version of the game. I’m told that it’s possible to work around this by adding some narrow new polygons behind the media textures, but I haven’t messed around with that yet because I’m not sure this change is going to be permanent. This is probably going to mess with the trilogy levels as well; maybe I’ll add some screenshots when I’ve gotten around to finding some examples.

**Comment by treellama** [comment]
Are those transparent lines? I would expect the textures to be transparent. If you want them to be solid, can't you set that in MML?

**Comment by aaronfreed** [comment]
The lines are transparent, but they're not used on the "transparent" part of each side (if I'm explaining this coherently), and the media textures applied there did appear solid in previous versions of Aleph One. It would probably be possible to remove the transparency with MML, but then the liquid transparency we've specified wouldn't work when it's actually supposed to be transparent... would it? I suppose we could also add alternate versions of each liquid texture that didn't have transparency, but knowing Aleph One's issues with memory management, I'd rather not - Eternal's texture sets are already bloated enough already.

**Comment by treellama** [comment]
If they're transparent lines, then only the transparent side should be textured, not the primary or secondary?

**Comment by aaronfreed** [comment]
Oh, I see what you mean. I thought you were asking whether the side was marked "transparent" in Weland. In that case no, those aren't transparent sides. That's either the primary or the secondary - I'm not sure which.

This is affecting Infinity as well, BTW - here's a shot from Vasara of Thing What Kicks:

![thing what kicks texture thing](https://user-images.githubusercontent.com/8217916/80840712-dcf6b880-8bcb-11ea-9e87-4d5d54ea8e00.png)

In this case, it's definitely the secondary texture being affected.

**Comment by treellama** [comment]
I was going to say, transparent media has been a thing for a long time. It looks like in this case it's the solid (secondary) part of the side that is being marked transparent.

**Comment by aaronfreed** [comment]
Yeah, wasn’t sure whether the engine would make the lower half of the polygon side "secondary" or "primary" if there was nothing on the upper half of it. 

Also, a possibly related issue: this is how the _actual_ transparent side on TWK is showing up in 1.3b3 LAA:

![thing what kicks transparent texture thing](https://user-images.githubusercontent.com/8217916/80841035-9b1a4200-8bcc-11ea-9e3f-54bc1fb5dddb.png)

And from the other side, it's just solid:

![thing what kicks transparent texture thing 2](https://user-images.githubusercontent.com/8217916/80841174-e0d70a80-8bcc-11ea-9c51-c64f11476abe.png)

I... don't think it showed up like that in 1.2.1. I will have to load it to be sure.

**Comment by ravenshining** [comment]
Personally I'm very pleased with the transparency effect, and would be sad to see it go.  Granted I am extremely used to seeing it as I can't compile 1.2.

**Comment by aaronfreed** [comment]
I hate it. I'd be fine seeing it made an optional effect that can be toggled with a new MML command, but I'd much prefer it be restored to its 1.2 behaviour by default. I'm already at the map index limit with "Stranger Fruit", and having to add a bunch of tiny polygons to make waterfalls not look ridiculous would probably crash the map.

**Comment by ravenshining** [comment]
It's not intuitive for a transparent texture to situationally not be transparent, either.  And, as much as it'd be nice to have more MML options, I'm not hopeful that will happen.

A simpler workaround if you want your transparent texture to be opaque would be to have a second, non-transparent version in the collection.

**Comment by aaronfreed** [comment]
That’s an absurd, completely unacceptable ‘solution’. The current stable release of Aleph One loads each texture into memory every time it’s called, so you’re essentially asking scenario developers to multiply the amount of memory taken up by each semitransparent texture by 1.75 (there won’t be an alpha channel for the second). Unless the devs implement memory pointers for textures (which, to be fair, I’d like to see happen), that probably crash _Eternal_ crashing on the current stable Windows, because Eternal 1.2.1 _already_  has all five media textures in each collection just to keep maps that use multiple media textures from crashing. And it still won’t solve the problem of Aleph One 1.2.1’s memory management, which the vast majority of people who play the game are going to be using.

Plus, your proposed solution won’t even work for maps that use the vanilla games (which is basically every net map that anyone still plays, for starters). You’d essentially be asking Ryoko, Windbreaker, and every other map designer to make new versions of their maps purely to accommodate your whims.

It’s also not at all intuitive for _solid_ walls to behave as anything other than, well, solid walls. The current 1.3 behaviour results in the underside of the map being visible, which is a completely unrealistic effect. I understand that you like that effect for whatever reason, but it detracts from countless maps that were designed for 1.2.x and have played fine for decades.

The only solution that looks acceptable to me is to introduce a new MML option that 1.2.1 ignores.

**Comment by ravenshining** [comment]
I doubt the vast majority of people are still using 1.2.1.  Seems to me like most of the community regards it as outdated and just uses 1.3, and I've never heard anyone complain about this until now.

If you can put aside your hatred of me for a second - think about what happens when you place a transparent texture on a wall, like a grating - you see into the Void, don't you?  What else would you expect to see?  I believe Rubicon uses this effect deliberately. Why should a *partially* transparent texture behave any differently - it's partially transparent, it partially covers the void.

It seems to me like you're the one who would be asking people to make new maps because you don't like the waterfall effect, for equal reason you seem to think the opposite.  Thus, it boils down to a trivial matter of taste, really.  And in that case, perhaps having a graphics option, like "semitransparent textures on walls appear opaque instead of semitransparent" would satisfy people of both persuasions without anyone having to make new maps for either behaviour.

**Comment by aaronfreed** [comment]
This seems to apply regardless of whether a map is using OpenGL textures or not. This is from one of Ryoko's maps for his WIP Metroidvania scenario using Phoenix textures, which don't have any OpenGL replacements:

![aqueduct waterfall](https://user-images.githubusercontent.com/8217916/80925405-77d2cc80-8d5d-11ea-9435-e4fff9ad9044.png)

You can see the lights behind the waterfall, which I presume is not desired behaviour.

---

@raven: The vast majority of people who are active in this community might be using 1.2.1 (I doubt anyone has run a survey), but that's because they are active in the community. The vast majority of people who play the game aren't active in the community, and they almost certainly haven't seen the tiny link at the top right of the Aleph One page to download 1.3b3. Almost everyone who's had trouble running _Eternal_ was running 1.2.1, and as far as I'm aware, not one of them even _saw_ the link for 1.3.

My feelings on this have nothing to do with you. I simply can't stand waterfalls looking like garbage, which is why I asked to have the effect reverted in the first place! I disliked the effect before I knew you were _this_ attached to it that you'd post this many comments arguing with me about it, and I continue to dislike it; your feelings about it don't enter into it. (You haven't actually explained under what circumstances you think this effect looks good, either.)

Semi-transparency doesn't exist in the original engine, so your comparison doesn't make much sense. In the original engine, transparency is a binary state: a pixel is either transparent or it isn't. If you have a completely transparent texture on a solid wall in the original game, you get a hall of mirrors glitch for the transparent parts, yes. I am not asking to have the hall of mirrors effect changed. If anything, it is applied inconsistently, and perhaps _that_ should be fixed: on a Mac, you will actually see black on a texture with transparency applied to a solid wall; whereas on Windows, you will still see the hall of mirrors effect.

But the media textures that are currently semi-transparent were _not_ semi-transparent in the original levels. They were _completely solid_. You are essentially asking the developers to overwrite twenty-four years of engine behaviour so you don't have to remake your levels. The vast majority of maps made for this engine were made before 1.3 was in widespread usage – almost certainly more than 99% of them. Even if you’re only counting maps people still play, the vast majority of net maps people still play were made no later than 2016 (a few stragglers from 2017 or 2018 creep in there, but about 98% are 2016 or earlier), and I don’t think people made maps with 1.3b1 behaviour in mind; and of the major total conversions, only _Eternal_ and _Yuge_ have been released or updated since 1.3b2 came out (and the original _Eternal_ maps were all designed well before 1.3 was even a twinkle in anyone’s eye). So you are asking _way_ more people to make new maps by asking to have the 1.3 behaviour made default.

I might find the preferences setting to be an acceptable solution _if_:

1. the MML setting isn't workable;
2. developers can specify one or the other as the default using a new MML command; and 
3. the 1.2 behaviour is the standard setting when the developers don't specify a preference.

Then I suppose there'd be "map default", "always solid", and "always hall of mirrors" options. However, I don't know how likely the Aleph One devs would be to implement it, because it would require a lot of text to explain, and most people won’t care. I would find it more palatable than forcing the 1.3 setting, at any rate.

**Comment by ravenshining** [comment]
> you were this attached to it that you'd post this many comments arguing with me about it,

Hey, you're the one posting walls of text, and post quantity is a two-way street.

> Semi-transparency doesn't exist in the original engine, so your comparison doesn't make much sense.

Yep, we improved on things by adding semitransparency and making it default for things like liquid surfaces.  None of the original maps were made with that ability in mind, and sometimes that exposes some ugly geometry - and we can turn it off if we want.  Same deal here.  You disagree that semitransparent walls are an improvement, so, let there be an option, that you turn off and I turn on.

Relegating it to MML wouldn't be a great solution, because then you'd have to remake old maps if you wanted whichever behaviour isn't default.  A preference setting eliminates that problem. 

Have you not seen that scenarios often come with default preference files?  If you don't want to see it in Chronicles, all you need do is set the falg in Chronicles' default preferences.

Scanning sounds clumsy and more difficult to code - why not just be able to turn it on and off per the user's desire?

**Comment by aaronfreed** [comment]
I’m through arguing with you about this. It’s accomplishing nothing except cluttering up the report – Treellama and Hopper will handle the problem how they see fit; it’s not your decision.

This was the last straw; you are now blocked here as well. Do not contact me again.

**Comment by treellama** [comment]
Hiding most of the comments and locking comments.

I believe the void should not be visible through semi-transparent primary/secondary textures; only the transparent part of the side should be transparent. Grates textures are a legacy undefined case and it's OK to display the void (or not). Any further discussion can occur on a pull request or commit.
