### ISSUE TITLE
1.3b3 media showing as semitransparent on random sides when transparency disabled

### ISSUE THREAD

**Issue by Captain-Fwiffo** [Aleph-One-Marathon/alephone#186]
![ExCathedra_0000](https://user-images.githubusercontent.com/55163469/81024589-75de3b80-8e39-11ea-9b23-f795c4d841e0.png)
![ExCathedra_0001](https://user-images.githubusercontent.com/55163469/81024605-7e367680-8e39-11ea-94a2-d6c582347465.png)
![WereEverywhere_0002](https://user-images.githubusercontent.com/55163469/81024612-82fb2a80-8e39-11ea-93d8-cf2fc28364a0.png)

Odd bug I found while playing through wrkncacnter's excellent loch translation of M2. Only a few polygons seem to do this. Might be in other scenarios, haven't tested yet. Levels are Ex Cathedra and We're Everywhere. Liquid transparency is off.

I'm using Windows 10, version 1.3b3 of Aleph One. Renderer is OpenGL. Video card is GTX 650. I've screenshotted and attached my graphics settings.

![Screenshot_0000](https://user-images.githubusercontent.com/55163469/81025241-a32be900-8e3b-11ea-95a8-f0d96712b04c.png)

![Screenshot_0001](https://user-images.githubusercontent.com/55163469/81025253-ad4de780-8e3b-11ea-87ac-376313416b61.png)

I should add it's present in the vanilla map as well, while not using the loch translation.

**Comment by Captain-Fwiffo** [comment]
I was encouraged to test this on older versions. The bug is not present for me on any of the renderers in 1.2.1, but it is present on the OpenGL renderer in 1.3b1. None of the "software" or "classic" renderers have the bug.

**Comment by treellama** [comment]
This is a very helpful report, thanks. Screenshots of preferences are a nice touch.

Possibly related to #183

**Comment by TrajansRow** [comment]
An easy way to spot this is in plain old Waterloo Waterpark, with all texture plugins disabled and transparent liquids turned off. In this screenshot, you are actually seeing the back side of a normally hidden elevator. Amazingly, that wall never gets shown when liquids are transparent.

<img width="1440" alt="Screen Shot 2020-05-06 at 8 46 00 AM" src="https://user-images.githubusercontent.com/25617921/81184716-5ac51600-8f76-11ea-8d26-238e8202d4b3.png">

**Comment by treellama** [comment]
It does if you die in the water :)

**Comment by TrajansRow** [comment]
Ha, I didn't try that! I can think of maybe two approaches to fixing this.

1) Always render all surfaces, regardless of whether liquids are transparent or not.

2) Disable blending when drawing an opaque media surface.

**Comment by Captain-Fwiffo** [comment]
![MyOwnPrivateThermopylae_0000](https://user-images.githubusercontent.com/55163469/81242488-e66c9000-8fd2-11ea-982a-f7af33f65253.png)

This is probably a more relevant comment for another issue, but the transparency bug also affects walls as shown in this picture. Same settings as before.

**Comment by aaronfreed** [comment]
I have a hypothesis that 1.3 is confused when a boundary between two polygons comes into contact with a media surface. I haven't narrowed this down for certain, but a lot of these screenshots certainly seem to be instances of such boundaries. Maybe the AO devs have already figured this out themselves, but I'm providing it on the off chance that it proves helpful.
