### ISSUE TITLE
'X' and Numpad '8' keys disable spacebar

### ISSUE THREAD

**Issue by WilliamDCroft** [Aleph-One-Marathon/alephone#191]
Holding the 'x' key and Numpad '8' causes the spacebar key to no longer function. 

Steps to reproduce:
1. Launch the game and go to preferences to set the following keys:
    Sidestep right: x
    Forward: Numpad 8
    Trigger: Space
    (This is part of the default keyboard layout for the Original Mac Version)
2. Load a new game
3. Once in the game, turn around to face the door nearest the player and switch to the fist weapon (to avoid activating the Phfor)
4. Hold x and Numpad 8.
5. While holding the above buttons, attempt to punch with the fist using space

Expected Result:
    Trigger should behave normally (fist weapon should punch / gun weapon should fire)

Actual Result:
    Trigger never causes weapon to perform action

Details:
This cause issues with the original Macintosh default settings where 8 is forward, x is sidestep, and space is trigger.

I tested this by changing the functionality of the spacebar to previous weapon and got the same result. While holding x and 8, I cannot get any action associated with spacebar to work.

OS: Windows 10 v1909 
CPU: Core i5-6500
Aleph One version: 1.2.1 (2015-06-20)
Scenario: Marathon 1, provided by the marathon trilogy section of the Aleph One main site.

**Comment by treellama** [comment]
This is likely an issue with the n-key rollover on your keyboard. Are you able to hold X + KP8 and type a space in notepad?

**Comment by WilliamDCroft** [comment]
I am not. So it seems it is indeed an issue with my machine and not the game.

**Comment by treellama** [comment]
They actually build keyboards with specific simultaneous keys in mind, and mostly WASD now because games have standardized on that! But, you may be able to find one that can rollover those three keys, I don't know. Regardless, closing this one out. Thanks for the report!
