### ISSUE TITLE
Certain light dependent panels/terminals do not work in vacuum levels in converted M1 scenarios

### ISSUE THREAD

**Issue by Shappie112** [Aleph-One-Marathon/alephone#192]
This is an issue that was also posted about on the Phforums by the creator of the scenario (Phoenix Falling) in which I encountered this bug.

The title pretty much says it all. No regular terminals, saves, health, air, or switches (basically anything interact-able aside from doors) will work in a converted Marathon 1 scenario vacuum level. They just make the "broken terminal" sound. It has something to do with the lighting levels of the panel.

To be clear, what I mean by converted scenario is a Marathon 1 scenario installed on a fresh copy of Marathon within an emulated Mac (OS 9, SheepShaver) and then converted to Windows compatible files via HFVExplorer and renaming the files/filetypes to what Aleph One understands.

The creator of the scenario, username mattschenk, found what was causing the issue and posted the following,

"I think I've figured this one out by finding a save terminal that happened to work on a vacuum level and then comparing its polygon lighting to others. Apparently M1 and M:i use different minimum light values to denote whether a switch or terminal is "active" in vacuum. In M1, it just had to be above 50%. With some quick testing, it appears they work when set to 80% or higher, but not at 60% where most were."

So far I've only encountered this in Phoenix Falling, though I haven't tried any other converted M1 scenario vacuum levels. I don't know any off the top of my head that I could quickly test this with. 

Windows 10
Geforce GTX 980 Driver 451.48
Aleph One 1.3b3 scenario Phoenix Falling
OpenGL

**Comment by treellama** [comment]
Do you have a reference for the 50% number for the original?

**Comment by Shappie112** [comment]
Just this Pfhorums post the creator of Phoenix Falling made http://pfhorums.com/viewtopic.php?t=53671

**Comment by treellama** [comment]
I was not able to get the Marathon engine to disable a terminal at any light level in a regular level. In a vacuum level, the light level must be greater than 50% for a terminal to be enabled.

Which leaves the question of why the first terminal behaves the same way.

**Comment by Shappie112** [comment]
My apologies, I meant to re-edit this. I think we came to find out that the Trojan bug I listed was not related to this at all.

I'm not totally sure why the terminals in this scenario are behaving this way. I've been in contact with the creator and he's been fixing these terminals by making the light change he mentioned. I can send you any related files, if that might help.
