### ISSUE TITLE
remove interlevel teleport delay for original Marathon

### ISSUE THREAD

**Issue by treellama** [Aleph-One-Marathon/alephone#195]
There's no interlevel teleport delay in original Marathon. See teleport_to_level in computer_interface.cpp

**Comment by tbcr** [comment]
So, as far as the testing I have done has indicated, the following commit I made at https://github.com/tbcr/alephone/commit/710ee84825e5becfeb430b37fdcf2bdbcf22b22a should fix the behavior correctly. Once Obsidian's issue is closed, I'll make a proper PR for this.

Shoutouts to aperturegrillz for input as well.

**Comment by treellama** [comment]
This is going to affect film playback for films recorded in 1.1 to 1.2, correct? So it needs a film profile entry?

**Comment by tbcr** [comment]
More than likely, I've not looked too much into the film profile information in the source code, but can during a stretch today.
