### ISSUE TITLE
Request: Marathon Map.scen file format

### ISSUE THREAD

**Issue by fergu** [Aleph-One-Marathon/alephone#196]
I'd like to look at some of the internals of a single marathon level. I.E - vertexes, heights, etc. For my purposes, I'm trying to do this with Arrival, the first M1 level.

I have been trying to dig through the source code to get a sense of how to interpret the `Map.scen` file, which I'm 99% sure is the file I want, but haven't yet found the relevant source code file to see how to interpret it (I've mainly been looking in the `Files` subdirectory of `Source_Files`, particularly the stuff related to wad files). I know I can ctrl-F in a hex-editor to find the first level name, but that hasn't given me enough info to interpret the (gibberish) that follows.

Anyone have a source file they can point me to?

**Comment by treellama** [comment]
Here's the ancient specs file on the format: http://fileball.whpress.com/content/marathon-specs

The code that loads it is in Files/game_wad.cpp. Look for `process_map_wad`. Good luck!
