### ISSUE TITLE
Aleph One handles line breaks differently than Infinity did

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#199]
The following is a picture of a terminal from the *Marathon Evil* level “Hackers” as it would have displayed running vanilla *Marathon Infinity*:

<img width="650" alt="Screen Shot 2020-07-31 at 14 55 17" src="https://user-images.githubusercontent.com/8217916/89068321-fdefb680-d33e-11ea-938b-39fb8b958a90.png">

Here’s the same terminal as Aleph One handles it:

<img width="956" alt="Screen Shot 2020-07-31 at 14 55 49" src="https://user-images.githubusercontent.com/8217916/89068342-0811b500-d33f-11ea-90eb-3f02bb1f7fbf.png">

As a result, there’s a second page (not shown here) where none previously existed.

The same issue can occur with mid-word hyphenation, although that is not demonstrated in these screenshots (maybe I’ll add some later). Our hypothesis is that the classic Mac OS allowed a number of mid-word line breaks that are not reproduced in Aleph One’s code.

This will be a pain to get working properly with film profiles, so I won’t be super surprised if this doesn’t get fixed anytime soon, but it does cause a desync in Dr Sumner’s “Hackers” film.

**Comment by treellama** [comment]
Do you have examples of mid-word hyphenation? I can't get SimpleText to break lines at hyphenation or repeated punctuation, and I can't find any documentation of the rules used for the `StyledLineBreak` function Marathon 2 calls.
