### ISSUE TITLE
more ffmpeg deprecation warnings

### ISSUE THREAD

**Issue by treellama** [Aleph-One-Marathon/alephone#202]
Lots of deprecation warnings using ffmpeg 4. Looks like SDL_ffmpeg is not updated any more, and also there is no decent documentation from ffmpeg on updating. Might be best to rewrite SDL_ffmpeg and Movie using the new ffmpeg tutorials...

**Comment by treellama** [comment]
As of ffmpeg 4.4 the video export no longer works. Just a black screen.

This is blocking an Apple Silicon release

**Comment by treellama** [comment]
Katharan was able to fix video and audio export, so we're OK with 4.4 for now.

**Comment by Kolfering** [comment]
We should be up to date with ffmpeg 4.4 now
