### ISSUE TITLE
Film profile does not save correctly in 1.3? or does not read previous film profile correctly? or something

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#217]
Films are still saving as 1.2 films, which means that any film that has a 1.3 behaviour change (e.g., platform flooding, playing multiple M1 levels, Trojan item pickup, etc.) will desync.

ETA: Apparently Toon actually recorded these with b3, not RC1. I am far too confused to remember whether that actually was *supposed* to use the 1.3 film profile, or whether it was still supposed to be using the old one. All I know is something with film profiles is wrong. Figuring out what is completely beyond me, at least at this stage of night :C

**Comment by treellama** [comment]
Fixed in 0fee7376771c67ca3a101eabc919931096168e23
