### ISSUE TITLE
Frame rate problems on Mac with precipitation Lua in 1.3.1

### ISSUE THREAD

**Issue by windbreaker777** [Aleph-One-Marathon/alephone#218]
Greetings. I'm seeing some frame rate issues with precipitation Lua that were not present in 1.2.1. Specifically, I'm seeing it on the Mac version of Aleph One, but not the Windows version. Wrk has reported no issue on Linux, either, so it seems limited to Mac.

I have an example below from a map I made in 2015, which did not have any frame rate issues in 1.2.1. When I stand in this region in 1.3.1, the frame rate drops significantly. I've fussed with my graphics settings pretty extensively, to no avail. I've included screenshots below:

1.2.1:
![1 2 1 fps](https://user-images.githubusercontent.com/70825225/92343617-70139380-f081-11ea-8335-cabd5eec1339.jpg)

1.3.1:
![1 3 1](https://user-images.githubusercontent.com/70825225/92343626-76097480-f081-11ea-85ae-86bc02f973a9.jpg)

Level: Tabula Rasa from [Infra Apogee v2.0.0](http://simplici7y.com/items/infra-apogee).

I have also experienced this issue on a newer map, with far less of a viewing distance in the area with the frame rate drop.

Mac OS 10.15.5

Not sure if this is needed, but here are the graphics settings from prefs:

```
<?xml version="1.0" encoding="utf-8"?>
<mara_prefs version="20200830">
  <graphics scmode_width="2560" scmode_height="1440" scmode_auto_resolution="true" scmode_high_dpi="true" scmode_hud="true" scmode_hud_scale="0" scmode_term_scale="2" scmode_translucent_map="false" scmode_camera_bob="true" scmode_accel="1" scmode_highres="true" scmode_fullscreen="true" scmode_bitdepth="32" scmode_gamma="2" scmode_fix_h_not_v="true" ogl_flags="2969" software_alpha_blending="0" software_sdl_driver="0" anisotropy_level="0" multisamples="0" geforce_fix="false" wait_for_vsync="true" gamma_corrected_blending="false" use_npot="false" double_corpse_limit="false" hog_the_cpu="false" movie_export_video_quality="50" movie_export_video_bitrate="0" movie_export_audio_quality="50">
    <void>
      <color red="0" green="0" blue="0"/>
    </void>
    <landscapes>
      <color index="0" red="1" green="1" blue="0.400000006"/>
      <color index="1" red="0.200000003" green="0.600000024" blue="1"/>
      <color index="2" red="0.0941176489" green="0.0941176489" blue="0.0627450943"/>
      <color index="3" red="0.0313725471" green="0.0313725471" blue="0.0627450943"/>
      <color index="4" red="0.400000006" green="0.400000006" blue="0.400000006"/>
      <color index="5" red="0" green="0" blue="0"/>
      <color index="6" red="0" green="0" blue="0"/>
      <color index="7" red="0" green="0" blue="0"/>
    </landscapes>
    <texture index="0" near_filter="1" far_filter="5" resolution="0" color_format="0" max_size="0"/>
    <texture index="1" near_filter="1" far_filter="1" resolution="0" color_format="0" max_size="0"/>
    <texture index="2" near_filter="1" far_filter="5" resolution="0" color_format="0" max_size="0"/>
    <texture index="3" near_filter="1" far_filter="1" resolution="0" color_format="0" max_size="0"/>
    <texture index="4" near_filter="1" far_filter="5" resolution="0" color_format="0" max_size="0"/>
  </graphics>
```

**Comment by treellama** [comment]
This might be related to the epic in #206

**Comment by treellama** [comment]
This is an issue in 1.2.1 with the Shader renderer in Catalina as well, so there's no regression here. Switching to the software renderer fixes it, and the issue does not appear in Linux / Windows. So I think it might be the Apple OpenGL shader pipeline.
