### ISSUE TITLE
Freeze on Waterloo Waterpark

### ISSUE THREAD

**Issue by Straeshi** [Aleph-One-Marathon/alephone#219]
When returning to the start area on Waterloo Waterpark a freeze can occur in front of the column door.

Steps:
Start Waterloo Waterpark and take the right path to the charger & chip room
Continue to the column door back to the start area
Activate door
Look down and slightly left and strafe right into the corner against the door

Looking at the map the freeze occurs just over the north east corner of the north column of the door, looking down and to the left so that the south column is on the left edge of the screen
![WW freeze](https://user-images.githubusercontent.com/11307290/92388341-7c1f5400-f15a-11ea-8ee3-d7b94bd6b5c3.jpg)

Possibly connected to #182 

On a possibly unrelated issue at the same location, running forwards and right strafing against the door while the door is opening will cause the left brown wall and door on the other side of the room to act as untextured until the column door finishes opening and the player moves forward again.

**Comment by LidMop** [comment]
My fault; this is a bug in 93f1f34 which causes `inset_vector` to be calculated from the wrong vertices sometimes, which results in the origin being nudged outside of its polygon in more cases than before. Working on a fix.

**Comment by LidMop** [comment]
The b1c5126 commit I just pushed also fixes the rendering glitch you mentioned (same cause).
