### ISSUE TITLE
Marathon scenarios do not start.

### ISSUE THREAD

**Issue by orbea** [Aleph-One-Marathon/alephone#22]
Alephone fails to start any of the official or non-official scenarios. Starting the games prints the initial output and then immediately quits, not even an error message. Below are some hopefully relevant details. I get the same result with the 20150907 release (With a few commits applied as patches to get around other issues) and the stable release no longer builds on my system due to ffmpeg-3.0.

os: Slackware64-current
alephone-745d8af_2016.02.29_master-x86_64-1_git
mesa-847f1cc_2015.12.16_master-x86_64-1_git
ffmpeg-3.0-x86_64_custom-1_SBo
xorg-server-1.18.1-x86_64-1
```
$ marathon
Aleph One Linux 2015-09-07 1.3a1
https://alephone.lhowon.org/

Original code by Bungie Software <http://www.bungie.com/>
Additional work by Loren Petrich, Chris Pruett, Rhys Hill et al.
TCP/IP networking by Woody Zenfell
Expat XML library by James Clark
SDL port by Christian Bauer <Christian.Bauer@uni-mainz.de>

This is free software with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
For details, see the file COPYING.

Built with network play enabled.

Built with Lua scripting enabled.
```
Here it quits...

/usr/games/marathon
```
#!/bin/sh

ALEPHONE_DATA="/usr/share/AlephOne/gamedata/Marathon"
export ALEPHONE_DATA

exec alephone "$@"
```

**Comment by orbea** [comment]
I was able to build the 20150620 tarball without ffmpeg which works....

**Comment by orbea** [comment]
Here is a backtrace with a break on exit, not sure its all that helpful?  Maybe its related to the recent upgrade to glibc-2.23 in Slackware-current?
```
Reading symbols from alephone...done.
(gdb) break exit
Breakpoint 1 at 0x414670
(gdb) run Marathon
Starting program: /usr/games/alephone Marathon
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/debug/libthread_db.so.1".
Aleph One Linux 2015-09-07 1.3a1
https://alephone.lhowon.org/

Original code by Bungie Software <http://www.bungie.com/>
Additional work by Loren Petrich, Chris Pruett, Rhys Hill et al.
TCP/IP networking by Woody Zenfell
Expat XML library by James Clark
SDL port by Christian Bauer <Christian.Bauer@uni-mainz.de>

This is free software with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
For details, see the file COPYING.

Built with network play enabled.

Built with Lua scripting enabled.

Breakpoint 1, 0x00007ffff24e0ff0 in exit () from /usr/lib64/debug/libc.so.6
(gdb) bt full
#0  0x00007ffff24e0ff0 in exit () from /usr/lib64/debug/libc.so.6
No symbol table info available.
#1  0x000000000041d7f4 in main ()
No symbol table info available
```

**Comment by Hopper262** [comment]
Do you get any output in Aleph One's [log file](https://github.com/Aleph-One-Marathon/alephone/wiki/File-Locations#linuxbsd-2)? If there's an unhandled exception, it looks like exit() is called without printing anything to stderr, but the log should get a message.

**Comment by orbea** [comment]
Yes actually.
```
Unhandled exception: basic_string::_S_construct null not valid (shell.cpp:384)
```

**Comment by Hopper262** [comment]
Can you see if 048af06 fixes it? SweetGale recently discovered and tracked down a crash on the same exception over in #21.

**Comment by orbea** [comment]
That did it, thanks!
I was able to get the master working and then I applied that commit as a patch to the 20150907 and it still worked.
