### ISSUE TITLE
Minor M1 activation differences

### ISSUE THREAD

**Issue by Captain-Fwiffo** [Aleph-One-Marathon/alephone#220]
These are some relatively minor differences I noticed in Marathon 1 while "vidding" them in Aleph One and then comparing my strategies to films of olde. Do with them what you will.

The first difference is on Cool Fusion. In Jim Mitchell's film a blue pfhor fighter makes its way down to an area and activates a bunch of doors there of its own accord. The only way to activate those doors as I saw it while playing was to jump down and open them all at once, which was very deadly every time. In the end I had to get creative and lure some pfhor fighters into dropping down and activating some of the doors.

Here's Jim's video, in this part you can see the room in the distance go dark because a pfhor fighter has activated some of the doors without Jim's even going into the first pit at all. Later in the video you can see it there yourself.

https://youtu.be/707bYHgN_gA?t=266

In contrast, here's a video starring me starting with sparing two fighters so that I can get at least one of them to drop into the pit successfully and open all the doors. Films of all these will be zipped and attached later.

https://youtu.be/yMsv_FayP7w?t=166

The second difference is on Eupfhoria. In the very next room after the one you start in, there are 5 doors with hunters behind them. In Aleph One, if you pass halfway through the room you step on a glue trigger and activate all 5 hunters at once, which is pretty deadly if you aren't prepared. Aaron posted a screenshot from Pfhorte of the room: 
![image](https://user-images.githubusercontent.com/55163469/92527152-2e532c00-f1ec-11ea-844d-d4cfaef91554.png)

However, in Jim Mitchell's run of that level, they do not seem to activate, no matter how much he runs around the room. No need for a timestamp, it's right at the start.

https://youtu.be/kBOH_zN4loM

In contrast, here is my film. The (probably intended) behavior of the hunters requires a different strategy, namely running around and screaming like a cheerleader.

https://youtu.be/OCx75qZ-qn0

The third difference is on Pfhoraphobia. This was a real dastardly change; one of the doors containing pfhor fighters and some enforcers *will not* open when you press the use button. The only way to activate it in Aleph One is to run down the hallway over the glue trigger and get ambushed on two sides. Aaron did some research with Pfhorte; here is an image of the area: 
![image](https://user-images.githubusercontent.com/55163469/92528771-f13c6900-f1ee-11ea-8477-8d71bf82dcf3.png)

And here are the attributes of the door:

![image](https://user-images.githubusercontent.com/55163469/92528816-09ac8380-f1ef-11ea-8038-fe12dc08f801.png)

Here is Jim Mitchell calmly approaching the door and opening it and executing all the monsters inside.

https://youtu.be/VDQCRHd9GvY?t=525

Here is a panicked me dashing down the hallway and scrambling for my life back up it, snarling expletives and firing in all directions all the while.

https://youtu.be/7v4Z4wwm00o?t=334

All of Jim Mitchell's M1 films can be found on this page. http://marathon.bungie.org/vidmaster/vidaroundworld.html
The following are my attached films of the levels mentioned. 
[toon_m1_github.zip](https://github.com/Aleph-One-Marathon/alephone/files/5191160/toon_m1_github.zip)

**Comment by treellama** [comment]
On Eupfhoria, using the original engine, any time I pass the glue trigger the hunters activate, as I would expect. So I think Aleph One is behaving the same as the original. I can't explain Jim Mitchell's film--are you able to reproduce that behavior in original Marathon somehow?

**Comment by treellama** [comment]
I'm able to open the door just fine in Pfhoraphobia. Is it possible you had some extra script or plugin running?

**Comment by Captain-Fwiffo** [comment]
Yes, I just tested it and I could open it fine too in 1.3.1. I am not sure if that was a problem with the beta, if I was just getting the wrong section, or what. You can mark that one off.

**Comment by treellama** [comment]
For Eupfhoria: you need to fire a pistol and wake the wasps just before you cross the glue trigger. That will set off the one-second inter-activation timer, nullifying the glue trigger as you cross. I just tested this in git, but it should work 1.3/1.4.

All that's left is Cool Fusion.

**Comment by treellama** [comment]
Cool Fusion has a vidmaster note for surviving the pit:

http://marathon.bungie.org/vidmaster/vidtipcool.html

Is this what Jim does? Does Aleph One behave differently?

**Comment by treellama** [comment]
The consensus is Aleph One behaves similarly enough to close this issue
