### ISSUE TITLE
Alt+tab to (and possibly from) window while film is rendering sometimes intersperses random frames from earlier in render

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#221]
It only seems to happen when the window size is the same as the screen size. If I have 1920x1080 and alt+tab to the window, it will randomly overwrite the current game frame with… I’m guessing whatever was onscreen when I alt+tabbed out. I have no idea why this occurs, but it also messes up alt+printscreen.

I’m running Windows 10, Intel Core i5-8400 CPU at 2.8 GHz. No GPU at the moment (I will probably reinstall one soon). Here are my basic graphics settings within Aleph One for the scenario that’s giving me trouble:

![image](https://user-images.githubusercontent.com/8217916/93196392-5e348f00-f718-11ea-9482-d23df52433b4.png)

General rendering options:

![image](https://user-images.githubusercontent.com/8217916/93196409-6391d980-f718-11ea-9007-697d07ce39e5.png)

Advanced rendering options:

![image](https://user-images.githubusercontent.com/8217916/93196419-68ef2400-f718-11ea-8dc9-17a050b19f89.png)

To my recollection, I have never had this occur when I have the game at some other resolution than my screen size, e.g.:

![image](https://user-images.githubusercontent.com/8217916/93196700-c2575300-f718-11ea-8968-f13251e135da.png)

Let me know whatever other info you need to fix this. It’s pretty annoying, so I’d appreciate having it fixed if possible! Thanks in advance.

**Comment by treellama** [comment]
Probably due to the audacious MainScreenSwap in shell.cpp:1470. Doesn't mean I know how to fix it though.
