### ISSUE TITLE
Terminal ends early in Trojan level Citizen Cane

### ISSUE THREAD

**Issue by jamos05** [Aleph-One-Marathon/alephone#223]
HAS brought this to my attention over Twitter. Apparently on the level "Citizen Cane", the terminal exits too early. Basically, instead of showing a bunch of spots on the level with some text alongside, it just abruptly ends.

Here is the video showing the bug: https://youtu.be/hiETIyOmphU

And here is the video of how it is supposed to be: https://youtu.be/wU-5r9v5oqQ?t=36

Steps to reproduce:
1. Run aleph one with the Trojan scenario files
2. Hold down Ctrl+Shift and click the "Begin New Game" button.
3. In the level select screen, select "5 - Citizen Cane" to skip to that level.
4. Walk forward, open the door, and read the terminal right in front of you.
5. Notice that on the third screen, rather than ending on "Now you're the one without a choice", it ends on "You're going to help me win back my freedom." And instead of the next few screens showing different locations on the map, it instead abruptly ends.

**Comment by hhas** [comment]
Can confirm the `MarathonTerminalCompiler` parser class is buggy. `#checkpoint` screens show correctly for `#information` terminals, but are silently discarded for `#unfinished`. This breaks multiple terminals in Trojan and presumably in M1 too. (I’ve hacked a fix that works for Trojan but it really needs fixed in AO.)

**Comment by treellama** [comment]
All of the #unfinished groups in M1 behave like #information, so that's why the parser processes them that way. Are you saying Marathon 1 could process nested groups? I can investigate

**Comment by hhas** [comment]
Directives have two levels. Top-level directives—`#logon`, `#information`, `#unfinished`, `#failure`, `#success`, `#briefing N`—delimit sections. `#logon` precedes the one-line text message that appears on logon/logoff screens. The others precede arbitrary-length text that is paged automatically till the next top-level directive or end of terminal resource is reached. 

(There are some rules regarding the order in which the end of one section leads to the start of another, but I don’t think that’s relevant here.)

Any number of `#checkpoint N` sub-directives can appears within `#information` and `#unfinished` (and possibly other) sections, clearing the screen and displaying half-and-half map (centered on goal N) and text. Dunno about paging behavior for lengthy checkpoint texts.

[termedit-manual.1.txt](https://github.com/Aleph-One-Marathon/alephone/files/6031443/termedit-manual.1.txt)

**Comment by treellama** [comment]
Thanks. So much of this information is lost to time. Hopefully I can find a way to translate it so that the M2 terminal processor in Aleph One displays it correctly.

**Comment by treellama** [comment]
Practically speaking, I guess you could have checkpoints in a success, failure, or briefing message, but I don't know why you'd ever want to. Neither Trojan nor Marathon does that. Are you aware of any scenarios that do?

**Comment by hhas** [comment]
It would be unlikely: `#success`, `#failure`, and `#briefing` directives are only shown on completion of a level, by which time it’s a bit late to be offering the player directions to objectives. It wouldn’t be an issue if the parser was conventionally constructed (e.g. hand-written recursive descent is trivial), but unless there are also M2/MI issues it isn’t worth rewriting now. The pragmatic solution is to do the least bodging necessary to treat `#unfinished` sections the same as `#information` and quietly leave the rest alone, which is what I did for Trojan. My quick-n-dirty hack is attached for reference.

[computer_interface.cpp.zip](https://github.com/Aleph-One-Marathon/alephone/files/6178499/computer_interface.cpp.zip)

**Comment by treellama** [comment]
I don't think you need recursive descent, as the only nesting is checkpoints inside the so-called top level sections.

M2 and Infinity are pre-compiled, and the rules for sections are much different, so those games are unaffected by these changes. #checkpoint didn't even work correctly in Marathon 2 / Infinity so it was never used by scenarios!

**Comment by treellama** [comment]
Interestingly enough, I've got these terminals working in Aleph One now, but another discrepancy noted in the original bug remains: the original Marathon engine appears to miscount lines when it pages, completely leaving out "You're going to help me win back my freedom." on my PowerBook.

**Comment by hhas** [comment]
Can’t say I’ve noticed that bug, but I have edited Trojan’s terminal texts so the flow’s different now anyway.
