### ISSUE TITLE
Regression: Splash screen with marathon-red broken

### ISSUE THREAD

**Issue by orbea** [Aleph-One-Marathon/alephone#226]
OS: `Slackware64-current`
alephone: https://github.com/Aleph-One-Marathon/alephone/commit/96a44b39c35eae192a34c3d000817f877ba0d01c
marathon-red: http://files3.bungie.org/trilogy/MarathonRED.zip

When starting a new game with marathon-red the splash screen displays only as a small white square instead of the expected image.

I bisected this.
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
b3e450f2e58ca26c389c6a7f716a2c0d3573c66e
da8e9dc218a67b57a0f4e763b3cceacae48f6f9f
957052249dd1f79047f236f53439dedc083bc5f3
We cannot bisect more!
```
b3e450f2e58ca26c389c6a7f716a2c0d3573c66e
da8e9dc218a67b57a0f4e763b3cceacae48f6f9f
957052249dd1f79047f236f53439dedc083bc5f3

So it probably happened in PR https://github.com/Aleph-One-Marathon/alephone/pull/208.

**Comment by orbea** [comment]
@Kolfering Any ideas? Maybe the class w_pict  is actually used?

**Comment by orbea** [comment]
After manually testing the bisect results I am pretty sure its commit https://github.com/Aleph-One-Marathon/alephone/commit/da8e9dc218a67b57a0f4e763b3cceacae48f6f9f.

**Comment by Kolfering** [comment]
I was able to identify where the problem was and I submited a PR to fix it.
Thanks for you work and your help !

**Comment by orbea** [comment]
test comment
