### ISSUE TITLE
netgame crash in TRON, but only from single player's perspective

### ISSUE THREAD

**Issue by Captain-Fwiffo** [Aleph-One-Marathon/alephone#228]
Hello scientists of Github,

I was playing a KOTH netgame hosted by windbreaker starring EDDIE DINGLE and also Edom when all of a sudden my game crashed! Thankfully windbreaker saved the film for me. To my great pleasure I found the crash was reproducible, but only from my own perspective (username Tooncinator in-game), as far as I can tell. The crash happens with 2:16 remaining on the game clock. You can speed up the game using ] to get to this point, but if you keep it sped up the crash will fail to occur. I tested this on another computer as well, since my mother so helpfully let me borrow hers for a few minutes.

On my computer, all settings were default for 1.3.1 except for the HUD being "normal" sized, all plugins being disabled, the mouse sensitivity being lowered, and certain keybindings were changed. On my mother's computer all settings were completely default. Both computers were running Windows 10. Hardware differences exist but I will not note them unless asked to.

Recording is listed here: https://metaserver.lhowon.org/game/windbreaker/2020-10-26/3
Map pack is listed here: http://simplici7y.com/items/imperium

**Comment by Kolfering** [comment]
This is the same bug as #219 which has already been fixed by b1c51268 on master
