### ISSUE TITLE
Linux Install Instructions do not work

### ISSUE THREAD

**Issue by hhas** [Aleph-One-Marathon/alephone#235]
Running `./configure` fails on a clean Ubuntu 20.04.1 LTS standard installation running in VirtualBox VM:

```
test@test-VirtualBox:~/Downloads/AlephOne-20200904$ ./configure
...
checking how to run the C++ preprocessor... /lib/cpp
configure: error: in `/home/test/Downloads/AlephOne-20200904':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
```

[shell.txt](https://github.com/Aleph-One-Marathon/alephone/files/5758839/shell.txt)
[config.log](https://github.com/Aleph-One-Marathon/alephone/files/5758838/config.log)

**Comment by treellama** [comment]
Configure isn't going to work on a clean installation. You need to have a development setup installed.
