### ISSUE TITLE
Weird rendering bug in OpenGL Shader on La Cosa Nostra

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#241]
Possibly in other maps as well. There's one particular area where the shader absolutely flips out. I took a few screenshots:

![2021-02-07 La Cosa Nostra](https://user-images.githubusercontent.com/8217916/107178143-8bbcf600-69a1-11eb-8564-4db7b40ee7e1.png)

![2021-02-07 La Cosa Nostra #2](https://user-images.githubusercontent.com/8217916/107178145-8c558c80-69a1-11eb-9b18-15b049d2d21d.png)

![2021-02-07 La Cosa Nostra #3](https://user-images.githubusercontent.com/8217916/107178146-8cee2300-69a1-11eb-9c21-8bb702544d8f.png)

![2021-02-07 La cosa nostra #4](https://user-images.githubusercontent.com/8217916/107178147-8cee2300-69a1-11eb-814d-20ef36279e87.png)

It usually only seems to happen for a frame at a time, but if I stopped at the right part of the map while looking at the correct angle, it might last for more than a frame. I was only able to get this to happen with enemies on, but I didn't try too hard in Vasara. It happens in both 1.3.1 and 1.4pre1; I have yet to test any other versions. I have a bunch of plugins on, but RyokoTK in the Discord was saying he was getting the same thing without any of the plugins. And here's a film:

[2021-02-07 la cosa nostra.zip](https://github.com/Aleph-One-Marathon/alephone/files/5941394/2021-02-07.la.cosa.nostra.zip)

And a YouTube video:

https://youtu.be/DtfdleoeZdQ

This probably happens in some other maps as well, but this is the first one where I noticed it and have been able to get it to happen consistently. If you want my opinion, the map is haunted.

**Comment by RyokoTK** [comment]
![image](https://user-images.githubusercontent.com/78819071/107412600-6cbf8080-6ad5-11eb-9a9d-37dd5abcebf1.png)

Map is Paratroopers from Kill Them All IV. Standing on that spot causes the glitch.
