### ISSUE TITLE
Respect "Interface Button Sounds" setting

### ISSUE THREAD

**Issue by Iritscen** [Aleph-One-Marathon/alephone#242]
At least on Mac, this checkbox does nothing.  Regardless of its state, sounds play every time I click a button within the additional screens off the main menu, and _no_ sounds play any time I click a button on the main menu.  Restarting the app does not cause the setting to take effect either, as one user suggested to me.

AlephOne 1.3.1, macOS 11.2

**Comment by treellama** [comment]
It affects the in-game interface (F keys)
