### ISSUE TITLE
Unbinding controls stops marathon from booting

### ISSUE THREAD

**Issue by LuxLucian** [Aleph-One-Marathon/alephone#246]
Running Arch Linux, unbinding look controls prevents Marathon 1 from starting up. Deleting the preferences file fixes this.

**Comment by treellama** [comment]
When you say unbind, you tap escape after selecting a key? It's not causing the issue for me in Ubuntu 20.04

**Comment by LuxLucian** [comment]
Yep. No idea what does it, but if someone finds this issue and figures out what not to do, at least that is helpful.

**Comment by ajshell1** [comment]
I'm running into the same issue with Void Linux, getting the same error as this and #247. 

I'm using the AlephOne-20200904 release because I'm trying to add Aleph One to the Void repositories.

I can't get it to run either Marathon or Marathon 2 (I haven't tried any others). I'd appreciate a solution.

**Comment by treellama** [comment]
What version of Boost do you have installed?

**Comment by ajshell1** [comment]
> What version of Boost do you have installed?
1.72.0

**Comment by treellama** [comment]
Are you able to get a backtrace? I’m running Ubuntu 20.04 without any issues so I suspect it’s a problem with new versions of boost

**Comment by ajshell1** [comment]
Something like this?
`Built with Lua scripting enabled.
[Detaching after fork from child process 7275]
[New Thread 0x7fffee080640 (LWP 7276)]
[New Thread 0x7fffed72b640 (LWP 7277)]
[New Thread 0x7fffecf2a640 (LWP 7278)]
[New Thread 0x7fffdffff640 (LWP 7279)]
[New Thread 0x7fffd7fff640 (LWP 7280)]
[New Thread 0x7fffdf7fe640 (LWP 7281)]
[New Thread 0x7fffdeffd640 (LWP 7282)]
[New Thread 0x7fffde7fc640 (LWP 7283)]
[New Thread 0x7fffddffb640 (LWP 7284)]
[New Thread 0x7fffdd7fa640 (LWP 7285)]
[New Thread 0x7fffdcff9640 (LWP 7286)]
[New Thread 0x7fffd77fe640 (LWP 7287)]
[New Thread 0x7fffd6ffd640 (LWP 7288)]
[New Thread 0x7fffd67fc640 (LWP 7289)]
[New Thread 0x7fffd5ffb640 (LWP 7290)]
[New Thread 0x7fffd57fa640 (LWP 7291)]
[New Thread 0x7fffd4ff9640 (LWP 7292)]
[New Thread 0x7fff9ffff640 (LWP 7293)]
[New Thread 0x7fff9f7fe640 (LWP 7294)]
[New Thread 0x7fff9effd640 (LWP 7295)]
[New Thread 0x7fff9e7fc640 (LWP 7296)]
[New Thread 0x7fff9dffb640 (LWP 7297)]
[New Thread 0x7fff9d7fa640 (LWP 7298)]
[Thread 0x7fff9d7fa640 (LWP 7298) exited]
[New Thread 0x7fff9d7fa640 (LWP 7299)]
[Thread 0x7fff9d7fa640 (LWP 7299) exited]
[New Thread 0x7fffec329640 (LWP 7300)]
while initializing preferences (preferences.cpp:2951)
  Reading older preferences of version 20200803. Preferences will be upgraded to version 20200904 when saved. (./Scripts/Default Preferences.xml) (preferences.cpp:3031)
Unhandled exception: conversion of type "PKc" to data failed (shell.cpp:363)
[Thread 0x7fff9dffb640 (LWP 7297) exited]
[Thread 0x7fff9e7fc640 (LWP 7296) exited]
[Thread 0x7fff9effd640 (LWP 7295) exited]
[Thread 0x7fff9f7fe640 (LWP 7294) exited]
[Thread 0x7fff9ffff640 (LWP 7293) exited]
[Thread 0x7fffd57fa640 (LWP 7291) exited]
[Thread 0x7fffd4ff9640 (LWP 7292) exited]
[Thread 0x7fffd5ffb640 (LWP 7290) exited]
[Thread 0x7fffd67fc640 (LWP 7289) exited]
[Thread 0x7fffd6ffd640 (LWP 7288) exited]
[Thread 0x7fffd77fe640 (LWP 7287) exited]
[Thread 0x7fffdcff9640 (LWP 7286) exited]
[Thread 0x7fffdd7fa640 (LWP 7285) exited]
[Thread 0x7fffddffb640 (LWP 7284) exited]
[Thread 0x7fffde7fc640 (LWP 7283) exited]
[Thread 0x7fffdeffd640 (LWP 7282) exited]
[Thread 0x7fffdf7fe640 (LWP 7281) exited]
[Thread 0x7fffd7fff640 (LWP 7280) exited]
[Thread 0x7fffdffff640 (LWP 7279) exited]
[Thread 0x7fffecf2a640 (LWP 7278) exited]
[Thread 0x7fffed72b640 (LWP 7277) exited]
[Thread 0x7fffee080640 (LWP 7276) exited]
[Thread 0x7fffec329640 (LWP 7300) exited]
[Inferior 1 (process 7271) exited with code 01]
(gdb)`

I can try rebuilding AlephOne with debug symbols, if I can figure out how.

**Comment by treellama** [comment]
Ah I understand, it’s because it exits before you can get a backtrace. You’d have to break on exceptions, and I don’t remember how to do that.

Debug symbols are on in the configure script by default :)

**Comment by ajshell1** [comment]
Okay then. Just let me know if there's anything else you think I can do to help you.

**Comment by treellama** [comment]
This is due to the number of joystick buttons changing in SDL 2.0.14; there are new buttons for Xbox controllers. But, it looks like this was broken before, because our parallel mappings do not include dpad buttons, but they are in my SDL 2.0.10 header file.

@Hopper262 is there a reason we don't use SDL's string functions for buttons? Afraid they will change and users' preferences will reset on upgades? I can either start using those, or make different `binding_joystick_button_name` arrays for each version of SDL that changes the number of joystick buttons. Any ideas?
