### ISSUE TITLE
Marathon 1 - Blank menus

### ISSUE THREAD

**Issue by orbea** [Aleph-One-Marathon/alephone#25]
When using `alephone-40498e7_2016.03.07_master-x86_64-1_git` I found that any menus (The preferences or the quit dialog) will be blank even if you can still click where the buttons should appear making it hard to configure.

The issue does not present itself with `release-20150907` with the following commits applied as patches.
https://github.com/Aleph-One-Marathon/alephone/commit/718fe46902106bdd15e6655817eccd8eb15948b8
https://github.com/Aleph-One-Marathon/alephone/commit/c0fc7680221af28794357e92d1db6ebd83b1adcb
https://github.com/Aleph-One-Marathon/alephone/commit/26c8edfa5511dd954a08335c15f41833e9bfc048
https://github.com/Aleph-One-Marathon/alephone/commit/048af06fbe2998d0d74f5ab4cec5f9c2f9e2b9ec

**Comment by Hopper262** [comment]
I see this same behavior on my Ubuntu machine, but not on OS X. The text for buttons is not drawn. Text is drawn for dialog titles and tabs.
