### ISSUE TITLE
Marathon 1 Resolution and HUD issues on Debian 10, Ubuntu 18.04 LTS, Ubuntu 20.04 LTS, and Mac OS X 10.9.5 Mavericks

### ISSUE THREAD

**Issue by baconicsynergy** [Aleph-One-Marathon/alephone#250]
When attempting to run Marathon 1 on Linux or Mac the resolution isn't displaying properly and cycling different resolutions only makes it worse. More importantly, the HUD is either not displaying at all or is taking up 2/3 of the screen when it does appear. I have followed the Linux compilation and installation guide to the letter. I've been trying to figure out what the heck has been wrong with my Alephone/Marathon 1 installations for around a week now. I swear I thought I was going crazy. I tried almost every stable Alephone source code release on so many different operating systems, replicating this bug on Debian 10, Ubuntu 18.04 and 20.04, KDE Neon, MX Linux, Mac OS X. The Arch Linux AUR package has been outdated for 6 years now, and trying to compile it would most certainly be doomed for failure (Yes, I tried to compile the Alephone 2015 stable source code releases and attempted to install the sdl1.2 dependencies. I received the same compilation error as this one: https://github.com/Aleph-One-Marathon/alephone/issues/171#issuecomment-522336585)

Runs perfectly on Windows 10 though. So strange! Unfortunately this is not an acceptable option for the machines I'm building.

Let me hop on the Mac and take a picture for you, so you can see what I'm talking about.

I hope this thread helps the devs and other players. My custom retro Steam Machines I'm building for my friends will just have to wait.

**Comment by treellama** [comment]
Are you using a HUD plugin? Aleph One can’t render the Marathon HUD on its own, so you have to enable one of the plugins. Classic HUD is about 2/3 screen, but take a screenshot so I know what you’re talking about.

You definitely want the latest stable release in Linux; SDL 1.2 is way too old.

**Comment by baconicsynergy** [comment]
Oh my goodness it worked. You are a hero to me. You have no idea how long I've been trying to figure this out. Linux and Mac automatically uses the classic HUD that you described - perhaps we could add this to the Linux instructions so newcomers don't get confused :) I am the happiest lad right now omg

**Comment by treellama** [comment]
Believe it or not, that’s what Marathon looked like!

**Comment by baconicsynergy** [comment]
What a world it must have been back in the day :o We certainly have come a long way!

**Comment by treellama** [comment]
FOV on that hud is 64 degrees too. I think it should stay the default but maybe we can add a note somewhere to turn the reasonable one
