### ISSUE TITLE
Interpolator crash

### ISSUE THREAD

**Issue by TrajansRow** [Aleph-One-Marathon/alephone#252]
I've seen a few identical crashes starting a new game in Marathon 2 in the interpolator due to a negative array index. If no-one else is seeing this, it could be a race condition due to the extreme amount of logging that I have enabled, which drops the frame rate to like 5fps. I cannot trigger it consistently, it just happens from time to time, and always right when a new game starts in M2. See the attached screenshot for the debugger state.

<img width="2144" alt="Screen Shot 2021-03-03 at 10 34 39 PM" src="https://user-images.githubusercontent.com/25617921/109912522-ddd7fb00-7c71-11eb-9619-1382d784ec8c.png">

**Comment by aaronfreed** [comment]
The game does crash occasionally for me as well. I assumed it was just because I had a ton of plugins enabled, but I think I’ve had it crash once when I had most stuff disabled, so ¯\(°_o)/¯

**Comment by treellama** [comment]
I have seen it happen before 1.4pre2, thought maybe bfba4f69 or 7356d1b fixed it but I guess not. I would appreciate a code review of interpolated_world.cpp if you have some free time :)

**Comment by treellama** [comment]
Interpolation never changes the side indexes of a polygon so it would be an overflow from something else.

**Comment by treellama** [comment]
Never mind the review; the polygon side count doesn't necessarily match the polygon vertex count :)

**Comment by TrajansRow** [comment]
If you have a change that might help, I should know within a couple of days whether it fixes this specific issue. Sounds like @aaronfreed might be hitting the same thing. ￼
