### ISSUE TITLE
Please add "make" to Fedora dependencies on wiki page

### ISSUE THREAD

**Issue by Iritscen** [Aleph-One-Marathon/alephone#254]
It seems that the only way to have a change made on the wiki is to file an issue, but correct me if I'm wrong.  I'd just like to ask for `make` to be added to the list of packages to be installed with `sudo dnf install` under the Fedora section.  I'm pretty sure I have a standard distro of Fedora, and it didn't come with `make` installed!  Had to install that too before A1 would build.

**Comment by treellama** [comment]
I just installed Fedora 33 and I did not need to install make
