### ISSUE TITLE
8-bit music at low volume resembles a death metal band shredding very quietly

### ISSUE THREAD

**Issue by hhas** [Aleph-One-Marathon/alephone#261]
Run Marathon.app, In Sounds Preferences select 8-bit Quality with music volume at 20-40%, and start a new game. Amusing as it initially is to play Arrival while headbanging vigorously yet very slightly, it does make it harder to aim and the novelty quickly wears off.

Workarounds for now: use 16-bit audio or set music volume high.

**Comment by treellama** [comment]
This is just what really quiet 8-bit music sounds like :)

Try opening one of the OGGs in Audacity, reducing by about 30 dB, and exporting as an 8-bit WAV.

**Comment by hhas** [comment]
It is not. At low volume there is *massive distortion* indicative of severe clipping. At 20% music volume, the tune is all but drowned in harsh noise. It is unlistenable. I did wonder if it was a problem with my machine, but jamos05 independently reported hearing it too.

The bug, I will wager, is where your mixer downsamples the 16-bit music files to 8-bit in order to mix with the 8-bit sound effects from the sounds file and play 8-bit out. If I had to guess, I’d say there’s a missing bitshift, so that the mixer’s taking the bottom 8 bits and discarding the top 8, instead of the other way around. 

--

As a more general point, the 8-vs-16-bit Quality checkbox, like number of channels and other preferences for eking speed out of low-performance hardware, is long since obsolete and not doing the app any favors. There is no reason to output 8-bit on even 15 year-old hardware. AO should accept music and effects audio at any reasonable bit-depth and sample rate, and mix it to 16-bit for playback or whatever the common standard is nowadays. 

It took me several hours to track down the problem in Trojan (having removed the Quality checkbox from the UI, it wasn’t obvious the mixer had subsequently switched from the standard 16-bit to 8-bit); however, manually setting the standard AO’s sound quality to 8-bit and playing a scenario that uses 16-bit music files produces exactly the same ear-bleeding result. 

Therefore, once the mixer bug is fixed I’d recommend stripping that checkbox entirely. (TBH the entire codebase could sorely do with a good decrufting but, small steps.)

**Comment by treellama** [comment]
Did you try what I suggested?

**Comment by hhas** [comment]
It sounds bad there too, but that doesn’t make it acceptable. 

https://superuser.com/questions/348948/why-noises-appeared-when-convert-16bit-wav-to-8-bit-wav-how-to-avoid-it

If it’s too much work to make the 8-bit mix vaguely tolerable, that’s a compelling argument for stripping out the 8-bit checkbox and support entirely. It hasn’t been needed since about 1997 and it makes your product sound terrible. There isn’t a machine that can run AO that can’t also handle ≥16-bit audio output. That would be a quick and easy fix for 1.4. (I’ve already done it for Trojan.)
