### ISSUE TITLE
Lua polygon:check_collision returns wrong location

### ISSUE THREAD

**Issue by wrkncacnter7** [Aleph-One-Marathon/alephone#262]
Using the attached lua script, slightly modified from one of Treellama's, it's supposed to print out the object returned by check_collision, as well as place an ephemera at the returned location. While it seems like it's printing the object successfully, the location of the ephemera doesn't seem to match where the player is looking. When it's printing the side you're looking at, sometimes the location is on the ground, nowhere near the side.

This was found using the latest master code on xubuntu.
[Test_Collision.zip](https://github.com/Aleph-One-Marathon/alephone/files/6203316/Test_Collision.zip)

**Comment by treellama** [comment]
You also need to set max = 32767 / 1024 in your script, because signed math is fun
