### ISSUE TITLE
update_time causing compile error

### ISSUE THREAD

**Issue by DanTheMan827** [Aleph-One-Marathon/alephone#263]
you have:
```
static constexpr auto update_time{std::chrono::milliseconds(250)};
```
But this causes compilation issues with GCC 4.9.3, I was able to fix those by changing it to:
```
static constexpr auto update_time = std::chrono::milliseconds(250);
```

**Comment by treellama** [comment]
What distro are you on that you're stuck with gcc 4.9?

If this is the only change, I think it's acceptable, but I don't think we should be stuck supporting an old compiler bug.

**Comment by DanTheMan827** [comment]
NES/SNES Classic and Genesis Mini

I’m not stuck with it exactly, but I want to avoid newer GCC when possible to avoid having to include the newer standard libraries
