### ISSUE TITLE
Switching to/from map with overlay map on appears to add a blank frame

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#265]
I only noticed this starting to happen with 1.4RC1. Not sure why. The screen blanks in https://youtu.be/ZzpYl3Z9qOc at least a couple of times near the start – e.g., at exactly 1:08.000, and then again at exactly 1:12.000. I _think_ it was just coincidence that those two occurred at exact-second intervals, as there are later map transitions (e.g., at 10:54.833 and 10:56.467) that don’t occur at exact-second intervals, but I wouldn’t wager money on it.

Note that the game also appears to add new frames whenever it blanks the screen. Counting the blank screen, there are three frames each for the timer reading 1:08.000, 1:12.000, 10:54.833, and 10:56.467. The other timer values have two frames each. Very odd.

**Comment by Kolfering** [comment]
Found the culprit: https://github.com/Aleph-One-Marathon/alephone/commit/96c14d6ec4ba75af7a5b1818a536199da7cd5d54#diff-c48189ea1bf7bfbae4b3b098c74ce408dae125bc7e4194adb02b640945ef5b1fR1360
