### ISSUE TITLE
First one or two frames in 60 fps on level transition are not using teleport distortion effect

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#266]
Probably just a quick timing fix or something. Meant to report this earlier, but it slipped my mind, sorry.

Oddly, this only is particularly awful for level transitions. If you look frame-by-frame, the same-level teleport appears to have its timing slightly off as well (it gets slightly more distorted for a couple of frames _after_ the teleportation, then starts to get less so), but not in a particularly noticeable way. The two issues probably have the same cause, though – my hypothesis is that for the same-level teleport, it is still applying the “teleport out” effect for the first frame or two after moving the player to the new polygon, but that effect won’t be active after a level transition, so the first frame or two of the new level won’t distort at all.

**Comment by Kolfering** [comment]
Might be fixed by 1e22191

**Comment by aaronfreed** [comment]
This seems to be really obvious in videos rendered inside Aleph One:

https://youtu.be/jaAyGUeXgR8?t=834

(Watching at 0.25x will make it super obvious)

It does not seem to happen in the game normally, or when replaying films:

https://www.youtube.com/watch?v=AcReh_ROf8M&start=4601

It might actually be a "rendered videos only" problem, but my guess is the game might not normally render the first few frames of gameplay, but it's probably rendering every frame in rendered videos because it's not doing those at real time.

**Comment by Kolfering** [comment]
Fixed by 44e1a42c
