### ISSUE TITLE
Liquid disappears/reappears depending on player position

### ISSUE THREAD

**Issue by Q3BFG10K** [Aleph-One-Marathon/alephone#268]
Load the Marathon 2 save and sidestep left without touching the mouse, and eventually the purple liquid disappears. Now keep sidesteping right and it'll eventually appear.

[1618237282.zip](https://github.com/Aleph-One-Marathon/alephone/files/6297578/1618237282.zip)

**Comment by Kolfering** [comment]
This is part of the original design of this map, and this is not an engine bug
