### ISSUE TITLE
Repair Switches in Trojan not responding.

### ISSUE THREAD

**Issue by Sharkie-Lino** [Aleph-One-Marathon/alephone#276]
While playing the Trojan scenario (downloaded the one currently on S7), I came across two instances where a level could not be completed because a switch (I'm assuming is a standard repair switch) required to "finish" the level would not respond at all. Neither the action key, nor weapons that can trigger switches. 

This happened on Have Gun, Will Travel, as well as Dance The Last Waltz With Me.  

(If you're wondering, the latter level I discovered because after all that and first getting stuck, really wanted to see what the rest of the terminals would say near the end, and I used the Nature's Peace plugin to get through them without having to fight anything). 

I first tried the scenario I believe on the Preview 1 version of 1.4, and then Preview 2. Per TL's suggestion, I tried them again on the 1.4 official release. Same problem. All Mac versions.

It seems according to a couple of others, they didn't have this problem and completed the scenario fine. Totally unsure why I would have this issue. Maybe could have been a bad download? *shrugs*

**Comment by Kolfering** [comment]
After testing, I can assert this is commit 398fcc65 which is the source of this bug

**Comment by Kolfering** [comment]
Discussion and more detailed information about this bug:
https://gist.github.com/Kolfering/cff8a83233b3ba92e9793910006c1ded
