### ISSUE TITLE
Wiki - Linux Install Instructions suggestion: sudo checkinstall as a cleaner, easier alternative to sudo make install

### ISSUE THREAD

**Issue by baconicsynergy** [Aleph-One-Marathon/alephone#278]
I just substituted "sudo make install" with "sudo checkinstall" and it packaged and installed the built source code in a beautiful, clean, professional manner that I can administrate with my set of apt package management tools. I think it's worth adding to the Linux installation guide

**Comment by treellama** [comment]
I think `make install` is more generic/widely applicable. Checkinstall is great if you're on an apt system, and there's also Flatpaks now.
