### ISSUE TITLE
Fonts not rendering on Linux

### ISSUE THREAD

**Issue by kookerus** [Aleph-One-Marathon/alephone#28]
I'm on Ubuntu 14.04, and certain fonts wont render. Any confirm dialog boxes, the preference menu, and save/load dialog boxes have no font rendered. The main menu, and option menus still have fonts.
![screenshot from 2016-03-16 17 19 30](https://cloud.githubusercontent.com/assets/8160403/13829075/5d892c4c-eb9b-11e5-858c-79eb31aaddbf.png)
![screenshot from 2016-03-16 17 20 06](https://cloud.githubusercontent.com/assets/8160403/13829073/5d863f50-eb9b-11e5-86ee-8f7452ab866d.png)
![screenshot from 2016-03-16 17 19 47](https://cloud.githubusercontent.com/assets/8160403/13829074/5d877d02-eb9b-11e5-9b91-e4376b9379ca.png)

**Comment by Hopper262** [comment]
What version are you running? Commit 4900928 fixed an identical issue for me in Ubuntu.

**Comment by kookerus** [comment]
I had to install the version in the repos because I couldn't get it to compile. output of `alephone --version` is `Aleph One Linux 2015-09-07 1.3a1`

I have no idea why, but cloning the repo and cherry picking your commit works perfectly. Thanks a bunch!
