### ISSUE TITLE
Aleph One always crashes upon trying to kill certain enemies 

### ISSUE THREAD

**Issue by ChloeBangBang** [Aleph-One-Marathon/alephone#282]
Assertion error every time I try to kill any of this group on enemies from [this save](https://mega.nz/file/22AWwZCA#oEXvILnP6j58CeYx5BsEheR12A-aTHcN3KflrCC-gIw) from the original Marathon level "Colony Ship For Sale, Cheap"
![image](https://user-images.githubusercontent.com/47910150/119276840-ee00d600-bbe1-11eb-8060-3efa50081dae.png)

The log file was less than helpful, but I'll include it anyway for the sake of completeness
```
-------------------- Wed May 19 23:57:41 2021



-------------------- Sat May 22 22:46:29 2021



-------------------- Sun May 23 15:52:56 2021



-------------------- Sun May 23 16:17:19 2021



-------------------- Sun May 23 16:20:48 2021
```
the console log:

```
Built with network play enabled.

Built with Lua scripting enabled.
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = short int; _Alloc = std::allocator<short int>; std::vector<_Tp, _Alloc>::reference = short int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
fish: Job 1, 'alephone-marathon' terminated by signal SIGABRT (Abort)
```
I was able to replicate this from both 1.4 and compiled master build, both built from the AUR.

system specs:
![image](https://user-images.githubusercontent.com/47910150/119277114-61efae00-bbe3-11eb-82cc-5a9738f87ffc.png)

[game configuration](https://mega.nz/file/v2AAxLiT#4imADWFyh-mdCckbQPHDU0oucTtanyJGxIpKHBSck8c)

**Comment by Kolfering** [comment]
Thanks for reporting this issue.
I am able to reproduce it. But in my case it crashes only when I try to kill one of those monsters with a grenade of the AR.
