### ISSUE TITLE
Aleph One on Windows can only render films to C:

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#288]
From my understanding this is due to some annoying aspect of Windows’ file system, but it’s really annoying, as it means I have to keep clearing space off my smallest and most commonly used drive, and to make matters worse, Windows sometimes randomly makes some 17 GB of free space just go missing. If future releases could render to other drives (e.g., my 16 TB RAID), it’d be really nice.

**Comment by treellama** [comment]
resolved in 0b4323c8
