### ISSUE TITLE
Chapter screen sounds don't work maps with the M2 win95 resource format

### ISSUE THREAD

**Issue by wrkncacnter7** [Aleph-One-Marathon/alephone#297]
Testing out the windows m2 map file on the trilogy release page (http://files3.bungie.org/trilogy/Map.sce2.zip) in alephone, I do not hear any chapter screen sounds.

Likely, it's because of the resource format used for the windows 95 map files.

**Comment by treellama** [comment]
Curiously, when I split that map with Atque, there are no sound resources present.

Also, Atque uses the M2 Win95 resource format for merges, and they work in Yuge...curious.

**Comment by treellama** [comment]
Haha, it turns out the chapter screen sounds in M2 for Win95 are stored in the sounds file, and the engine uses a hard coded lookup table to play them.

WONTFIX
