### ISSUE TITLE
Please clarify license of game data repositories

### ISSUE THREAD

**Issue by ghost** [Aleph-One-Marathon/alephone#30]
Hello,

I see that the alephone repo itself has a COPYING file, but I see no license statement for any of the game data repos. The alephone site also points out the GPL3 license of this project, but is silent about the game data files.

Please clarify Bungie's intentions about acting on its copyright on the game data, even if it is only to say that Bungie considers them abandonware or something similar.

**Comment by treellama** [comment]
Our permission for redistribution comes from the FAQ for the 2005 trilogy release: http://trilogyrelease.bungie.org/faq.html

The Infinity source code contains an INFINITY_CONTENT_LICENSE.txt that has the CC BY-NC-SA license in it.

Nobody has been able to pin Bungie down for a better license to the content. I don't think they consider it abandonware.

**Comment by wgreenhouse** [comment]
Please consider placing this license text in the repos it applies to. This will aid others in evaluating when/whether/where they can redistribute it. At the moment, without a license text, the game data repos might appear to be "all rights reserved!"

**Comment by wgreenhouse** [comment]
I thank you for the clarification. However, the choice of a license excluding commercial use will make it impossible for software distributions applying the GNU Free Software Definition (see freedoms 0, 2, and 3 at https://www.gnu.org/philosophy/free-sw.html) and/or the Debian Free Software Guidelines (see Paragraph 6, No Discrimination Against Fields of Endeavor at https://www.debian.org/social_contract). If Bungie would consider applying CC-BY-SA licensing to the game data, it would be possible for such software distributions to include Marathon games.

Thank you!

**Comment by darealshinji** [comment]
> If Bungie would consider applying CC-BY-SA licensing to the game data, it would be possible for such software distributions to include Marathon games.

That would be great. But since they "only" released their engine under the GPL and from reading the FAQ I doubt that will happen soon. But distros could still package alephone and add launch scripts that will download the game content from Github for the user at first start and maybe inform them about the game's license conditions.
