### ISSUE TITLE
Adding in support for title screen demo videos?

### ISSUE THREAD

**Issue by eisnerguy1** [Aleph-One-Marathon/alephone#300]
Is there a way to add title screen demo video support? If you leave any Marathon game at the main screen for too long, demo videos play. I'm talking about this (had to upload it to Google Drive as it was too large to update to this issue, also couldn't get the audio to record):
https://drive.google.com/file/d/1P_Bhilzm9bnaE57jjvKiLsS7rxeUdL0m/view?usp=sharing
Could this functionality be added to Aleph One? Or, is there a setting for this already?

**Comment by treellama** [comment]
This was added in 498d4038cd0da3105ef7dafdb2a5f8f4c1b92f5c

**Comment by eisnerguy1** [comment]
Is there any way to enable this feature for the original Marathon too?

**Comment by treellama** [comment]
No, Aleph One cannot play Classic Marathon films. The source code for that game was never released, and reverse engineering exact film compatibility would be a giant task.

**Comment by eisnerguy1** [comment]
Ah, dang. Makes sense. Thanks for clarifying that for me 👍🏻
