### ISSUE TITLE
Some of the font is blurry in the HUD

### ISSUE THREAD

**Issue by eisnerguy1** [Aleph-One-Marathon/alephone#301]
So, some of the font for the ammunition & weapon name is blurry in the HUD for Marathon 2 & Infinity, but completely clear in Marathon 1's HUD. I'm using [this for the original Marathon](http://simplici7y.com/items/marathon-classic-hud) so, I'm not sure if the blurriness in the radar font is a problem with that HUD plugin or Aleph One itself. That font is clear in Marathon 2 & Infinity though.
![Arrival_0000](https://user-images.githubusercontent.com/3295271/126890819-5e413d87-ae53-4ba5-8c77-ce2fee2c32f7.png)

![WaterlooWaterpark_0000](https://user-images.githubusercontent.com/3295271/126890830-e6e2cdb8-ecb3-41eb-bacc-2f1ac1b00185.png)

![NeCedeMalis_0007](https://user-images.githubusercontent.com/3295271/126890851-95e8faf2-cfad-455c-a77c-f8fd2b0dea4f.png)

**Comment by treellama** [comment]
The original HUD is rendered at 640x480 and scaled up. The classic HUD plugin for Marathon renders text post-scaling. So it would just be a matter of writing a new HUD plugin.
