### ISSUE TITLE
Building without BOOST, possible?

### ISSUE THREAD

**Issue by vanfanel** [Aleph-One-Marathon/alephone#303]
Hi there!

Since libboost is such a huge dependency, with many projects distancing from it, and after seeing some commits in that direction in Aleph-One (like this one: https://github.com/Aleph-One-Marathon/alephone/commit/d3974b93ac9211afa202f1f436e9fd24d05346b2),  I was thinking: is it somehow possible to build AlephOne without depending on BOOST?

Tanks!

**Comment by treellama** [comment]
We're not removing boost--if anything, we'll be using it more in future releases
