### ISSUE TITLE
Weapon static/fold-in teleport effects not happening with monster plugins

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#308]
Specifically, the XBLA monsters and Wrk’s monster upscales, and probably others as well. May be related to #307. Unlike that one, this one occurs even in software mode, and also unlike that one, this one does not occur when rendering films. 

ETA: Apparently some people are also having this problem without any plugins enabled, but I’m not able to reproduce that behaviour.

**Comment by treellama** [comment]
Reports are this is still happening in 1.5 with frame cap set to unlimited. I haven't seen it.
