### ISSUE TITLE
Aleph One (1.5 RC) crash when texturing untextured walls. 

### ISSUE THREAD

**Issue by Sharkie-Lino** [Aleph-One-Marathon/alephone#321]
After creating new polygons and attempting to texture the walls of them with both Visual Mode Lua, and Vasara, A1 immediately crashes back to the desktop. No issues with the floor or ceiling, or when you Pave Level first and retexture the now-textured walls.

When attempting this through Weland's Visual Mode, the same issues happen, and the error down below pops up. 

On the Mac version, with Big Sur. 

  
![image](https://user-images.githubusercontent.com/80301156/141402467-3eb96565-32f1-458d-bf17-109b62137f40.png)

**Comment by treellama** [comment]
I'm not able to reproduce this; Visual Mode.lua textures untextured polygons just fine. I tried all combinations of primary, secondary, and transparent side. Can you describe how to reproduce the problem in more detail?

**Comment by Sharkie-Lino** [comment]
Sorry it took me so long to respond to this. I'll see if I can give more detail. 

When starting a new map from scratch, I made a simple 3-polygon test map. When using Weland's visual mode, I tested both VML, and Vasara. In the completely untextured map, I place a texture on the floor or ceiling, all works well. But, when trying to texture the untextured wall, the screen turns like a bright red and immediately after, exits (I'm assuming crashed based on that error message) out of visual mode back to Weland, with the "Entering Visual Mode...." dialogue box remaining, unless you close it manually. 

With that Pave Level example I mentioned earlier, I can mention something extra. If I do Pave Level, and then create any new polygons after that, when I texture the untextured walls, it does not seem to crash out, but, sometimes it looks like it works fine, other times, the texture appears to like rapidly vibrate up and down. 

Only thing different between now and the original post is that I'm using the official release of 1.5.

**Comment by treellama** [comment]
Is there an error message in your Aleph One log? Can you upload the map that crashes when you try to texture?

**Comment by Sharkie-Lino** [comment]
Sure, here's the map. I tried creating new polygons separate from the original area (didn't save it), which didn't seem to reproduce the issue, it only seems to have happened with a freshly-made one. 

Where is the A1 Log again? Been a while. When I can, I'll try another test on a
brand new map to see if anything appears on it. 
 
[Test Map.sceA.zip](https://github.com/Aleph-One-Marathon/alephone/files/9612708/Test.Map.sceA.zip)

**Comment by treellama** [comment]
Here are the locations of the log files: https://github.com/Aleph-One-Marathon/alephone/wiki/File-Locations#log-files

I am able to texture all three untextured walls in this map just fine with Visual Mode.lua

**Comment by Sharkie-Lino** [comment]
Found the log file, but it seems nothing is appearing in it when the issue happens, aside from that original error dialogue. 

I had a feeling nothing was gonna happen with that map file, it doesn't seem to happen with a saved file. I forget if you did this already, but if you just open Weland, without opening any saved maps, and start making a level, and texture an untextured wall, does the issue happen then?  That's when it does for me. 

If it doesn't for ya, then I guess I'm at a stand-still, but I do have work-arounds as mentioned above.

**Comment by jamos05** [comment]
I can get this to repro. I'm using Aleph One latest (commit cee60a81011d345541bffe09a3a3244ac511c8e7) on Linux (Steam Deck OS). However, I couldn't get it to happen with the test scene above. Instead, I have my own textured map which is literally just one untextured triangle: [untexturedTri.sceA.zip](https://github.com/Aleph-One-Marathon/alephone/files/10246905/untexturedTri.sceA.zip)

Running it with gdb, it looks like it's dying in the fps interpolation code. Which tracks because I noticed the crash doesn't happen as long as my FPS isn't set to >30. My best guess is that the code is trying to read an uninitialized texture and segfaulting:

```
Thread 1 "alephone" received signal SIGSEGV, Segmentation fault.
0x000055555564463b in enter_interpolated_world () at interpolated_world.cpp:270
270                     current_tick_sides[i].y0 = map_sides[i].primary_texture.y0;
(gdb) bt
#0  0x000055555564463b in enter_interpolated_world() () at interpolated_world.cpp:270
#1  0x000055555561c4c3 in update_world() () at marathon2.cpp:596
#2  0x00005555557bd77d in idle_game_state(unsigned int) (time=<optimized out>) at interface.cpp:1221
#3  0x00005555555b7adc in main_event_loop () at shell.cpp:754
#4  main(int, char**) (argc=<optimized out>, argv=<optimized out>) at shell.cpp:286
```

Steps to repro:
1. Download and unzip the attached map
2. Set your A1 prefs to use >30 FPS (interpolated). Enable the Visual Mode or Vasara Plugin
3. Run: alephone -e /path/to/infinity/data /path/to/untexturedTri.sceA
4. Try to texture a wall. It should crash. Note that texturing the floors and ceiling does not crash.

**Comment by treellama** [comment]
Thanks, maybe > 30 fps is the key!

**Comment by Sharkie-Lino** [comment]
To help confirm. Just tested it again my original way a few times with it set to 30 FPS, and no problems. 

Nice finding there.
