### ISSUE TITLE
Primary texture of split polygon getting messed up when door borders split polygon

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#327]
If you have a door that extends “from ceiling” or “from both”, and it borders a split polygon that has both a primary and a secondary texture on it, then it will mess up the texture alignment of the primary texture of said split polygon. Attached is a very basic map that demonstrates the bug.

[platform bug.zip](https://github.com/Aleph-One-Marathon/alephone/files/7831264/platform.bug.zip)

This may be related to #233, which also relates to texture alignment of doors that extend “from ceiling” or “from both” getting messed up.

ETA: Video [here](https://cdn.discordapp.com/attachments/430075740889808908/939641856420110336/platform_bug.webm).

**Comment by treellama** [comment]
Possibly related to https://github.com/Aleph-One-Marathon/alephone/commit/389551ae05293cd06f8b66656e3b41dc7e7ca3b7
