### ISSUE TITLE
Couldn't initialize SDL (no available video device)

### ISSUE THREAD

**Issue by greenchile99** [Aleph-One-Marathon/alephone#335]
Hello,

 I followed all of the steps [here](https://github.com/Aleph-One-Marathon/alephone/wiki/Linux%20Install%20Instructions) for Ubuntu 20.04 LTS.  I'm getting some warnings from "make" which I have included.  I'm wondering if I compiled things in the wrong order.  

Initially, I downloaded and installed individual SDL2 packages.   I probably need to restart the install process from the beginning, but I don't know how remove then reinstall all of the packages.

Thank you

output from running "/usr/local/bin/alephone":

Couldn't initialize SDL (No available video device)

[1]+  Exit 1                  alephone MarathonInfinity-20220115-Data/

output of "./configure":

checking mad.h usability... no
checking mad.h presence... no
checking for mad.h... no
checking for sndfile... yes
checking for vorbisfile... yes
checking smpeg/smpeg.h usability... no
checking smpeg/smpeg.h presence... yes

configure: WARNING: smpeg/smpeg.h: present but cannot be compiled
configure: WARNING: smpeg/smpeg.h:     check for missing prerequisite headers?
configure: WARNING: smpeg/smpeg.h: see the Autoconf documentation
configure: WARNING: smpeg/smpeg.h:     section "Present But Cannot Be Compiled"
configure: WARNING: smpeg/smpeg.h: proceeding with the compiler's result
configure: WARNING:     ## -------------------------------------------------------------------- ##
configure: WARNING:     ## Report this to https://github.com/Aleph-One-Marathon/alephone/issues ##
configure: WARNING:     ## -------------------------------------------------------------------- ##

 
    Enabled: OpenGL rendering
    Enabled: built-in Lua scripting
    Enabled: SDL2_image support
    Enabled: FFmpeg playback and film export
  Not found: libmad MP3 playback
    Enabled: libsndfile audio decoding
    Enabled: libvorbis Ogg/Vorbis music playback
  Not found: SMPEG movie playback
    Enabled: Speex net mic playback
    Enabled: ALSA net mic transmission
    Enabled: cURL for HTTP communication
    Enabled: zziplib support
    Enabled: libpng PNG screenshot support
  Not found: miniupnpc support

warnings from output of "make":

mv -f $depbase.Tpo $depbase.Po
metaserver_messages.cpp:269:33: warning: macro "__DATE__" might prevent reproducible builds [-Wdate-time]
  269 |  write_padded_string(thePacket, __DATE__, 32);
      |                                 ^~~~~~~~
metaserver_messages.cpp:270:33: warning: macro "__TIME__" might prevent reproducible builds [-Wdate-time]
  270 |  write_padded_string(thePacket, __TIME__, 32);
      |                                 ^~~~~~~~
                          ^~~~~~~~
HUDRenderer.cpp: In member function ‘void HUD_Class::update_inventory_panel(bool)’:
HUDRenderer.cpp:426:28: warning: ‘%d’ directive writing between 1 and 10 bytes into a region of size 4 [-Wformat-overflow=]
  426 |       sprintf(kills_left, "%d", kill_limit);
      |                            ^~
HUDRenderer.cpp:426:27: note: directive argument in the range [-98303, 2147483647]
  426 |       sprintf(kills_left, "%d", kill_limit);
      |                           ^~~~
In file included from /usr/include/stdio.h:867,
                 from /usr/local/include/SDL2/SDL_stdinc.h:43,
                 from /usr/local/include/SDL2/SDL_main.h:25,
                 from /usr/local/include/SDL2/SDL.h:32,
                 from ../../Source_Files/CSeries/cseries.h:34,
                 from HUDRenderer.h:31,
                 from HUDRenderer.cpp:28:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:34: note: ‘__builtin___sprintf_chk’ output between 2 and 11 bytes into a destination of size 4
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
   
   n file included from screen.cpp:124:
screen_shared.h: In function ‘void render_screen(short int)’:
screen_shared.h:548:21: warning: ‘ ms)’ directive writing 4 bytes into a region of size between 0 and 9 [-Wformat-overflow=]
  548 |     sprintf(ms, "(%i ms)", latency);
      |                     ^~~~
In file included from /usr/include/stdio.h:867,
                 from /usr/local/include/SDL2/SDL_stdinc.h:43,
                 from /usr/local/include/SDL2/SDL_main.h:25,
                 from /usr/local/include/SDL2/SDL.h:32,
                 from ../../Source_Files/CSeries/cseries.h:34,
                 from screen.cpp:29:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:34: note: ‘__builtin___sprintf_chk’ output between 7 and 16 bytes into a destination of size 11
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());

**Comment by treellama** [comment]
If you ended up with an Aleph One executable, then you compiled it correctly. I would take "No available video device" at its word: SDL is not able to initialize video for some reason.

**Comment by greenchile99** [comment]
Should I contact the SDL2 maintainers?  I don't know how to proceed.  The executable stops and never opens.  There are warnings when I run "make".  I'm not sure if the warnings are serious enough to prevent the executable from running.

Thanks

**Comment by greenchile99** [comment]
I resolved the issue. I compiled the latest version of SDL2 from source then compiled AlephOne. It opened and ran. I can only think that I installed the wrong version of SDL2.

 
 
  On Tue, Mar 1, 2022 at 6:44 PM, Gregory ***@***.***> wrote:   


Closed #335.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
