### ISSUE TITLE
HUD broken (bug)

### ISSUE THREAD

**Issue by deqnet** [Aleph-One-Marathon/alephone#34]
I just built Alephone on 64bit Ubuntu and after sorting out the SDL2 libs I get this issue when playing 

> [string "HUD Lua"]:288: attempt to index global 'pos' (a nil value) (lua_script.cpp:1106)

No other problems

d

**Comment by darrenmason** [comment]
I recently fixed this issue on my Debian machine.  The install instructions do not include the dependency: `libsdl2-image-dev`  I think this may be (?) when alephone switched to sdl2, and the packages were split.

After installing it, run `configure` and you will see the sdl-image "optional" feature fulfilled.  Then run `make` and `make install`. The error should go away and the HUD displays normally.

**Comment by scooterx3** [comment]
I'm running Fedora 24, I wound up having to install 'SDL_image' and 'SDL_image-devel' to fix this issue. I'm no pro but I think only the latter was actually needed? I didn't do individual tests; just installed both, recompiled, and the HUD worked fine.

**Comment by Hopper262** [comment]
Based on the comments here, the [install instructions](https://github.com/Aleph-One-Marathon/alephone/wiki/Linux-Install-Instructions) now include `libsdl2-image-dev` as a dependency. Using those instructions, I cannot replicate the bug on Ubuntu with current master.
