### ISSUE TITLE
Fix Text Scaling in Software Mode for Marathon 1 Classic HUD

### ISSUE THREAD

**Issue by OpenRift412** [Aleph-One-Marathon/alephone#342]
I know this is a bit nitpicky, but I noticed that unlike in Marathon 2 and Infinity, Marathon 1's HUD text (ammo count, scoreboard, weapon list, etc.) isn't scaled to match the rest of the HUD's graphics.

Here's a comparison between 1 and 2.

Marathon 1
![G4Sunbathing_0000](https://user-images.githubusercontent.com/29780788/161444636-a041ce87-69a3-479e-84a4-0fd80eb27aea.png)

Marathon 2
![WaterlooWaterpark_0000](https://user-images.githubusercontent.com/29780788/161444694-eae9f012-4698-4e91-9a32-e7b0d5607a02.png)

Also of note, the "Are you sure you want to quit?" dialogue isn't scaled at all, regardless of which game.

**Comment by aaronfreed** [comment]
The text scales fine for me, and the “are you sure you want to quit?” message is a reasonable size. I wonder if there’s some preferences setting somewhere that causes this to differ, or whether it differs between OSes. What OS are you using?

![image](https://user-images.githubusercontent.com/8217916/177053227-fddd7348-cfd0-4d92-a709-6f096212061b.png)

![image](https://user-images.githubusercontent.com/8217916/177053285-bcb55c62-0f8c-4bae-a0f6-79236879239b.png)

**Comment by OpenRift412** [comment]
> The text scales fine for me, and the “are you sure you want to quit?” message is a reasonable size. I wonder if there’s some preferences setting somewhere that causes this to differ, or whether it differs between OSes. What OS are you using?
> 
> ![image](https://user-images.githubusercontent.com/8217916/177053227-fddd7348-cfd0-4d92-a709-6f096212061b.png)
> 
> ![image](https://user-images.githubusercontent.com/8217916/177053285-bcb55c62-0f8c-4bae-a0f6-79236879239b.png)

I'm currently running windows 11, latest version of Aleph One

Here's my config file:
[Marathon Preferences.zip](https://github.com/Aleph-One-Marathon/alephone/files/9035429/Marathon.Preferences.zip)

**Comment by aaronfreed** [comment]
Looks like it only scales correctly in OpenGL. My recommendation: don’t use software mode; it doesn’t work well, and in fact it crashes way more often. If you want OpenGL to look like software mode, disable at least near texture filtering in preferences -> graphics settings -> rendering options -> advanced. (Distant texture filtering looks less terrible.)

**Comment by OpenRift412** [comment]
> Looks like it only scales correctly in OpenGL. My recommendation: don’t use software mode; it doesn’t work well, and in fact it crashes way more often. If you want OpenGL to look like software mode, disable at least near texture filtering in preferences -> graphics -> rendering options -> advanced. (Distant texture filtering looks less terrible.)
> 
> They probably should still fix software mode for the HUD, but I doubt it’s a high priority when they’re actually trying to get an entirely new rendering engine working (what with OpenGL now being ancient).

Damn, that sucks. I always preferred that 256-color paletted look though :(

**Comment by treellama** [comment]
If you set the resolution for 640x480 full screen it should resemble the original game. Lua HUDs can't scale fonts in software mode, and there's no C HUD for original Marathon.
