### ISSUE TITLE
Suggested updates for vcpkg README, project README and wiki

### ISSUE THREAD

**Issue by Iritscen** [Aleph-One-Marathon/alephone#345]
Here are some small suggested updates to three areas of the documentation.

# vcpkg/README.md
## Mac

1. After cloning Aleph One's source code, clone vcpkg to some other directory with `git clone https://github.com/microsoft/vcpkg`.
2. `cd` into the vcpkg project's directory.
3. Run `./bootstrap-vcpkg.sh`.
4. Run `./vcpkg integrate install`.
5. Now `cd` into Aleph One's vcpkg/ directory.
6. Run either `./install-arm64-osx.sh` or `./install-x64-osx.sh` if you want to build for your machine architecture; run both if you intend to build universal binaries.
7. You can now build Aleph One using PBProjects/AlephOne.xcodeproj (see wiki's [Developer Notes](https://github.com/Aleph-One-Marathon/alephone/wiki/Developer-Notes) for details).

## Windows

1. After cloning Aleph One's source code, clone vcpkg to some other directory with `git clone https://github.com/microsoft/vcpkg`.
2. `cd` into the vcpkg project's directory.
3. Run `bootstrap-vcpkg.bat`.
4. Run `vcpkg integrate install`.
5. You can now build Aleph One using VisualStudio/AlephOne.sln (see wiki's [Developer Notes](https://github.com/Aleph-One-Marathon/alephone/wiki/Developer-Notes) for details).

# Wiki's Developer Notes (Mac section)
## Compiling on macOS
We use the package manager vcpkg to deal with the dependencies. You can find the instructions on how to set it up correctly in the readme located at [vcpkg/README.md](https://github.com/Aleph-One-Marathon/alephone/tree/master/vcpkg). **Note:** Some dependencies' installation scripts may fail if the path where you cloned vcpkg or the Aleph One repository contain certain characters such as '+' or spaces.

Release binaries are built using the latest Xcode (the 1.5 release was built with Xcode 13). The Xcode project is located at PBProjects/AlephOne.xcodeproj. The first thing you'll need to do if you are not the official maintainer is change or turn off the developer certificate in the Xcode project's signing settings. Note that you can only build the target "Aleph One" without the game data; the various Marathon targets require game data to be present, which means you must clone the Aleph One repository with `git clone --recurse-submodules`. Disk images for final release are built outside of Xcode using the script tools/build_dmg.sh.

# README (in main dir.)

#### This change simply updates the readme to use Markdown. Please also change its name to README.md.
----
# Aleph One

Aleph One is the open source continuation of Bungie's Marathon 2 FPS game engine. Aleph One plays Marathon, Marathon 2, Marathon Infinity, and 3rd-party content on a wide array of platforms, with (optional) OpenGL rendering, Internet play, Lua scripting, and more.

Binary releases and scenario files are available at the [Aleph One web site](https://alephone.lhowon.org/).

For more information and instructions on compiling from source, check out the [Aleph One wiki](https://github.com/Aleph-One-Marathon/alephone/wiki).

**Comment by treellama** [comment]
Hopefully addressed by c315bbd
