### ISSUE TITLE
M1: reload sound on pistols plays on wrong frame

### ISSUE THREAD

**Issue by MaddTheSane** [Aleph-One-Marathon/alephone#352]
When playing Marathon 1, the sound for reload is on the wrong frame. I remember it being on frame 2 of 3, but Aleph One plays it on frame 3.

**Comment by Iritscen** [comment]
In case it's helpful, see attached videos of a pistol reload in Marathon 1 v1.2 and in Aleph One v1.5.  I did not test or record other weapon reloads but can upon request.

https://user-images.githubusercontent.com/1541542/175843937-2875c54b-87b4-47d4-abed-01c2f005300e.mp4

https://user-images.githubusercontent.com/1541542/175843946-6aa8b6b7-c855-48eb-b461-40d91ed54c14.mp4

**Comment by treellama** [comment]
Here is a fix for this, but it will affect the film profile so it's pending the next film profile change:

```diff
diff --git a/Source_Files/GameWorld/weapons.cpp b/Source_Files/GameWorld/weapons.cpp
index 800b517b..a7621f68 100644
--- a/Source_Files/GameWorld/weapons.cpp
+++ b/Source_Files/GameWorld/weapons.cpp
@@ -3146,8 +3146,16 @@ static void calculate_ticks_from_shapes(
        
                        total_ticks= high_level_data->ticks_per_frame*high_level_data->frames_per_view;
                        definition->await_reload_ticks= 0;
-                       definition->loading_ticks= high_level_data->ticks_per_frame*(high_level_data->key_frame+1)
+                       if (definition->flags & _weapon_is_marathon_1)
+                       {
+                               definition->loading_ticks= high_level_data->ticks_per_frame*(high_level_data->key_frame)
+                               - definition->await_reload_ticks;
+                       }
+                       else
+                       {
+                               definition->loading_ticks= high_level_data->ticks_per_frame*(high_level_data->key_frame+1)
                                - definition->await_reload_ticks;
+                       }
                        definition->finish_loading_ticks= total_ticks - definition->loading_ticks 
                                - definition->await_reload_ticks;
                } else {
```

**Comment by Iritscen** [comment]
I have recorded the MA-75 to show the difference in reload frame with this weapon too:

https://user-images.githubusercontent.com/1541542/179283415-5982c61a-e044-4df3-ae89-c8226c804017.mp4


https://user-images.githubusercontent.com/1541542/179283430-aa56f823-c44b-483b-9780-d314624a10f8.mp4
