### ISSUE TITLE
(v1.3a1) Engine: The load menu scrolls one save-point too many.

### ISSUE THREAD

**Issue by Zetren** [Aleph-One-Marathon/alephone#36]
**Default AOI plugins** 
Using the mouse's scroll wheel to scroll will result in it going past a whole save. If there are 10 saves on the menu for instance, I initially see the first 4 saves. Scrolling once will skip save 5 and present me with saves 6 to 9

**Comment by Hopper262** [comment]
All list boxes in Aleph One scroll 3 lines per OS-level wheel 'tick', which is fine for the file dialogs, but not good for the more-recently-added plugins and saves. If you scroll 2 'ticks' (which, depending on your OS settings, may be your mouse's minimum speed) then you see this situation.

I'm changing it to 1 line at a time, which is good for plugins and saves but will slow down navigation of large file dialogs. To me, those dialogs still feel plenty fast even after the change, so I'll leave it for now and adjust the scroll speed per dialog if others complain.

Thanks for reporting this bug!
