### ISSUE TITLE
Memory leak with graphics plugins

### ISSUE THREAD

**Issue by wrkncacnter7** [Aleph-One-Marathon/alephone#361]
Each time you get a progress bar loading a level, it loads more data into memory. This is easiest to observe using a HD monster plugin on a map with a bunch of different monsters. Each time you start the game, quit to menu, and start the game again, alephone will consume more memory than before.

If I do this about 20 times, alephone either crashes, or my computer locks and I have to restart my computer.

This was observed using the latest master code on Linux.

**Comment by wrkncacnter7** [comment]
I tried this on windows and wasn't able to reproduce it there with the 1.5 release. The issue remains in 1.5 on linux, so maybe this is something specific to linux or a dependency I have?

**Comment by treellama** [comment]
I don't see any appreciable leaks in valgrind here with Linux, Intel Mesa. If you are using binary drivers, can you try with open source and see if it is better?

**Comment by jonirons** [comment]
I have the same issue, and encountered it starting earlier this year, concurrent with me trying a bunch of hi-res stuff, rather than post 1.6. In my case, I'm using the nouveau driver. Apologies for the format of the attached file. Just the output of `alephone` to stdout (with print statements on init and player killed) plus timestamps and the output of `free`. I haven't tried valgrind but am willing to do so.

[ram.txt](https://github.com/Aleph-One-Marathon/alephone/files/10187528/ram.txt)

**Comment by jonirons** [comment]
tail end of `valgrind` output

```
==21055== Warning: set address range perms: large range [0x52b7d0040, 0x54b7d0040) (undefined)
==21055== Warning: set address range perms: large range [0x54b7d1040, 0x56b7d1040) (undefined)
==21055== Warning: set address range perms: large range [0x56b7d2040, 0x58b7d2040) (undefined)
==21055== Warning: set address range perms: large range [0x58b7d3040, 0x5ab7d3040) (undefined)
==21055== Warning: set address range perms: large range [0x52b7d0028, 0x54b7d0058) (noaccess)
==21055== Warning: set address range perms: large range [0x54b7d1028, 0x56b7d1058) (noaccess)
==21055== Warning: set address range perms: large range [0x56b7d2028, 0x58b7d2058) (noaccess)
==21055== Warning: set address range perms: large range [0x58b7d3028, 0x5ab7d3058) (noaccess)
==21055== 
==21055== HEAP SUMMARY:
==21055==     in use at exit: 38,514,678 bytes in 16,542 blocks
==21055==   total heap usage: 11,572,285 allocs, 11,555,743 frees, 42,676,556,936 bytes allocated
==21055== 
==21055== LEAK SUMMARY:
==21055==    definitely lost: 4,248 bytes in 23 blocks
==21055==    indirectly lost: 5,537,041 bytes in 5,962 blocks
==21055==      possibly lost: 31,234,538 bytes in 109 blocks
==21055==    still reachable: 1,738,815 bytes in 10,447 blocks
==21055==         suppressed: 36 bytes in 1 blocks
==21055== Rerun with --leak-check=full to see details of leaked memory
==21055== 
==21055== Use --track-origins=yes to see where uninitialised values come from
==21055== For lists of detected and suppressed errors, rerun with: -s
==21055== ERROR SUMMARY: 22 errors from 14 contexts (suppressed: 0 from 0)
```
