### ISSUE TITLE
[Suggestion] Support for building locally on 32-bit Windows?

### ISSUE THREAD

**Issue by rzhxiii** [Aleph-One-Marathon/alephone#365]
From what I understand, compiling Aleph One's source code on Windows is usually done using Visual Studio 2022, which only runs on 64-bit Windows computers.
I've tried to do it using Visual Studio 2019, but it fails because the solution specifically asks for build tools that were only shipped with Visual Studio 2022.
Since Aleph One can run on 32-bit Windows, I would suggest implementing a way to compile it locally directly on 32-bit Windows computers, whether through older version of Visual Studio or through something else, like MSYS/ MinGW.
I could be wrong about this, so please do let me know if that's the case.
If it's not feasible, it's not the end of the world as one could use the released versions to play the games, but I like being "up-to-date" so to speak.

**Comment by Kolfering** [comment]
We were using VS2019 before VS2022 came out, normaly the only thing you would have to do to make it work in VS2019 is editing the project files to downgrade the platform toolset from v143 to v142. 
Here is the commit about the upgrade from VS2019 to VS2022 you can revert to see how it goes: 09c348ca.
