### ISSUE TITLE
(v1.3a1) Marathon 1: The rocket launcher first person sprite displays incorrectly at 1920x1080

### ISSUE THREAD

**Issue by Zetren** [Aleph-One-Marathon/alephone#37]
**Aleph One v1.3a1.**
http://puu.sh/qsbwQ/307be792be.jpg

There is a gap between the beginning of the sprite and the monitor. Also the crosshair is too far left. I am using Alpha's improved weapons sprites but the bug is present without that mod

**Comment by Kolfering** [comment]
Duplicate of #222
