### ISSUE TITLE
A toggle for classic_aim_speed_limits should be added in game.

### ISSUE THREAD

**Issue by NolanHewitt** [Aleph-One-Marathon/alephone#371]
Changing this setting in the preferences file provides a very big improvement to mouse aim, but unlike other mouse settings there is no in-game check box for this. Adding one would be a very nice QOL change. Being able to set lower mouse sens values in game would be another nice feature. For reference I'm using 1410 in the preferences file.

**Comment by treellama** [comment]
bcc2d12b
