### ISSUE TITLE
Enhanced HUD doesn't work under debian linux

### ISSUE THREAD

**Issue by spencerthayes** [Aleph-One-Marathon/alephone#372]
The HUD itself doesn't show up and the console keeps repeating "[string "HUD Lua"]:286:attempt to index global 'pos' (a nil value)"

screenshot:
![Screenshot_20220810_145821](https://user-images.githubusercontent.com/16262389/183996107-45fc002f-5e9f-46c4-af00-46d99e0fc7e8.png)

**Comment by treellama** [comment]
You need to install SDL_image
