### ISSUE TITLE
shader renderer: _xfer_fade_out_static transfer_data is ignored

### ISSUE THREAD

**Issue by treellama** [Aleph-One-Marathon/alephone#378]
The transfer data is set up for xfer_fade_out_static in render.cpp:818, but then it never appears to be used in RenderRasterize_Shader.cpp. This causes compilers to disappear instantly on death rather than fade out.

**Comment by Iritscen** [comment]
Attaching videos as requested.

https://user-images.githubusercontent.com/1541542/193342087-a5415d3a-7ec2-4fdf-b8ca-61912923619b.mp4

https://user-images.githubusercontent.com/1541542/193342106-931b56b2-622c-448e-8389-836687039b98.mp4
