### ISSUE TITLE
shader: static transfer lacks transparency

### ISSUE THREAD

**Issue by treellama** [Aleph-One-Marathon/alephone#379]
In the software renderer, some pixels in static transfer are transparent. See drop_less_than in randomize_vertical_polygon_lines. The shader renderer does not render these as transparent. This may gate #378

**Comment by Iritscen** [comment]
See attached videos showing transparent vs. non-transparent pixels.

https://user-images.githubusercontent.com/1541542/193342410-fe4e75e4-79e6-4a7d-9aae-ea31649f9465.mp4


https://user-images.githubusercontent.com/1541542/193342425-8c308fa6-80e7-4e5b-bfb3-015f200576ec.mp4
