### ISSUE TITLE
Player can shoot through "space ceilings" in Marathon

### ISSUE THREAD

**Issue by Iritscen** [Aleph-One-Marathon/alephone#388]
For lack of a better term, "space ceilings" are areas in the ceiling through which you can see outer space.  In the original Marathon, you cannot shoot through these, but in Aleph One projectiles can pass through them depending on the angle of fire.  See attached comparison videos from a ceiling in Bigger Guns Nearby.  The behavior has been confirmed at space ceilings beside this one, can provide other examples if desired.

https://user-images.githubusercontent.com/1541542/200203682-096c05ff-6ab1-4060-9a5a-c1ab33ef681a.mp4

https://user-images.githubusercontent.com/1541542/200203780-17f183ef-5c65-4b22-8aed-8887c5a7ac6d.mp4

**Comment by mmorrisonlk** [comment]
I was looking into this issue and thought I should document what I've found. I have confirmed projectiles do pass through these looking glass decorations in both Bigger Guns Nearby and the ones on the walls in Never Burn Money. I used cheats to test with the rocket launcher as well. Pistol and machine gun bullets, machine gun grenades and rocket launcher missiles disappear into the distance when fired at these objects without detonating.

I was able to test in Never Burn Money that if you fire the rocket or machine gun grenade point blank into the looking glass wall they will detonate and damage/kill the player but will not play the sound effect like it detonated into a wall. I suspect that it has something to do with the properties assigned to these specific walls. The player character is unable to move past these objects so they are catching player movement but not projectiles.
