### ISSUE TITLE
I can't choose solo script in marathon when it is on e: disk.

### ISSUE THREAD

**Issue by kotenok2000** [Aleph-One-Marathon/alephone#397]
I can't switch from c: directory tree to e: directory tree.
![Снимок экрана (266)](https://user-images.githubusercontent.com/8822292/204547138-8d96abb6-f8b5-4b22-9d1c-3f5992bbee61.png)

**Comment by Kolfering** [comment]
You need to enable "Use Native File Dialogs" for that, in Preferences => Environment
