### ISSUE TITLE
Saving and/or level changes sometimes causes primary fire trigger issues. (A1 1.6 Mac version)

### ISSUE THREAD

**Issue by Sharkie-Lino** [Aleph-One-Marathon/alephone#398]
While using A1 last night, and after doing some testing today, it seems sometimes after saving a game, or teleporting to the next level, it causes the primary trigger button (left mouse button in my case) to act up. Tested it on Eternal, KTA, and the regular Infinity map.

Instead of firing the weapon (all of them), it seems to completely freeze the game when pressed, and then unfreezes when let go, and will keep doing that. 

I noticed that if the pattern buffer is used again (sometimes after a couple of times), or if I pause and then unpause, the problem goes away and the weapon fires like normal again, at least until maybe the next pattern buffer usage or level change. It's kind of the luck of the draw, and the same "fixes" apply. 

Didn't see any issues happening with the 2nd trigger button.

**Comment by Sharkie-Lino** [comment]
Alright, Here's a copy of the file, with the metaserver password redacted. Also did the same to the join address. It wasn't mine but *shrugs* thought maybe it was a good idea. If not a big deal, I'll ignore it next time. 
[Marathon Infinity Preferences copy.txt](https://github.com/Aleph-One-Marathon/alephone/files/10200857/Marathon.Infinity.Preferences.copy.txt)

**Comment by Iritscen** [comment]
Very interesting!  I tried your prefs out and could reproduce the bug, but I now see that I can repro the bug even with the prefs that I had, as long as I run fullscreen and load certain savepoints (a pattern buffer in Aye Mak Sicur wasn't doing it for me, but one in ACCIVI was).  I'm trying some different things with the dev team to narrow down the problem.

**Comment by parkerwb** [comment]
Same, same... M1 Macbook Air playing Phoenix scenario... primary left trigger will freeze entire game after saving to buffer. Thanks for looking into this! Since it come always right after a save I just quit the game, restart and it's fine until the next time.

**Comment by Sharkie-Lino** [comment]
You might not have to quit. Try saving again, or pausing and then unpausing. It seems to work for me for now. Sometimes it will do it on one shot, or may take a couple of times.

**Comment by Iritscen** [comment]
The cause has basically been found, and a fix is under discussion.  For now I'll just mention that playing in windowed mode or turning off raw input in the mouse settings should avoid the bug.

**Comment by Sharkie-Lino** [comment]
Cool deal. Thanks for that info!

**Comment by treellama** [comment]
This is due to a change in SDL's behavior. I have filed this bug upstream:

https://github.com/libsdl-org/SDL/issues/6994
