### ISSUE TITLE
'UPNP_LOCAL_PORT_ANY’ was not declared in this scope

### ISSUE THREAD

**Issue by MWaleedK** [Aleph-One-Marathon/alephone#400]
I followed the readme instructions. Tried installing from both https://alephone.lhowon.org/ and https://github.com/Aleph-One-Marathon/alephone.git. Now, autoreconf -i does not report anything wrong. The ./configure phase runs butter-smooth. However when I make/ sudo make/ sudo checkinstall, I get this error:

PortForward.cpp: In constructor ‘PortForward::PortForward(uint16_t)’:
PortForward.cpp:17:7: error: ‘UPNP_LOCAL_PORT_ANY’ was not declared in this scope
       UPNP_LOCAL_PORT_ANY, false, 2, &error),
       ^~~~~~~~~~~~~~~~~~~
Makefile:518: recipe for target 'PortForward.o' failed
make[4]: *** [PortForward.o] Error 1

Yes, I have installed miniupnpc and other dependencies mentioned. My OS is Linux Mint 19 (Tara), Kernel version: 4.15.0-20-generic.

**Comment by treellama** [comment]
That #define is definitely included (PortForward.cpp includes PortForward.h which includes miniupnpc/miniupnpc.h). I'm not sure why your compiler can't find it.

Can you search /usr/include/miniupnpc/miniupnpc.h for UPNP_LOCAL_PORT_ANY?
