### ISSUE TITLE
Players:find_target() freezing app

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#403]
See here for further details including stack trace: https://discord.com/channels/190488331207835649/973622824923172954/1060094625123139654. In rare cases it causes an infinite loop that the app doesn’t know how to return from. I don’t know what the cause is, but all the maps I’ve seen it happen in are physically large and extend to near the edge of the map space.

ETA: Solra has identified this code as a likely culprit. There does not seem to be an escape hatch for this loop, which seems like a problem.

```c++
        // preflight a projectile, 1 WU at a time (because of projectile speed bug)
        uint16 flags = translate_projectile(0, &origin, old_polygon, &destination, &new_polygon,
                       player->monster_index, &obstruction_index, &line_index, true, NONE);

        while (!(flags & _projectile_hit))
        {
                origin = destination;
                old_polygon = new_polygon;

                translate_point3d(&destination, WORLD_ONE, player->facing, player->elevation);
                flags = translate_projectile(0, &origin, old_polygon, &destination, &new_polygon,
                        player->monster_index, &obstruction_index, &line_index, true, NONE);
        }
```

I’ve noticed that the game will frequently fail to target projectiles correctly at or near the edge of the map. This might be related – the map that was experiencing the freeze goes from -31.875 WU to 31.875 WU in both compass directions.

**Comment by aaronfreed** [comment]
This is definitely the source of the issue. Run the map in here with the solo script in here. The game will freeze as soon as the player gets to 16.125 WU. (Be warned, this freeze will cause your CPU usage to spike massively.) The player must be viewing in a cardinal direction and probably must be looking straight ahead, which is probably why it’s taken so long to isolate this bug. The map must also extend to near the edge of the screen. In such cases, because the find_target “projectile” moves precisely 1 WU per tick, it will just keep overflowing and never hit anything.

This is also why projectiles frequently fail to hit anything at the edges of the map – there’s no check for an integer overflow with projectiles. ISTM that the next film profile update could possibly fix that as well… but that’s an issue for another day.

[find_target freeze kit.zip](https://github.com/Aleph-One-Marathon/alephone/files/10343321/find_target.freeze.kit.zip)

**Comment by treellama** [comment]
Maps that extend past -31 or +31 WU are generally asking for trouble, due to the projectile issue. Perhaps editors should warn the user when saving such an invalid map. 846f77d2 will help out by returning a nil from find_target when this happens
