### ISSUE TITLE
Can't install, Debian 11 / BunsenLabs Linux

### ISSUE THREAD

**Issue by jason-mehmel** [Aleph-One-Marathon/alephone#404]
I'm downloading the release from https://alephone.lhowon.org/games/marathon.html#download

I'm trying to follow the instructions on the main page and here in Github, and I'm getting the following errors when I try to _make install_ or _sudo make install_.

```
/home/jason/Downloads/programs/AlephOne-20221126/Source_Files/Sound/SoundManager.cpp:862: undefined reference to `Movie::GetCurrentAudioTimeStamp()'
/usr/bin/ld: Sound/libsound.a(SoundManager.o): in function `SoundManager::PlaySound(short, world_location3d*, short, int)':
/home/jason/Downloads/programs/AlephOne-20221126/Source_Files/Sound/SoundManager.cpp:394: undefined reference to `Movie::GetCurrentAudioTimeStamp()'
/usr/bin/ld: Sound/libsound.a(SoundManager.o): in function `SoundManager::DirectPlaySound(short, short, short, int)':
/home/jason/Downloads/programs/AlephOne-20221126/Source_Files/Sound/SoundManager.cpp:447: undefined reference to `Movie::GetCurrentAudioTimeStamp()'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:536: alephone] Error 1
make[3]: Leaving directory '/home/jason/Downloads/programs/AlephOne-20221126/Source_Files'
make[2]: *** [Makefile:577: all-recursive] Error 1
make[2]: Leaving directory '/home/jason/Downloads/programs/AlephOne-20221126/Source_Files'
make[1]: *** [Makefile:563: all-recursive] Error 1
make[1]: Leaving directory '/home/jason/Downloads/programs/AlephOne-20221126'
make: *** [Makefile:457: all] Error 2
```

I'm fairly sure I've got all of the necessary libraries, but maybe you can tell if I'm missing something from here?

This is what came from the optional features in the config section:

```
    Enabled: OpenGL rendering
    Enabled: built-in Lua scripting
  Not found: SDL2_image support
  Not found: FFmpeg playback and film export
    Enabled: libmad MP3 playback
    Enabled: libsndfile audio decoding
    Enabled: libvorbis Ogg/Vorbis music playback
  Not found: SMPEG movie playback
  Not found: Speex net mic playback
    Enabled: ALSA net mic transmission
  Not found: cURL for HTTP communication
  Not found: zziplib support
    Enabled: libpng PNG screenshot support
  Not found: miniupnpc support

```

**Comment by treellama** [comment]
This was fixed in 2a6cea82757a2c5fa46c2a69e71cd2448c8bb3e2 which unfortunately was after the release. You've got three options:

1. Install the flatpak (easiest)
2. Install ffmpeg dependencies to build 1.6
3. Build from the latest in git

**Comment by jason-mehmel** [comment]
Interesting! I decided to go the flatpak route, though it was a bit tricky to find!

I googled first, and found this: https://www.gamingonlinux.com/forum/topic/5272/

But I should have checked here for the flatpaks in the current release. Ah well. The above link and files worked, so I'll keep going with them for now but when I switch distros again, or need to reinstall, I'll come here first!

**Comment by treellama** [comment]
We haven't updated alephone.lhowon.org to point to the flatpaks yet, but feedback so far indicates it is ok to do so.
