### ISSUE TITLE
This link is _20 years_ stale

### ISSUE THREAD

**Issue by wifiprintguy** [Aleph-One-Marathon/alephone#414]
https://github.com/Aleph-One-Marathon/alephone/blob/7e18182a352a9eefd6d0a4083152c75069937e75/docs/MML.html#L22

Check the Wayback machine:

https://web.archive.org/web/20060301000000*/http://www.trafficstudio.com/sixpack

**Comment by mmorrisonlk** [comment]
Removed the link and modified wording since there isn't a real need to have a link to a dedicated XML editor these days.
