### ISSUE TITLE
Varying issues with the original Marathon Rubicon (Non-X version)

### ISSUE THREAD

**Issue by eisnerguy1** [Aleph-One-Marathon/alephone#415]
So, I'm trying to use the [original Marathon Rubicon](https://web.archive.org/web/20020210123848/http://www.marathonrubicon.com/index_main.html) ([Non-X version](https://web.archive.org/web/20100209033835/http://www.marathonrubicon.com/)) in Aleph One 1.6.1 on my Mac and I'm running into some weird errors. When trying to load a saved game, I'm seeing this error:

`alert (ID=0): The scenario file that this saved game was from cannot be found.  When you switch levels you will revert to the default map. (/Users/runner/work/alephone/alephone/Source_Files/CSeries/csalerts_sdl.cpp:200)`
![Screenshot_0001](https://github.com/Aleph-One-Marathon/alephone/assets/3295271/b04577cc-a52e-4de9-a3c1-fd8d535bdb1a)

<br>
The saved game still loads properly though 🤔 (as far as I can tell)
<br>
<br>

When trying to view any of the “Rubicon Vidmaster Films” that were downloaded from the [old Marathon Rubicon site](https://web.archive.org/web/20020204070526/http://www.marathonrubicon.com/downloads.html), I’m getting this error message:

`alert (ID=0): Marathon Rubicon Classic was unable to find the map that this film was recorded on, so the film cannot be replayed. (/Users/runner/work/alephone/alephone/Source_Files/CSeries/csalerts_sdl.cpp:200)`
![Screenshot_0000](https://github.com/Aleph-One-Marathon/alephone/assets/3295271/9dfb75da-ee96-4820-9cd1-8ff556e62ca1)

<br>
The game is just brought back to the main menu. 
<br>
<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/3295271/241581623-df6c38dc-0588-4621-ba90-5ef09c56258a.png"
<br>

I have all of the files in the correct spot and selected properly:
<img width="574" alt="Screen Shot 2023-05-26 at 10 04 43 PM" src="https://github.com/Aleph-One-Marathon/alephone/assets/3295271/3f5db4bb-b664-4972-99b3-a17f80ee47e8">
![Screenshot_0004](https://github.com/Aleph-One-Marathon/alephone/assets/3295271/f0701fba-7265-41db-9307-1b54f3fdd0ea)

<br>
This is what I have in my "Marathon Rubicon Classic.mml" file:
<img width="502" alt="Screen Shot 2023-05-28 at 2 46 36 PM" src="https://github.com/Aleph-One-Marathon/alephone/assets/3295271/fe4b04a5-d58a-4547-9cb1-4e01536a0454">

<br>
Is this a known issue with the original Marathon Rubicon? Here's my preferences file if that helps at all:
<br>
https://pastebin.com/PDP8FrVG
<br>
<br>
Any help at all would be greatly appreciated 😄👍🏻 
<br>

**Comment by treellama** [comment]
Those error messages just mean Aleph One can't find the map file that matches the saved game of film.

**Comment by eisnerguy1** [comment]
🤔 That's a bit weird as I have the map selected and everything is listed in the Filesname.mml file properly:
<img width="519" alt="Screen Shot 2023-05-28 at 3 13 16 PM" src="https://github.com/Aleph-One-Marathon/alephone/assets/3295271/8074673e-6b43-4e6c-9d3a-b1cc69838f59">
