### ISSUE TITLE
Unable to use ALEPHONE_DATA Environment Variable Relative to Executable

### ISSUE THREAD

**Issue by MrMendelli** [Aleph-One-Marathon/alephone#416]
OS: Windows x64
Build: Latest

I am attempting to use the `ALEPHONE_DATA` environment variable to store data relative to the location of the executable. I have tried several different methods and syntax and none seem to make any difference, the `AlephOne` directory is still used in the default path of `%userprofile%\Documents\AlephOne\`. I am using a batch script to do this, everything works with the exception of my intended use of this feature. Here are some examples of coed I have tried:

```bat
md "%cd%\Data"
set ALEPHONE_DATA="%cd%\Data"
start "" ".\Marathon.exe" directory "%cd%" -f -Q
```
```bat
md "%cd%\Data"
set "ALEPHONE_DATA=%cd%\Data"
start "" ".\Marathon.exe" directory "%cd%" -f -Q
```
```bat
md "%cd%\Data"
set ALEPHONE_DATA=%cd%\Data
start "" ".\Marathon.exe" directory "%cd%" -f -Q
```

```bat
md ".\Data"
set ALEPHONE_DATA=".\Data"
start "" ".\Marathon.exe" directory "%cd%" -f -Q
```
```bat
md ".\Data"
set "ALEPHONE_DATA=.\Data"
start "" ".\Marathon.exe" directory "%cd%" -f -Q
```
```bat
md ".\Data"
set ALEPHONE_DATA=.\Data
start "" ".\Marathon.exe" directory "%cd%" -f -Q
```

I have also tried using full static paths and I get the same result of no change in where the data directory is stored. Since I am able to use the `%cd%` wildcard for the location of the scenario data, I am wondering why there is no effect for the data location variable. I am unsure if I am doing something wrong or if this is a bug, either way I would like the ability to house data in the intended location.

**Comment by treellama** [comment]
`ALEPHONE_DATA` specifies the location of some default files (like Fonts and Themes; it's mostly outdated) to _load_. It doesn't specify the location of saved files.
