### ISSUE TITLE
Linux - Controller Support not functioning

### ISSUE THREAD

**Issue by flawedintellect** [Aleph-One-Marathon/alephone#419]
Regarding Aleph One Version 1.6.1 and 1.6.2 
On my Steam Deck, running on SteamOS v3.4.8 [and also with previous versions], running the flatpak releases of the Marathon games, the game engine does not seem to recognize the Steam Deck's built in controls as a controller. When an external dock is plugged in, with an Xbox controller plugged into the external dock, the game engine does not recognize the presence of the Xbox controller either. [Note: in the case of plugging in an external controller, I've tried both plugging it in with the game program running, and also plugging it in before launching the game, and in both cases, the game doesn't recognize the external controller.]
[Yes, I'm aware of a work-around involving importing the games into Steam and using the controller mapping feature to map the game's default keyboard and mouse inputs to a controller. Nonetheless, it'd be nice if it were possible for controllers to work immediately on a fresh install.]

On my desktop PC on Windows 10, I could plug in an Xbox controller and use it in-game with no issues.

**Comment by treellama** [comment]
See this entry in the flathub wiki: https://github.com/flathub/com.valvesoftware.Steam/wiki#my-controller-isnt-being-detected
