### ISSUE TITLE
(v1.2.1) Marathon 2: level "Kill Your Television" erroneous scenery placement.

### ISSUE THREAD

**Issue by Zetren** [Aleph-One-Marathon/alephone#42]
There is a [lamp scenery](http://images.akamai.steamusercontent.com/ugc/263844677731631495/368E29EB837CB079FEF92CEAFACDD3A7AA6D02ED/) the wrong place located [here](http://images.akamai.steamusercontent.com/ugc/263844677731632184/F4D9ED50B32B5D4F6DA830CF0826DC43C72175DB/)

I am using all plugins which are enabled by default upon fresh installation of Marathon 2 from the main page.

**Comment by SolraBizna** [comment]
The incorrectly-placed lamp is present in the data, and can be seen both in the original Marathon 2 and in Forge.

**Comment by Hopper262** [comment]
The Aleph One project simply distributes the games as produced by Bungie and will not fix bugs in the original data. In fact, Bungie has not explicitly given permission for others to create and share edited versions, so I would not feel comfortable publishing tweaks even if we wanted to. I see that as different from fan scenarios, which feature a lot of original work beyond what Bungie did.
