### ISSUE TITLE
(v1.3a1) Marathon Infinity audio popping

### ISSUE THREAD

**Issue by Zetren** [Aleph-One-Marathon/alephone#43]
Cross posting this so that it may be noticed by the maintainers

http://pfhorums.com/viewtopic.php?p=167032#p167032

**Comment by SolraBizna** [comment]
If I'm not mistaken, this bug is present in the original game. Several of the ambient sounds have popping issues. This is a case of Aleph One faithfully presenting the game's data.

**Comment by Hopper262** [comment]
It's certainly possible for Aleph One to introduce popping issues -- one snuck into the last sound rewrite. But as Solra says, there are a lot of problems with the original sounds so we'd need evidence these pops were not in earlier versions or the original Mac games.

As mentioned in #42, we won't fix problems in the original game data. Please reopen this or file a new issue if you do notice a regression between versions, though!
