### ISSUE TITLE
Does not support High-DPI Windows

### ISSUE THREAD

**Issue by rkuykendall** [Aleph-One-Marathon/alephone#434]
If I set my scaling to 150% on Windows then SDL thinks my monitor is 1440p, [similar to this issue](https://discourse.libsdl.org/t/4k-28-fullscreen-reporting-as-1440p/31566). That lead me to https://github.com/libsdl-org/SDL/issues/2119 where it looks like High-DPI can be enabled with the `SDL_WINDOW_ALLOW_HIGHDPI` flag or with some additions to the manifest.

**Comment by treellama** [comment]
Duplicate of #229
