### ISSUE TITLE
Antialiasing doesn't seem to work

### ISSUE THREAD

**Issue by Lrflx** [Aleph-One-Marathon/alephone#437]
Got Aleph One 1.6.2 prepackaged with M1 and doesn't matter if I set AA from ingame or force it through driver there's no visible effect on geometry at all. Using Nvidia card here

**Comment by treellama** [comment]
Duplicate of #237

**Comment by Lrflx** [comment]
Woudn't it be better to remove the option completely then? Cause it definitely gives wrong assumption.
Also not to hijack with another request, but I tried additionaly with DSR and it might've worked pretty well, only caveat is that map doesn't scale properly at high resolution, it becomes too small and illegible very fast.

**Comment by treellama** [comment]
From the other issue: 

> We either need to render multisampled to the FBO, or remove the slider.
