### ISSUE TITLE
Display corruption when shooting liquids

### ISSUE THREAD

**Issue by Q3BFG10K** [Aleph-One-Marathon/alephone#441]
Win10-64, Marathon 2, 1.6.2, OpenGL, unlimited framerate. Happens with or without the HD content.

This is a recent problem probably 1-2 releases old as I don't recall it on 1.6. 

![Liquid](https://github.com/Aleph-One-Marathon/alephone/assets/40132921/58ea4204-e3df-4487-bb03-9e263759b4bb)

**Comment by Kolfering** [comment]
This happens while having transparent liquid plugin enabled at the same time as HD monsters plugin
