### ISSUE TITLE
"wander" transfer mode crashes software mode on Windows with really short lines

### ISSUE THREAD

**Issue by aaronfreed** [Aleph-One-Marathon/alephone#451]
"short" being, in this case, one internal unit (or mibi-World Unit or 1/1024 WU. whatever you want to call it). presumably this is because it has no sanity check to see that vector_magnitude is not zero before dividing by it

**Comment by aaronfreed** [comment]
[Septococcal Pfhoryngitis software crash.zip](https://github.com/Aleph-One-Marathon/alephone/files/13501464/Septococcal.Pfhoryngitis.software.crash.zip)

Best viewed with Eternal's shapes, but it doesn't really matter; it'll probably crash Windows in software mode no matter what you use if you so much as move a muscle. Weirdly it doesn't seem to crash on MacOS. I leave drawing conclusions from this as an exercise for the reader.

**Comment by aaronfreed** [comment]
[Septococcal Pfhoryngitis normal side crash.zip](https://github.com/Aleph-One-Marathon/alephone/files/13502943/Septococcal.Pfhoryngitis.normal.side.crash.zip)
Sides have "normal" transfer mode. Still crashes when i move at all

**Comment by LidMop** [comment]
I see that we get a divide-by-zero for any drawn vertical texture with a slide, wander, or pulsate transfer mode on a line that is degenerate or that is so close to being degenerate that it rounds to degenerate in eye space (e.g. a length-1 line will be OK for some camera yaw values and not others). No crash occurs if the texture is invalid/absent.
