### ISSUE TITLE
1.7 Color depth reduction with OpenGL

### ISSUE THREAD

**Issue by Sharkie-Lino** [Aleph-One-Marathon/alephone#470]
I happen to notice that when using an older A1 (1.6) the color depth looked richer, and it was. Did another test by switching to Software in 1.7 and after you accept the changes and return to the main menu, the color richness comes back. You can immediately see it in the main menu screen as well. Two in game images here to show the differences. Top image is 1.6

<img width="2560" alt="Screenshot 2024-03-09 at 7 23 28 PM" src="https://github.com/Aleph-One-Marathon/alephone/assets/80301156/cc2939b2-b816-4051-9746-74ad9d3ce4df">
<img width="2560" alt="Screenshot 2024-03-09 at 7 25 28 PM" src="https://github.com/Aleph-One-Marathon/alephone/assets/80301156/c45175aa-c1a7-4737-b33d-50dfb0dbd4f1">

**Comment by treellama** [comment]
We determined that the new behavior is the correct one--per https://github.com/libsdl-org/SDL/commit/d2300516c3998277c993fd4ac336fbb4ba71641a it was likely oversaturated on wide gamut displays pre-1.7. This was also confirmed by comparing the landscape image to the shapes file.
