### ISSUE TITLE
Random sprites when Aleph One opens Marathon 1

### ISSUE THREAD

**Issue by imcinnes31** [Aleph-One-Marathon/alephone#477]
Have played Marathon 1 on Aleph One with no issues, but now it is behaving very strangely:

- The game opens up with holding a missile launcher (not in frame) which shoots images of hand holding alien weapon. 
- Green fighters are shown as looker bugs repeatedly blowing up. 
- Fists show up as pistol reloading
- Orange fighters become compilers
- End terminals are not working

And this is just a few that I've seen so far. Anything need to be updated?

**Comment by behSMart** [comment]
Try to delete your preferences file, or at least rename it and see if it fixes your issue.
https://github.com/Aleph-One-Marathon/alephone/wiki/File-Locations
If it does, can you upload your file here after removing your network credentials from it if you have some?
