### ISSUE TITLE
Transparent_Liquids.mml interfears with CFP replacement sprites when loaded as a plugin

### ISSUE THREAD

**Issue by JoshuaPettus** [Aleph-One-Marathon/alephone#499]
This is an odd one.

When the same Transparent_Liquids.mml is loaded as a plugin as oppose to the standard mml Scripts folder, (Ala the current dataset release) it interferes with my Freeverse Scenery replacement sprites.  Specifically the transparency part of the image becomes colored.  Seems to be some sort of ordering issue...  I tried turning on the Transparent Liquid plugin before the scenery plugin and had the same effect.

![Screenshot from 2024-06-20 22-00-50](https://github.com/Aleph-One-Marathon/alephone/assets/5043172/7496c5fa-5a2f-43fb-ba40-f1594b004f6d)

The plugin in question is here
https://simplici7y.com/items/community-freeverse-plugin-scenery/

**Comment by treellama** [comment]
The transparent liquids plugin is only for the built-in shapes. You should disable it if you're using the Freeverse graphics
