### ISSUE TITLE
Feature Request: Read .sceA data from dedicated Netmaps folder

### ISSUE THREAD

**Issue by Shockwave508** [Aleph-One-Marathon/alephone#505]
Given how insanely-cluttered the game directory can be with a great big pile of netmap-only .sceA files lying around, I think it would be better if Aleph One could read such files from a dedicated Netmaps folder, given how recent updates let you select any map from any detected .sceA during multiplayer session setup.

**Comment by treellama** [comment]
The env selectors are recursive, so you should be able to organize maps however you like...
