### ISSUE TITLE
gluScaleImage

### ISSUE THREAD

**Issue by parkerwb** [Aleph-One-Marathon/alephone#512]
Setting up a brand new linux box and feening for some AlephOne action. Folllowing the Linux HOW-TO for building from source, which I've done before successfully, but on my fresh Mint distro I'm getting this error (can't seem to find the pkg I need... tried lots of different mesa, libglu etc.):

`/usr/bin/ld: RenderMain/librendermain.a(OGL_Textures.o): in function `TextureManager::Shrink(unsigned int*)':
/home/parker/Documents/AlephOne-20240822/Source_Files/RenderMain/OGL_Textures.cpp:1192: undefined reference to `gluScaleImage'
/usr/bin/ld: RenderMain/librendermain.a(OGL_Textures.o): in function `TextureManager::PlaceTexture(ImageDescriptor const*, bool)':
/home/parker/Documents/AlephOne-20240822/Source_Files/RenderMain/OGL_Textures.cpp:1296: undefined reference to `gluBuild2DMipmaps'
/usr/bin/ld: RenderMain/librendermain.a(OGL_Textures.o): in function `LoadModelSkin(ImageDescriptor&, short, short)':
/home/parker/Documents/AlephOne-20240822/Source_Files/RenderMain/OGL_Textures.cpp:1668: undefined reference to `gluBuild2DMipmaps'
/usr/bin/ld: RenderMain/librendermain.a(ImageLoader_Shared.o): in function `ImageDescriptor::Minify()':
/home/parker/Documents/AlephOne-20240822/Source_Files/RenderMain/ImageLoader_Shared.cpp:153: undefined reference to `gluScaleImage'`

**Comment by treellama** [comment]
It's got to be in libGLU right? 

```
$ ldd ~/Development/alephone/build/Source_Files/alephone | grep -i glu
	libGLU.so.1 => /lib/x86_64-linux-gnu/libGLU.so.1 (0x00007f94653c3000)
```

**Comment by parkerwb** [comment]
Installed as near as I can tell... thought maybe :i386, but that didn't help. I'm way too stoopid with linux to know much more than typing ./configure make etc. haha. Hmm. Will keep googling. On Linut Mint Debian Edition, which is new to me. This all "just worked" on Bookworm, but I had other issues so had to move to another distro.

`make[3]: Entering directory '/home/parker/Documents/AlephOne-20240822/Source_Files'
g++  -g -O2   -o alephone shell.o shell_misc.o shell_options.o main.o CSeries/libcseries.a Files/libfiles.a FFmpeg/libffmpeg.a GameWorld/libgameworld.a Input/libinput.a Lua/liba1lua.a Misc/libmisc.a ModelView/libmodelview.a Network/libnetwork.a Network/Metaserver/libmetaserver.a RenderMain/librendermain.a RenderOther/librenderother.a Sound/libsound.a XML/libxml.a CSeries/libcseries.a Files/libfiles.a FFmpeg/libffmpeg.a GameWorld/libgameworld.a Input/libinput.a Lua/liba1lua.a Misc/libmisc.a ModelView/libmodelview.a Network/libnetwork.a Network/Metaserver/libmetaserver.a RenderMain/librendermain.a RenderOther/librenderother.a Sound/libsound.a TCPMess/libtcpmess.a XML/libxml.a -lminiupnpc -lpng16  -lzzip -lz  -lcurl  -lavcodec -lavformat -lavutil -lswscale -lswresample  -lSDL2_image -lSDL2  -lopenal  -lsndfile  -lz  -lSDL2_net -lSDL2  -lSDL2_ttf -lSDL2  -lboost_filesystem -lboost_system  -lSDL2  -lGL -lpthread
/usr/bin/ld: RenderMain/librendermain.a(OGL_Textures.o): in function `TextureManager::Shrink(unsigned int*)':
/home/parker/Documents/AlephOne-20240822/Source_Files/RenderMain/OGL_Textures.cpp:1192: undefined reference to `gluScaleImage'
/usr/bin/ld: RenderMain/librendermain.a(OGL_Textures.o): in function `TextureManager::PlaceTexture(ImageDescriptor const*, bool)':
/home/parker/Documents/AlephOne-20240822/Source_Files/RenderMain/OGL_Textures.cpp:1296: undefined reference to `gluBuild2DMipmaps'
/usr/bin/ld: RenderMain/librendermain.a(OGL_Textures.o): in function `LoadModelSkin(ImageDescriptor&, short, short)':
/home/parker/Documents/AlephOne-20240822/Source_Files/RenderMain/OGL_Textures.cpp:1668: undefined reference to `gluBuild2DMipmaps'
/usr/bin/ld: RenderMain/librendermain.a(ImageLoader_Shared.o): in function `ImageDescriptor::Minify()':
/home/parker/Documents/AlephOne-20240822/Source_Files/RenderMain/ImageLoader_Shared.cpp:153: undefined reference to `gluScaleImage'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:547: alephone] Error 1
make[3]: Leaving directory '/home/parker/Documents/AlephOne-20240822/Source_Files'
make[2]: *** [Makefile:604: all-recursive] Error 1
make[2]: Leaving directory '/home/parker/Documents/AlephOne-20240822/Source_Files'
make[1]: *** [Makefile:560: all-recursive] Error 1
make[1]: Leaving directory '/home/parker/Documents/AlephOne-20240822'
make: *** [Makefile:454: all] Error 2
parker@MP61LMDE:~/Documents/AlephOne-20240822$ apt search libglu
v   libglu-dev                                                    -                                                                        
v   libglu-dev:i386                                               -                                                                        
v   libglu1                                                       -                                                                        
v   libglu1:i386                                                  -                                                                        
i   libglu1-mesa                                                  - Mesa OpenGL utility library (GLU)                                      
i A libglu1-mesa:i386                                             - Mesa OpenGL utility library (GLU)                                      
i   libglu1-mesa-dev                                              - Mesa OpenGL utility library -- development files                       
i   libglu1-mesa-dev:i386                                         - Mesa OpenGL utility library -- development files                       
p   libgluegen2-build-java                                        - Tool to automatically generate the Java and JNI code                   
p   libgluegen2-doc                                               - Tool to automatically generate the Java and JNI code                   
p   libgluegen2-jni                                               - Tool to automatically generate the Java and JNI code                   
p   libgluegen2-jni:i386                                          - Tool to automatically generate the Java and JNI code                   
p   libgluegen2-rt-java                                           - Tool to automatically generate the Java and JNI code                   
p   libglusterd0                                                  - GlusterFS glusterd shared library                                      
p   libglusterd0:i386                                             - GlusterFS glusterd shared library                                      
p   libglusterfs-dev                                              - Development files for GlusterFS libraries                              
p   libglusterfs-dev:i386                                         - Development files for GlusterFS libraries                              
p   libglusterfs0                                                 - GlusterFS shared library                                               
p   libglusterfs0:i386                                            - GlusterFS shared library                                               
i   libglut-dev                                                   - OpenGL Utility Toolkit development files                               
p   libglut-dev:i386                                              - OpenGL Utility Toolkit development files                               
i A libglut3.12                                                   - OpenGL Utility Toolkit                                                 
p   libglut3.12:i386                                              - OpenGL Utility Toolkit`

**Comment by treellama** [comment]
I don't see `-lGLU` in that link line...any chance you didn't re-run ./configure after installing libGLU?

**Comment by parkerwb** [comment]
Good chance of that... derp... will re-do... thanks and sorry for n00b.

**Comment by parkerwb** [comment]
That worked. Thanks and sorry to spam the Issues. Note to self: always re-./configure!
