### ISSUE TITLE
Aim get occasionally stuck when playing on controller

### ISSUE THREAD

**Issue by Kolfering** [Aleph-One-Marathon/alephone#513]
See this video showing the problem: https://www.youtube.com/watch?v=VzTsGMVmj18
When this happens, moving the aim stick horizontaly no longer does anything and the mouse must be moved to make the problem go away.
It's not easy to reproduce and might need having a specific sensitivity for this to happen.

**Comment by Hopper262** [comment]
I had this happen to me over the weekend, on a fresh Steam install of Marathon 2. IIRC, the only change I made to preferences was setting 120 FPS.

**Comment by Kolfering** [comment]
After more testing, I could reproduce it and save it as a film. I'am not sure the film will be very helpful since the issue to debug is while processing aim inputs. That time it happened vertically and not horizontally with the standalone version. 
An easy way to simulate that situation is by adding these lines of code
```patch
diff --git a/Source_Files/Input/joystick_sdl.cpp b/Source_Files/Input/joystick_sdl.cpp
index 81013d92..7ba9e772 100644
--- a/Source_Files/Input/joystick_sdl.cpp
+++ b/Source_Files/Input/joystick_sdl.cpp
@@ -188,6 +188,13 @@ int process_joystick_axes(int flags, int tick) {
 			angular_deltas[info.abs_pos_index] += norm * (info.negative ? -1.0 : 1.0) * angle_per_norm;
 		}
 	}
+
+	static bool firstPass = true;
+	if (firstPass)
+	{
+		firstPass = false;
+		angular_deltas[_flags_yaw] = 0.5;
+	}
 	
 	// return this tick's action flags augmented with movement data
 	const fixed_angle dyaw = static_cast<fixed_angle>(angular_deltas[_flags_yaw] * FIXED_ONE);


```

process_aim_input will then get stuck there with a vir_aim_delta.yaw value moving from 32768 one frame to -32768 the next one, then 32768 again then -32768 etc...

Recording in M2 waterloo: (had to be zipped for github)
[bug_joystick.zip](https://github.com/user-attachments/files/16964546/bug_joystick.zip)
