### ISSUE TITLE
Feature request: clear a side's primary texture from Lua

### ISSUE THREAD

**Issue by Hopper262** [Aleph-One-Marathon/alephone#514]
Once a side has been assigned a primary texture, it cannot be cleared via Lua, unlike the transparent texture. This is especially problematic when changing a polygon's height: if a high/low/split side becomes a full side, the primary texture will render in the previously-open area. The only way to make the side visibly transparent again is to assign a non-existent texture index from a valid collection (and hope any custom Shapes file leaves that spot blank), or to remove the line's sides in Weland and re-texture it as needed.

A Lua script would probably need at least one of the following to reliably clear these sides within Visual Mode:

* Add `Sides[index].primary.empty`
* Allow deletion of sides
* Stop rendering primary textures on full sides of two-polygon lines. The "primary + transparent" layering technique is discouraged in the [Forge FAQ](https://marathon.bungie.org/story/hastur_aug97/Bungie/forgefaq.html#usingforge), but I assume it's used in some scenarios.

**Comment by treellama** [comment]
I think `.empty` probably makes the most sense here. Maybe there is a use case for deleting sides, but I don't think it's needed for this one.
