### ISSUE TITLE
Joystick Y axis too sensitive or the Deadzone doesn't seem to work? 

### ISSUE THREAD

**Issue by albrechtjess** [Aleph-One-Marathon/alephone#525]
No matter how much you adjust the deadzone it seems to not really work. When I aim left and right using a steam deck controller joystick it seems to be really sensitive to vertical movements. I'm curious if perhaps the vertical deadzone doesn't exist compared to the horizontal deadzone?

**Comment by Kolfering** [comment]
It applies on both joysticks. 
If the maximum dead zone value is not enough for some setups I suppose we could increase the range in the slider.

**Comment by albrechtjess** [comment]
If that's the case that'd be an easy fix as I think the maximum currently is 10?

**Comment by albrechtjess** [comment]
It could also be that the Y axis is way more sensitive then the X axis? I notice that even with the sensitivity turned down looking up and down is still super sensitive. I notice that the deadzone works as intended when set to 0 but even on the max of 10 it is really hard to spin a full 360 without it going slightly up or down so I'm curious if the sensitivity values are different on the x and y?

**Comment by Kolfering** [comment]
No, they are the same. 
That's probably more of an impression you got there.
Usually games (at least FPS / TPS or other kinds where aiming is important) allow you to setup sensitivity / dead zone per axis and that's probably something we should do too. I'll see if I can make it for the next update.

**Comment by albrechtjess** [comment]
I noticed this morning there is sensitivity per axis for mouse so I imagine that code could maybe be adapted for the joystick.

**Comment by albrechtjess** [comment]
Yasss! Thank you! I'll have to give it a try!
