### ISSUE TITLE
Game hangs with blank screen after completing 15 levels without respawning

### ISSUE THREAD

**Issue by joeyadams** [Aleph-One-Marathon/alephone#53]
If you try to play a scenario from start to finish without respawning from a pattern buffer, the game will hang with a blank screen after you have completed exactly 15 levels.  Every time.  This might be related to #38.

I have reproduced this on a recent Windows build, and on a Linux debug build at commit 1eab7361 (master as of September 4, 2016).

It can be reproduced in the following ways:
 1. Literally play the game without saving until you complete 15 levels.  The game will hang with a blank screen after you teleport out of the 15th level you've played.
 2. Load a replay that has been saved after reproducing (1) (I have such a replay).  The game will hang in the same fashion at the end of the replay.
 3. (Fastest) Use scripting to teleport to a level 15 times.

To reproduce quickly:
* Check out and compile https://github.com/joeyadams/alephone/tree/TestTeleport15
  - This contains a workaround to make the `Players:teleport_to_level` Lua command work, and a tweak to Cheats.lua to make the console button (`) use it.
* Launch Marathon Infinity (I haven't tested other scenarios).
* Load [Cheats.lua from the branch](https://github.com/joeyadams/alephone/blob/TestTeleport15/examples/lua/Cheats.lua).
* Begin a new game.
* Hit the console button 15 times in a row (waiting for teleport each time).  This simulates playing 15 levels without respawning.  After the 15th press, the game will be hung.

When the game hangs, the event loop in shell.cpp runs, and you hear the background sound of the target level, but you see a blank screen, and any platforms and monsters that would activate on start do not activate.  The reason hitting Esc does not work when you reproduce this for real (1 or 2 above) is because you just left a terminal, and there's logic to prevent Esc from doing anything within one game second of accessing a terminal (no game seconds elapse in this hang).

**Comment by joeyadams** [comment]
I am very close to finding the root cause.  It has to do with a discrepancy between `heartbeat_count` and the current user's `action_queue`, which apparently have to be in sync for the game to progress.

The 15 comes from vbl.cpp `MAXIMUM_TIME_DIFFERENCE`, which (as far as I can tell) prevents the game from fast forwarding an absurd amount when the game world can't keep up with the timer (e.g. due to lag).  If the heartbeat count is ahead of game ticks by 15 or more, we essentially freeze the timer until the game logic can catch up.

But the ahead-ness of `heartbeat_count` is tied to the number of events in the current player's `action_queue`.  Normally, the following evaluates to zero:

    (heartbeat_count - dynamic_world->tick_count) - GetRealActionQueues()->countActionFlags(local_player_index)

But every time you teleport to another level, this increases to 1, 2, 3, etc.  Once it hits 15, the game freezes; the `input_controller` method thinks there's a full backlog of user events to pump into the game state, but the action queue is actually empty.

**Comment by joeyadams** [comment]
I found a straightforward fix for this (pull request #54), though there might be more robust ways to fix the issue at large (including #38).  In particular, it would be better if we did not rely on `heartbeat_count - dynamic_world->tick_count` always matching the size of the local user's queue.

**Comment by Hopper262** [comment]
Thanks for all the legwork you did to debug this! Figuring out the cause is usually 90% of the battle.

The Lua command didn't work because the method needs a colon, not a period: `Players[0]:teleport_to_level(18)` The colon causes the player object to be passed as the first argument, which is why the level number is read from the second spot, and why you had to hardcode player 0 in your branch.

Also, you can use the Up arrow key in the Lua console to recall the last command. So after typing in the first teleport command, the sequence of Backslash, Up, Return is another quick way to teleport repeatedly.
