### ISSUE TITLE
Marathon 2 closes on startup

### ISSUE THREAD

**Issue by gesamt** [Aleph-One-Marathon/alephone#57]
Running on a 2013 MBP, OS 10.11.6. Neither Marathon nor Infinity have any trouble starting up or running, but Marathon 2 will not launch: application opens, fades to black, and CTDs immediately, no error message. Taking a look in Console I see:

`10/2/16 9:30:53.162 AM Marathon 2[2070]: 09:30:53.162 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.`

`10/2/16 9:30:53.621 AM com.apple.xpc.launchd[1]: (org.bungie.source.Marathon2.153632[2070]) Service exited with abnormal code: 1`

Some cursory googling on the WARNING there suggests that a number of different projects on GitHub have run into that problem. However I'm not convinced that it has anything in particular to do with the launchd problem that follows it: the same message pops up in console when I launch Infinity, which doesn't have any problem running and therefore obviously doesn't have the launchd error. Even older versions of Marathon 2 seem to have this problem, which is particularly weird since some of the versions I have (unsuccessfully) tried are older than the last time I successfully ran the game. Any insight as to how this can be fixed is appreciated.

**Comment by Hopper262** [comment]
Your Marathon 2 preferences are probably corrupted. Please delete the file located at:

    /Users/<your user name>/Library/Preferences/Marathon 2/Marathon 2 Preferences

**Comment by gesamt** [comment]
I tried this, but it doesn't seem to have had any effect -- even if I delete the file and then attempt to open the game from a fresh install, I still get the CTD. However, on one occasion (not sure what prompted it) I got an error message saying "There were preferences-file parsing errors (see Marathon 2 Log.txt for details)". So I took a look at the Marathon 2 log file (Library/Logs/Marathon 2 Log.txt) and saw this for every failed attempt to open the game:

```
Trying OpenGL 16-bit mode (/Users/jeremiah/Source/alephone-svn/trunk/PBProjects/../Source_Files/RenderOther/screen.cpp:800)
```

Which suggests to me that it is OpenGL having problems. It jumped out at me because my username isn't jeremiah, nor is there any user jeremiah on this machine. While googling that file path I found a [reddit link](url=https://www.reddit.com/r/Marathon/comments/3h9mr9/trouble_starting_game_on_os_x_yosemite/) which is clearly referring to the same problem as I have. The guy in the thread there links a blank preferences files which would set the viewsize to 640x480, presumably circumventing whatever OpenGL screwup is leading to the CTD, but unfortunately his link is dead. Since it seems like whatever process the application is using to create a new preferences file isn't working correctly, is there any chance you could do the same?

**Comment by tagreene** [comment]
@Hopper262 I had this issue as well on all Marathon titles. Playing on a MBP 2016, with AMD Radeon 455 Graphics. MacOS High Sierra. Screen would go black on launch, then crash. Same Jeremiah entry in the logs.

I am able to get the game to run by changing `scmode_auto_resolution` to `false` in the preferences file. No idea if this will cause problems later in the game.

**Comment by gesamt** [comment]
I actually found a somewhat related solution to this lately and forgot to mention it here. The problem seems to come from how Aleph One works with the display scaling preferences on the Retina display. If I set the scaling slider all the way to “More Space” I get this crash on startup. If however I set the resolution to “Default for display” or even to a less extreme scaling option, it works fine. It isn’t really a problem for me to leave my display in such a mode so that’s what I’ve done, rather than be reduced to the ironic fate of having to play Marathon in my Windows partition. I’m still not sure why exactly this is a problem that Aleph One has or why it started (since I definitely used to be able to run it without adjusting my display settings) but at least it can be readily solved.

**Comment by Hopper262** [comment]
Please try the 1.3b1 release: it should do better at recovering from resolution issues. Any feedback is appreciated, so we can make the final 1.3 release as good as possible.

**Comment by esprecher** [comment]
> Additionally, it looks like this bug only appears when using a resolution on a MacBook other than 1280 X 800 or 1400 X 900.
> The new default resolution on the 2016 MacBook pros (1680 X 1050) will cause the bug to appear, though strangely 1680 X 1050 works fine when using an external monitor.

Thank you @tagreene so much!!  This bug was driving me nuts.  I tried a couple different resolutions, and then Maraton/AlephOne opened and worked seamlessly.  I would never have figured this out otherwise, thanks!!
