### ISSUE TITLE
Release 20150907 build fails against boost 1.56

### ISSUE THREAD

**Issue by jonirons** [Aleph-One-Marathon/alephone#6]
I'm on Gentoo x86_64, Linux kernel 4.0.5 (with Gentoo patches, probably). I previously built release 20150907 when I had boost 1.55 installed, but now that I've updated to 1.56, I get an error during build (`make`). I've tried it both `gcc` and `clang`. Error output for `gcc` is posted below. I reverted back to boost 1.55 and had no issues. If this is already fixed in a newer version, I'll be glad to test that version for you.

GitHub isn't letting me attach text files (nice) so, my apologies in advance for the below.

`gcc` as compiler:

```
InfoTree.cpp: In member function 'void InfoTree::save_xml(FileSpecifier) const':
InfoTree.cpp:80:63: error: no matching function for call to 'xml_writer_make_settings(char, int)'
          boost::property_tree::xml_writer_make_settings(' ', 2));
                                                               ^
InfoTree.cpp:80:63: note: candidate is:
In file included from /usr/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,
                 from /usr/include/boost/property_tree/detail/xml_parser_write.hpp:15,
                 from /usr/include/boost/property_tree/xml_parser.hpp:15,
                 from InfoTree.h:36,
                 from InfoTree.cpp:23:
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:55:30: note: template<class Str> boost::property_tree::xml_parser::xml_writer_settings<Str> boost::property_tree::xml_parser::xml_writer_make_settings(typename Str::value_type, typename Str::size_type, const Str&)
     xml_writer_settings<Str> xml_writer_make_settings(typename Str::value_type indent_char = (typename Str::value_type)(' '),
                              ^
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:55:30: note:   template argument deduction/substitution failed:
InfoTree.cpp:80:63: note:   couldn't deduce template parameter 'Str'
          boost::property_tree::xml_writer_make_settings(' ', 2));
                                                               ^
InfoTree.cpp: In member function 'void InfoTree::save_xml(std::ostringstream&) const':
InfoTree.cpp:87:63: error: no matching function for call to 'xml_writer_make_settings(char, int)'
          boost::property_tree::xml_writer_make_settings(' ', 2));
                                                               ^
InfoTree.cpp:87:63: note: candidate is:
In file included from /usr/include/boost/property_tree/detail/xml_parser_utils.hpp:15:0,
                 from /usr/include/boost/property_tree/detail/xml_parser_write.hpp:15,
                 from /usr/include/boost/property_tree/xml_parser.hpp:15,
                 from InfoTree.h:36,
                 from InfoTree.cpp:23:
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:55:30: note: template<class Str> boost::property_tree::xml_parser::xml_writer_settings<Str> boost::property_tree::xml_parser::xml_writer_make_settings(typename Str::value_type, typename Str::size_type, const Str&)
     xml_writer_settings<Str> xml_writer_make_settings(typename Str::value_type indent_char = (typename Str::value_type)(' '),
                              ^
/usr/include/boost/property_tree/detail/xml_parser_writer_settings.hpp:55:30: note:   template argument deduction/substitution failed:
InfoTree.cpp:87:63: note:   couldn't deduce template parameter 'Str'
          boost::property_tree::xml_writer_make_settings(' ', 2));
                                                               ^
make[3]: *** [InfoTree.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

`clang` output is pretty much identical.

**Comment by Hopper262** [comment]
Thanks for the report. I'm able to replicate the problem with Boost 1.58.0, and borrowed from mapnik/mapnik@65bd9e69260be0b82732b4606d048c85b22f3d8c to get master compiling again.

To get a working Aleph One again, you can build a [current Git snapshot](https://github.com/Aleph-One-Marathon/alephone/archive/master.zip) and run "./autogen.sh" instead of "./configure". I'm currently working through some other library updates, and might do another release before I switch to SDL 2 and go dark for a few months.

**Comment by jonirons** [comment]
Thanks! Is the snapshot compatible with the current release on the
metaserver?

On Fri, Oct 9, 2015 at 9:18 PM, Jeremiah Morris <notifications@github.com>
wrote:

> Thanks for the report. I'm able to replicate the problem with Boost
> 1.58.0, and borrowed from mapnik/mapnik@65bd9e6
> <https://github.com/mapnik/mapnik/commit/65bd9e69260be0b82732b4606d048c85b22f3d8c>
> to get master compiling again.
>
> To get a working Aleph One again, you can build a current Git snapshot
> <https://github.com/Aleph-One-Marathon/alephone/archive/master.zip> and
> run "./autogen.sh" instead of "./configure". I'm currently working through
> some other library updates, and might do another release before I switch to
> SDL 2 and go dark for a few months.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Aleph-One-Marathon/alephone/issues/6#issuecomment-147020096>
> .
>



-- 
Jon Irons

**Comment by Hopper262** [comment]
Yes, the current code is compatible with both 1.2 and the preview. I don't plan to change any network or gameplay behaviors until after 1.3 comes out, which is definitely a change of pace from the last few releases.

If you run into any problems with the automake or whatever, let me know and I'll put a tarball together. I expect you'll be just fine on Gentoo, though.

**Comment by jonirons** [comment]
Compilation went fine and I didn't notice any problems with a cursory test.
