### ISSUE TITLE
too many monsters freeze

### ISSUE THREAD

**Issue by KRAT3** [Aleph-One-Marathon/alephone#60]
i've noticed that when there are too many monsters some of them freezes, can you tell me why?

**Comment by Harv696** [comment]
I have this issue as well.

**Comment by treellama** [comment]
There's a limit to how many monsters are active at one time. If you're using a scenario designed for the higher monster limit in old versions of Aleph One, you can install this plugin to restore those limits: http://simplici7y.com/items/aleph-one-previous-ai

**Comment by Harv696** [comment]
Thanks!

**Comment by KRAT3** [comment]
i didn't tried it yet, but thanks anyway
