### ISSUE TITLE
Enemies don't attack in Rubicon

### ISSUE THREAD

**Issue by Harv696** [Aleph-One-Marathon/alephone#62]
Some enemies, I think especially when there's too many of them, don't attack. This doesn't occur when they teleport in, but when they're already spawned. Instead they just loop whatever "alert" sound they do but don't even move. Some may wake up if I shoot them first, but sometimes not.

This is in the latest version of Rubicon.

**Comment by treellama** [comment]
This is Rubicon X? Install this plugin: http://simplici7y.com/items/aleph-one-previous-ai to restore the AI limits that Rubicon X was designed for.

**Comment by orbea** [comment]
@Hopper262 Could you elaborate on what needs to be done to fix the scenarios so they do not need this plugin?

**Comment by Hopper262** [comment]
@orbea Here's the full explanation from [this post](http://pfhorums.com/viewtopic.php?f=13&t=37859&p=160982#p160982)

In the distant past, Aleph One expanded several built-in engine limits, to allow for bigger scenarios than the computers of 1995 could play. This included a limit on the number of monsters moving around, to allow for more intense battles with swarms of AI enemies.

This had a downside, though: the increased limit can change the gameplay of older scenarios, tuned for the original smaller number. In some levels built for M2 or Infinity, too many monsters can wake up and leave their ambush spots to chase you, disrupting the intended difficulty and pacing of battles.

Aleph One 1.1 reduces this AI limit to its original value, to restore the intended gameplay of classic scenarios. Treellama and I had to choose between compatibility with older single-player maps and compatibility with newer ones. More maps were made for the original engines than for Aleph One, and newer maps' creators are more likely to be around to release updates, so this was the lesser of two evils.

**Players:** To restore the earlier behavior for scenarios that broke under 1.1, use [this plugin](
http://simplici7y.com/items/aleph-one-previous-ai).

**Scenario makers:** To use the pre-1.1 monster limits, include this MML in your map or scenario:

```xml
<marathon>
  <dynamic_limits>
    <paths value="128"/>
  </dynamic_limits>
</marathon>
```

**Comment by orbea** [comment]
@Hopper262 Thank you very much for the explanation, it seems both `Eternal X`and `Marathon Phoenix` are already fixed, I don't have `Kill Them All` so I haven't checked that yet.

**Comment by orbea** [comment]
I've attempted to fix Rubicon by adding `scripts/AI` which contains the MML snippet from above, it seems to work although I have not played the game very much honestly.
