### ISSUE TITLE
"Couldn't initialize SDL (Failed to connect to the Mir Server)"

### ISSUE THREAD

**Issue by diqrtvpe** [Aleph-One-Marathon/alephone#63]
When running alephone on one of my Ubuntu machines I got the error "Couldn't initialize SDL (Failed to connect to the Mir Server)". This did not happen on another one of my machines, and I'm not sure why, as they are running the same version of Ubuntu and to my knowledge I haven't installed different Mir packages on one or the other.

I was able to work around this issue by changing my configure command to be "SDL_VIDEODRIVER=x11 ./configure", after which it ran properly. I'm mostly submitting this issue so that if anyone else runs into this problem they can find the workaround. Thanks!

**Comment by zztttt** [comment]
did you meet this error when you were using "spring init" ? I encounter this now, but this project does not seem like a spring project.

**Comment by ccallahan** [comment]
The build system isn't spring, it is an autotools-based setup. If I may ask, what made you think it was spring-based? AFAIK, spring only works for Java-based programs.

**Comment by zztttt** [comment]
> The build system isn't spring, it is an autotools-based setup. If I may ask, what made you think it was spring-based? AFAIK, spring only works for Java-based programs.

because I happend to run into this problem yesterday when build a spring-based project, and I searched for the solution through Google, then it leads me to this issue...Actually I don't understand this repository at all.
