### ISSUE TITLE
backguar compat with older boots for compiling in other platforms

### ISSUE THREAD

**Issue by mckaygerhard** [Aleph-One-Marathon/alephone#7]
please support older versions of boost filesystems

due commit 9f4a40a60ece60024f419b6500388e8d281cabd5 now i cannot compile in some older linux on embebed devices 

with that now alephone need boost 1.53 as minimun.. 

can be improved with a macro if-else conditional that select wich version are and use old code if older version are present

**Comment by darealshinji** [comment]
You could try to lower the required minimum version for `AX_BOOST_BASE` in configure.ac and see if it builds.

**Comment by mckaygerhard** [comment]
i have done, need a macro check on two parts, the firts are in `configure.ac` around line 74 +/-9 with this patch:

```
 AC_CHECK_HEADERS([unistd.h pwd.h])
 
 dnl Check for boost functions and libraries.
-AX_BOOST_BASE([1.53.0],
+AX_BOOST_BASE([1.42.0],
               ,
-              [AC_MSG_ERROR([You need Boost 1.53.0 or higher to build Aleph One.])])
+              [AC_MSG_ERROR([You need Boost 1.42.0 or higher to build Aleph One.])])
 AX_BOOST_SYSTEM
 AS_IF([ test "x$BOOST_SYSTEM_LIB" != "x" ],
       [ LIBS="$BOOST_SYSTEM_LIB $LIBS" ],
```

but the second i reported in the issue number #8 i made a more huge conditional for boost check and sustitue the entire code (yeah a nasty solution, but i'm not familliar with boost) so  the error that raises if i dont  revert the improvements to treeinfo are:

```
In file included from WadImageCache.cpp:29:
../../Source_Files/XML/InfoTree.h:38:37: error: boost/range/any_range.hpp: No existe el fichero o el directorio
In file included from WadImageCache.cpp:29:
../../Source_Files/XML/InfoTree.h:120: error: ISO C++ forbids declaration of ‘any_range’ with no type
../../Source_Files/XML/InfoTree.h:120: error: typedef name may not be a nested-name-specifier
../../Source_Files/XML/InfoTree.h:120: error: expected ‘;’ before ‘<’ token
../../Source_Files/XML/InfoTree.h:121: error: ‘const_child_range’ does not name a type
WadImageCache.cpp: In member function ‘std::string WadImageCache::image_to_new_name(SDL_Surface*, int32*) const’:
WadImageCache.cpp:126: error: ‘to_string’ is not a member of ‘boost::uuids’
```

**Comment by mckaygerhard** [comment]
hi, i solved using the stable release due the commit of usage of treeinfo are too huge for current main master.. commit 9f4a40a causes alephone doesn **not compile in most  embebed devices such gp2x or older linuxes**

i able to compile usin not master, i use the last stable release and with some little patches got until this error:

```
preferences.cpp:103:35: error: boost/algorithm/hex.hpp: no such file or directory
preferences.cpp:642: error: 'hex' its not a member of boost:algorithm
```
so then: **how could i generate hex string for connection to pass user crdentials without using the newer hex function not available in boost 1.42?**

i copy the suggestion of @darealshinji here as cited here, but this are not viable due the resulting binary will depend of recent changes in glibc and stdlib, **so when i run the resulting binary got error loading required libc6 library version and sdtlib, hat's due level optimization and flags using in the project, so this behabior are not suitable:** ue i used glibc 2.7 and glibc 2.10 on the systems, by examble due performance in gp2x i used glibc 6.7 that load more faster rather than recent...
here the cited suggestion that does not work in this behavior:
> You could try to build alephone on a newer system and link most dependencies statically. The resulting binary should work on most Linux systems.

>Here's a script for -Ubuntu- winbuntu 14.04 to build a portable binary (still requires OpenGL and SDL1.2 runtime):

```
#!/bin/sh
set -e
set -v

git clone --depth 1 https://github.com/Aleph-One-Marathon/alephone.git
cd alephone
git clone --depth 1 --branch release/2.8 https://github.com/FFmpeg/FFmpeg.git ffmpeg
#git clone --depth 1 git://source.ffmpeg.org/ffmpeg.git ffmpeg
curdir="$PWD"

cd ffmpeg
./configure --prefix="$curdir/libs" --enable-small --disable-runtime-cpudetect \
  --disable-debug --disable-asm --disable-programs --disable-doc --disable-hwaccels \
  --disable-bzlib --disable-lzma --disable-sdl --disable-xlib --disable-zlib
make -j4
make install
cd ..

sudo apt-get install libsdl1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev libboost-all-dev libpng12-dev

autoreconf -if
export PKG_CONFIG_PATH=libs/lib/pkgconfig
export CFLAGS="-O3 -Wall -Wno-sign-compare -Wno-maybe-uninitialized -fstack-protector -fno-strict-aliasing -ffunction-sections -fdata-sections -D_FORTIFY_SOURCE=2"
export CXXFLAGS="$CFLAGS -Wno-reorder -Wno-narrowing"
export LDFLAGS="-s -Wl,-z,relro -Wl,-z,defs -Wl,--gc-sections"
./configure --without-mad --without-sndfile --without-vorbis --without-smpeg \
  --without-speex --without-alsa --without-curl --without-zzip
make -j4

cd Source_Files
g++ $LDFLAGS -o alephone shell.o shell_misc.o \
CSeries/libcseries.a Files/libfiles.a FFmpeg/libffmpeg.a GameWorld/libgameworld.a Input/libinput.a Lua/liba1lua.a \
Misc/libmisc.a ModelView/libmodelview.a Network/libnetwork.a Network/Metaserver/libmetaserver.a \
RenderMain/librendermain.a RenderOther/librenderother.a Sound/libsound.a XML/libxml.a CSeries/libcseries.a \
Files/libfiles.a FFmpeg/libffmpeg.a GameWorld/libgameworld.a Input/libinput.a Lua/liba1lua.a Misc/libmisc.a \
ModelView/libmodelview.a Network/libnetwork.a Network/Metaserver/libmetaserver.a RenderMain/librendermain.a \
RenderOther/librenderother.a Sound/libsound.a TCPMess/libtcpmess.a XML/libxml.a LibNAT/libnat.a \
-Wl,-Bstatic -lexpat -lpng12 -lz -Wl,-Bdynamic \
-L"$curdir/libs/lib" -lavformat -lavcodec -lswresample -lswscale -lavutil -lm \
-Wl,-Bstatic -lboost_filesystem -lboost_system -Wl,-Bdynamic \
-lSDL -lSDL_net -lSDL_ttf -lGL -lGLU -pthread -lpthread -static-libstdc++ -static-libgcc
```

**Comment by darealshinji** [comment]
stdlib changes shouldn't be a problem if you link with `-static-libstdc++`.

As for the glibc problem, here are some suggestions that might or might not be a solution for you:
 * Stick with an older version and backport only important bugfixes and newer features you absolutely need.
 * Link the whole binary statically. That might not be as easy as it sounds and the resulting binary might still not run.
 * Build the binary with the provided script and ship the binary with the glibc libraries and the dynamic linker from the distribution it was build on. Then run alephone with the newer ld.so and add the newer glibc libraries to the search path, like that: `LD_LIBRARY_PATH=./libs/ ./ld-linux-x86-64.so.2 alephone`

**Comment by mckaygerhard** [comment]
thanks @darealshinji i goin for the one suggestion, i already made the statically option and works only for a sid debian (between squeeze and wheeze), but for eepc installation or some geento and for my gp2x does not due u already said.. does not run...

so then i stick and older version, i take the lasted stable 1.2 and made some fix, litle, only two conditionals, one in string conversion and one on the configure.ac script.. but now i need a last backport fix:

```
preferences.cpp:103:35: error: boost/algorithm/hex.hpp: no such file or directory
preferences.cpp:642: error: 'hex' its not a member of boost:algorithm
```
the code takes the response http and i dont know if convert the string url to a hex result token or only converts the format to and string due already are a hex..

how could i made a code on c that represends that portion?:
```
		std::string token = boost::algorithm::hex(conn.Response());
		url += "?token=" + token;
```
due the hex.hpp are not present in boost 1.42!

please help with that to make packages that works for my children in class with their devices,due there have recicled devices...

**Comment by darealshinji** [comment]
Here are 32 and 64 bit builds for Linux, with most libraries linked statically, including stdlib and libgcc. A copy of glibc 2.19, which will be used via `LD_LIBRARY_PATH`, is included too.
https://github.com/darealshinji/alephone/releases/download/20150907-2/alephone-portable-20150907-1.3a1-linux.tar.xz
Remaining dependencies are: libSDL-1.2.so.0, libSDL_net-1.2.so.0, libSDL_ttf-2.0.so.0, libGL.so.1, libGLU.so.1

**Comment by mckaygerhard** [comment]
the remaining dependencies are solved there are main system sdl optimized libs for eepc and gp2x in the linux box.. i tested and runs aceptable in a debian squeeze oldstable box, tomorrow i'll test in the devices..

there's any possibility to change the code  cited.. that able to modify my own binary event using a portable pre-build!
the piece of code its used only for auth against the servers for onlyne game but may be ussefully fix that problem and able to build for any linu version of boost
