### ISSUE TITLE
Crashing after Habe Quiddam 

### ISSUE THREAD

**Issue by ObsidianCarnageX12** [Aleph-One-Marathon/alephone#72]
It spits this out into the error log and the hud disappears .
less than a second later the game just Crashes to desktop.

[string "HUD Lua"]:171: bad argument #1 to '__index' (Screen expected, got userdata) (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)
attempt to index a nil value (lua_script.cpp:1106)

**Comment by orbea** [comment]
Is this still an issue? What is Habe Quiddam? How can I try to reproduce this? What OS? I'm not sure there is enough information to determine much here.

**Comment by Hopper262** [comment]
@orbea Habe Quiddam is a level in Marathon 1. Judging by the line number in the error, I believe this was using the Enhanced HUD.

I haven't been able to replicate this error. Some Lua bugs have been fixed in the [1.3 beta releases](https://github.com/Aleph-One-Marathon/alephone/releases). @ObsidianCarnageX12 can you try the most recent beta (or compile from master) and see if it still crashes? Thanks.

**Comment by ObsidianCarnageX12** [comment]
It seems to be fixed since the beta for sure , i can run through the game without crashes
