### ISSUE TITLE
Chapter Screen Error

### ISSUE THREAD

**Issue by Olroda** [Aleph-One-Marathon/alephone#73]
Well met!

I have an error to report.
The screen is black when the game is supposed to show a chapter screen from Counterattack and onwards.
The background sound effect is still audible, and the game loads the next chapter as it should.

After testing fairly extensively, on two separate computers, I've concluded that it doesn't occur in Open GL (Classic or Shader). Also, the initial chapter screen (Arrival) shows up fine with any renderer.

Windows 7 Professional x64 / Windows 7 Ultimate x32.
GeForce GTX 980, driver version: 21.21.13.7878 / GeForce 8800, driver version unknown, likely current).
Aleph One version 20150620: Marathon scenario. Fresh, untampered install (no settings changed).
Renderer: Software.

**Comment by Hopper262** [comment]
This should be fixed in 222bbc5, and will be part of the next release (1.3b3). Thanks for the report!
