### ISSUE TITLE
Simultaneous mouse and joystick support.

### ISSUE THREAD

**Issue by Kamastein** [Aleph-One-Marathon/alephone#76]
I was wanting to use that because I want to play Aleph One with the Steam Controller and that would be the best arrangement for it. However, I found one can only enable one or the other but not both.

**Comment by Hopper262** [comment]
Please try the 1.3b1 release: it has simultaneous mouse and controller support. Any feedback is appreciated, so we can make the final 1.3 release as good as possible.
