### ISSUE TITLE
Marathon crashing on retina MacBook pros

### ISSUE THREAD

**Issue by rawkfistn1** [Aleph-One-Marathon/alephone#77]
I downloaded all 3 bundled games from the aleph one page and tried to run them on my new MacBook Pro, for each one the app will open, the screen will turn black for a second, then the app closes out and that's it. At first I thought it was probably just something on my computer so I tried it on my wife's and my brother's older MacBook Pros (still retina) and the same thing happened for them. I then tried it on my old MacBook (pre-retina) and it worked great. I also tried downloading just the scenario by itself and aleph one separately and seeing if that worked but ran into the same problem. 

This is from Terminal-
"Built with Lua scripting enabled.
WARNING: Failed to initialize OpenGL with 24 bit depth
WARNING: Retrying with 16 bit depth
Can't open video display (Failed to find display resolution: 1680x1050x32)
WARNING: Failed to initialize OpenGL with 24 bit colour
WARNING: Retrying with 16 bit colour
Can't open video display (Failed to find display resolution: 1680x1050x32)
logout
Saving session...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found."

Any help would be great. Sorry if this isn't the right place to come to with this issue. Thanks

**Comment by rawkfistn1** [comment]
Well, somewhat unsurprisingly I guess, I found that if I lower my display resolution it can run okay.  If there are any other tips or tricks though to forego this step, those would be appreciated. Thanks!

**Comment by tagreene** [comment]
I had this problem as well - see my comment on #57

**Comment by Hopper262** [comment]
Please try the 1.3b1 release: it should do better at recovering from resolution issues. Any feedback is appreciated, so we can make the final 1.3 release as good as possible.
