### ISSUE TITLE
Build failure with ffmpeg github master

### ISSUE THREAD

**Issue by orbea** [Aleph-One-Marathon/alephone#93]
OS: `Slackware64-current`
`gcc-7.3.0`
`ffmpeg-2018.03.31_5f83935_master-x86_64-1_git`

When building the alephone github master (b0520129e821a1a2d8b94eefd3dc309606f3561d) I with the ffmpeg github master I encountered this build failure.
```
make[3]: *** [Makefile:426: Movie.o] Error 1
make[3]: Leaving directory '/tmp/SBo/alephone/Source_Files/FFmpeg'
make[2]: *** [Makefile:601: all-recursive] Error 1
make[2]: Leaving directory '/tmp/SBo/alephone/Source_Files'
make[1]: *** [Makefile:551: all-recursive] Error 1
make[1]: Leaving directory '/tmp/SBo/alephone'
make: *** [Makefile:445: all] Error 2
```
Full build log - https://pastebin.com/KHnb3EL5

**Comment by orbea** [comment]
Actually, it builds with PR https://github.com/Aleph-One-Marathon/alephone/pull/89.

This issue can be closed when that or a similar fix is merged to the master branch.

**Comment by h3xx** [comment]
Pretty sure this is closed by 902cd09ef8a83ce318365300f46c4c0801e5ca19.

**Comment by Hopper262** [comment]
Yep, should be. The warnings are still on my to-do list but the build should continue. Thank you for the patch, @h3xx !

**Comment by orbea** [comment]
Thanks! It built here too.
