### ISSUE TITLE
1.2.1 backports for newer compilers

### ISSUE THREAD

**Issue by bentley** [Aleph-One-Marathon/alephone#96]
alephone-1.2.1 and alephone-1.3a1, both released in 2015, no longer build as of clang-6.0.0, the default on OpenBSD.

    c++ -DHAVE_CONFIG_H -I. -I../..  -I../../Source_Files/Files -I../../Source_Files/GameWorld -I../../Source_Files/Input -I../../Source_Files/Misc -I../../Source_Files/ModelView -I../../Source_Files/Network -I../../Source_Files/RenderMain -I../../Source_Files/RenderOther -I../../Source_Files/Sound -I../../Source_Files/XML -I../../Source_Files/Network/Metaserver -I../../Source_Files/TCPMess -I/usr/local/include/libpng16 -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include/opus -I/usr/local/include -I/usr/local/include -I/usr/local/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -I/usr/X11R6/include -DXTHREADS -DSDL -DSPEEX  -O2 -pipe -g -MT csalerts_sdl.o -MD -MP -MF $depbase.Tpo -c -o csalerts_sdl.o csalerts_sdl.cpp &&\
    mv -f $depbase.Tpo $depbase.Po
    In file included from csalerts_sdl.cpp:38:
    In file included from ../../Source_Files/Misc/sdl_widgets.h:52:
    In file included from ../../Source_Files/GameWorld/map.h:57:
    ../../Source_Files/GameWorld/world.h:208:13: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    int32 isqrt(register uint32 x);
                ^~~~~~~~~
    In file included from csalerts_sdl.cpp:37:
    In file included from ../../Source_Files/Misc/sdl_dialogs.h:33:
    In file included from /usr/local/include/boost/function.hpp:70:
    In file included from /usr/local/include/boost/preprocessor/iteration/detail/iter/forward1.hpp:47:
    In file included from /usr/local/include/boost/function/detail/function_iterate.hpp:14:
    In file included from /usr/local/include/boost/function/detail/maybe_include.hpp:15:
    /usr/local/include/boost/function/function_template.hpp:159:33: error: called object type 'nullptr_t' is not a function or function pointer
              BOOST_FUNCTION_RETURN((*f)(BOOST_FUNCTION_ARGS));
                                    ^~~~
    /usr/local/include/boost/function/function_template.hpp:81:36: note: expanded from macro 'BOOST_FUNCTION_RETURN'
    #  define BOOST_FUNCTION_RETURN(X) X
                                       ^
    /usr/local/include/boost/function/function_template.hpp:925:53: note: in instantiation of member function 'boost::detail::function::void_function_obj_invoker0<nullptr_t, void>::invoke' requested here
            { { &manager_type::manage }, &invoker_type::invoke };
                                                        ^
    /usr/local/include/boost/function/function_template.hpp:716:13: note: in instantiation of function template specialization 'boost::function0<void>::assign_to<nullptr_t>' requested here
          this->assign_to(f);
                ^
    /usr/local/include/boost/function/function_template.hpp:1061:5: note: in instantiation of function template specialization 'boost::function0<void>::function0<nullptr_t>' requested here
        base_type(f)
        ^
    ../../Source_Files/Misc/sdl_widgets.h:1082:5: note: in instantiation of function template specialization 'boost::function<void ()>::function<nullptr_t>' requested here
                    , m_callback (NULL)
                      ^
    1 warning and 1 error generated.
    gmake[3]: *** [Makefile:403: csalerts_sdl.o] Error 1

Post‐#82, everything builds without a problem (including Git master). Unfortunately backporting #82 is not enough to resolve the above build failure. I would much prefer a new release, but [it looks like 1.3 will be a while in coming](http://pfhorums.com/viewtopic.php?p=183006#p183006). At this point I’m fairly stuck.

**Comment by Hopper262** [comment]
There's a 1.3b1 release now, I'd appreciate any feedback as we work toward a stable 1.3 in the coming weeks.
