### ISSUE TITLE
Alephone fails to start if no theme plugin is installed, throws misleading error

### ISSUE THREAD

**Issue by ravenshining** [Aleph-One-Marathon/alephone#98]
As I mentioned in my PR #97 , not thinking this was a bug per se, A1 fails to start and throws the error:
`fatal alert (ID=-1): Please be sure the files 'Map', 'Shapes', 'Images' and 'Sounds' are correctly installed and try again. (csalerts_sdl.cpp:210)`
if no theme plugin is found in the scenario folder.

Confirmed the behaviour by taking a good scenario, removing the theme from its plugins folder, starting A1 via the terminal, and it throws the error.  Trash the preferences, no difference.  Put the theme back, the error disappears.  

On my system (Debian 8) the A1 binary is living under /usr/local/bin.  If I put a scenario under /usr/local/share/AlephOne, A1 will start using that scenario if I simply type "alephone" into a terminal, and if so started it will search /usr/local/share/AlephOne/Plugins/ for theme plugins, but if I start a scenario elsewhere (e.g., "alephone ~/AlephOne/Infinity/") it will NOT look in /usr/local/share/AlephOne.

If I place a theme plugin under ~/.alephone/Plugins, A1 will use it provided there is also a theme plugin present in the scenario folder.  It will not start and throw the error if there is only a theme in the ~/.alephone/Plugins folder.

The source I compiled is from February 26th, 2017.

Again, sorry I didn't think this was a bug.  I though it was normal behaviour for A1 to not run if it did not have an interface, and thought making a PR would be the most polite way to propose a change to the error message.

**Comment by ravenshining** [comment]
I found another way to trigger this:  Start a scenario that has theme a plugin(s), disable all plugins under environment preferences, quit, and restart A1.  With all themes disabled in the preferences file, it throws the error.

**Comment by Hopper262** [comment]
I was finally able to set up a decent Linux test machine and replicate this bug. I should be able to track down the cause by the next beta. Thanks for your efforts in researching and reporting this one!
